/* ui.js — rendering. Vanilla DOM, no build. Everything a player reads here is in-world (STORY_BIBLE Part II).
   Views: intro, home, grid, level, jobs (the board), run (the dive), deck, shop, key (codex), stats (record), crew, log (journal). Dev panel with ?dev=1. */
(function(){
  const $ = s => document.querySelector(s); const app = () => $('#app');
  const esc = s => String(s == null ? '' : s).replace(/[&<>"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));
  let view = 'home', lastView = null, cur = { stage: null, level: null, beat: 0, job: null, synced: null, dev: 'lint', dmResult: null, devOpen: false, goldenRes: null, shopMsg: null };
  const P = () => window.PLATFORM || {};
  const A = c => String.fromCharCode(65 + c);

  function rich(text){ return esc(text).replace(/\[\[([^\]]+)\]\]/g, (m, t) => { const def = GLOSSARY[t.toLowerCase()] || 'See the codex.'; return '<span class="term" data-def="' + esc(def) + '">' + esc(t) + '</span>'; })
      .replace(/"([^"]{2,80}?)"/g, (m, q) => /^[a-z0-9 \-\/\.\,]+$/i.test(q) && /^(show|spanning-tree|configure|interface|enable|write|copy|ip |vlan|hostname|switchport|do |no |root|end$|ping|access-list|router)/i.test(q) ? '<code>' + q + '</code>' : m); }
  function toast(msg, cls){ let t = $('.toast'); if (!t) { t = document.createElement('div'); t.className = 'toast'; document.body.appendChild(t); } const d = document.createElement('div'); d.className = cls || ''; d.textContent = msg; t.appendChild(d); setTimeout(() => d.remove(), 4200); }
  const portraits = {}; // npc id -> true (file exists) | false (missing); unknown until the preload answers
  function preloadPortraits(){ Object.keys(NPCS).forEach(id => { if (portraits[id] !== undefined) return; const im = new Image(); im.onload = () => { portraits[id] = true; }; im.onerror = () => { portraits[id] = false; }; im.src = 'assets/npc/' + id + '.png'; }); }
  function npcEl(id, size, look){ const n = NPCS[id] || { name: id, look: look || { seed: String(id) } }; const wrap = document.createElement('span'); wrap.style.display = 'inline-block'; wrap.style.lineHeight = '0';
    const apply = el => { if (size) { el.style.width = size + 'px'; el.style.height = size + 'px'; } return el; };
    const sprite = () => { const cv = document.createElement('canvas'); Sprite.animate(cv, look || n.look); wrap.innerHTML = ''; wrap.appendChild(apply(cv)); };
    if (NPCS[id] && portraits[id] !== false) { const img = new Image(); img.alt = n.name; img.decoding = 'async'; img.style.background = '#0b0f18'; img.src = 'assets/npc/' + id + '.png'; img.onload = () => { portraits[id] = true; }; img.onerror = () => { portraits[id] = false; sprite(); }; wrap.appendChild(apply(img)); return wrap; }
    sprite(); return wrap; }
  const npcSlot = (id, size) => '<span class="npcslot" data-npc="' + esc(id) + '" data-size="' + size + '"></span>';
  const pSlot = (p, size) => '<span class="npcslot" data-protege="' + esc(p.id) + '" data-size="' + size + '"></span>';
  const noDay = s => String(s || '').replace(/^Days? [\d–,\- ]+ · /, '');

  // ---- HUD --------------------------------------------------------------------------
  function hud(){ const s = Game.state, c = Game.classFor(s.rep), nx = Game.nextClass(s.rep), rb = Game.riteBlocking(); const pct = nx ? Math.min(100, Math.round(((s.rep - c.min) / (nx.min - c.min)) * 100)) : 100;
    const openJobs = JOBS.filter(j => Game.jobStatus(j).locked.length === 0 && !s.jobsDone[j.id]).length; const alive = Protege.active(s.roster).length, lost = Protege.lost(s.roster).length; const dm = Game.dm.pending(); const u = window.Auth && Auth.user();
    return '<div class="hud"><div class="logo">NETRUNNER<small>://</small>CCNA</div><div class="handle">handle <b>' + esc(s.handle || '—') + '</b>' + (u ? ' <span class="signin">' + (u.avatar ? '<img src="' + esc(u.avatar) + '">' : '') + esc(u.name) + '</span>' : '') + '</div><span class="cls ' + c.id + '">CLASS ' + c.id + '</span>' +
      '<div class="rep"><span>REP ' + s.rep + (nx ? (rb ? ' · Class ' + nx.id + ' waits on the rite: ' + esc(rb.title) : ' / ' + nx.min + ' → Class ' + nx.id) : ' · top of the street') + '</span><div class="bar"><i style="width:' + pct + '%"></i></div></div><div class="creds">' + (s.creds || 0) + ' <small>creds</small></div>' +
      '<div class="body" title="a gig costs food and chrome at jack-in. zero on either is a flatline."><div class="m food' + (s.body.food <= 30 ? ' low' : '') + '"><span>FOOD</span><div class="bar"><i style="width:' + s.body.food + '%"></i></div><b>' + s.body.food + '</b></div><div class="m chrome' + (s.body.chrome <= 30 ? ' low' : '') + '"><span>CHROME</span><div class="bar"><i style="width:' + s.body.chrome + '%"></i></div><b>' + s.body.chrome + '</b></div></div>' +
      (s.roster.list.length ? '<div class="crew">crew <b>' + alive + '</b>' + (lost ? ' <span class="lost">†' + lost + '</span>' : '') + '</div>' : '') +
      '<div class="nav">' + [['home', 'MAP'], ['grid', 'GRID'], ['jobs', 'BOARD'], ['crew', 'CREW'], ['shop', 'STALL'], ['deck', 'DECK'], ['key', 'CODEX'], ['stats', 'RECORD'], ['log', 'JOURNAL']].map(([v, l]) => '<button data-v="' + v + '" class="' + (view === v || (v === 'grid' && view === 'level') || (v === 'jobs' && view === 'run') ? 'on' : '') + (v === 'crew' && dm ? ' dmping' : '') + '">' + l + (v === 'jobs' && openJobs ? '<span class="badge">' + openJobs + '</span>' : '') + (v === 'crew' && dm ? '<span class="badge">CALL</span>' : '') + '</button>').join('') +
      (window.Auth && Auth.configured && !u ? '<button id="signin" title="keep your record across decks">SIGN IN</button>' : '') + (u ? (Auth.needsToken() ? '<button id="reconnect" class="warn" title="your record is not reaching your Drive right now. reconnect">RECONNECT</button>' : '') + '<button id="signout">SIGN OUT</button>' : '') + (P().dev ? '<button id="devtoggle" class="dev">DEV</button>' : '') + '<button id="logout" title="back to the door. your record stays under this handle">LOG OUT</button></div></div>'; }

  // ---- views ------------------------------------------------------------------------
  function intro(){ return '<div class="intro"><h1 class="glitch">NETRUNNER<span>://</span>CCNA</h1><p>Watson district. Old switches, thin budgets, people who remember every outage by what they lost. The corpo cores downtown run gear the street never sees. The street runs the old stuff, and the old stuff still keeps the clinic open. You are new, you need work, and somebody vouched for you.<br><b>THE GRID</b> is the people who keep the district running. Each of them works one part of the net, and they teach the way people teach: by showing you the thing that went wrong.<br><b>THE BOARD</b> is the work. Dispatch sends a gig, you dive, you fix it in the old tongue the boxes understand, and someone gets their day back.<br><b>THE CREW</b> are the kids who look up to you. The street has no junior tier, so you send them on the risky gigs, and they call you when it gets loud. Answer fast and right.</p>' +
      '<p><input id="handle" placeholder="your handle" maxlength="18" autocomplete="off"> <input id="pass" type="password" placeholder="passcode" maxlength="32" autocomplete="off"> <button class="btn mag" id="go">JACK IN</button></p><p class="muted" style="font-size:11px">new handle: pick any passcode and it registers. the deck remembers you until you LOG OUT. there are no chips and no manual saves: your record syncs after every talk and every gig.</p>' + (Game.profiles().length ? '<p class="muted" style="font-size:12px">saved on this deck: ' + Game.profiles().map(h => '<button class="btn ghost" data-resume="' + esc(h) + '" style="margin:2px 4px">' + esc(h) + '</button>').join('') + '</p>' : '') +
      (window.Auth && Auth.configured ? '<p><button class="btn ghost" id="signin">SIGN IN WITH GOOGLE</button></p>' : '') +
      '<div class="footer">The Board\'s syllabus follows Jeremy\'s IT Lab. Built alongside the notes of <a href="https://github.com/psaumur/CCNA_Course_Notes" target="_blank">psaumur</a> and <a href="https://github.com/sparrowjumpy/CCNA-Notes" target="_blank">sparrowjumpy</a>. The history is real. MIT.</div></div>'; }

  function home(){ const s = Game.state; const reads = Object.keys(s.read).length; const total = STAGES.reduce((a, st) => a + st.levels.length, 0); const done = Object.keys(s.jobsDone).length; const dm = Game.dm.pending();
    return (dm ? '<div class="panel" style="border-color:var(--mag)"><b class="mag">A call is waiting.</b> ' + esc(dm.open.split(':')[0]) + ' needs you. <button class="btn mag" data-v="crew">PICK UP</button> <span class="muted">the clock starts when you read it.</span></div>' : '') +
      (Game.body.low() ? '<div class="panel low"><b>You are running on empty.</b> food ' + s.body.food + ' · chrome ' + s.body.chrome + '. a dive costs both, and an empty runner does not come back. <button class="btn" data-v="shop">MARROW\'S STALL</button></div>' : '') +
      '<div class="panel"><h2>THE JOURNEY</h2><div class="muted">one district at a time. rep and class follow you. only one is lit so far.</div><div class="arcs" style="margin-top:12px">' +
      ARCS.map(a => '<div class="arc ' + (a.status === 'play' ? 'play' : 'lock') + '" ' + (a.status === 'play' ? 'data-v="grid"' : '') + '><div class="n">ARC ' + a.n + '</div><div class="t">' + a.title + '</div><div class="st">' + esc(a.sub) + '</div>' + (a.status === 'play' ? '<div style="margin-top:8px"><span class="tag on">lit</span><span class="tag">' + reads + '/' + total + ' met</span><span class="tag">' + done + '/' + JOBS.length + ' gigs</span></div>' : '<div style="margin-top:8px"><span class="tag lock">signal lost · not yet mapped</span></div>') + '</div>').join('') + '</div></div>' +
      '<div class="grid2"><div class="panel"><h2>THE GRID</h2><p class="dim">The people. Each one works a part of the net, and their name gives it away. Glowing <span class="term" data-def="Like this. Hover any glowing word for what the Board means by it.">words</span> are the ones the Board and the job will both use. Meeting someone slots a quickhack into your deck at zero. Using it on a dive is what makes it count.</p><button class="btn" data-v="grid">GO TO THE GRID</button></div>' +
      '<div class="panel"><h2>THE BOARD</h2><p class="dim">Dispatch sends a message, the client says what is wrong in their own words, and you dive. A live map of the building\'s net, the old tongue in your shell, a person beside you. Quickhacks only sharpen when you use them without help. Rites of passage pay big and change what people call you.</p><button class="btn mag" data-v="jobs">OPEN THE BOARD</button></div></div>'; }

  function grid(){ const s = Game.state; if (!cur.stage) cur.stage = (STAGES.find(st => st.status === 'live') || STAGES[0]).id; const st = STAGES.find(x => x.id === cur.stage);
    return '<div class="panel"><h2>THE GRID · WATSON</h2><div class="stages"><div class="stagelist">' + STAGES.map(x => { const n = x.levels.filter(l => s.read[l.id]).length; return '<button data-stage="' + x.id + '" class="' + (x.id === cur.stage ? 'on' : '') + '">' + esc(x.title) + '<span class="p">' + n + '/' + x.levels.length + '</span><br><span class="muted">' + esc(noDay(x.sub)) + '</span></button>'; }).join('') + '</div>' +
      '<div><div class="row" style="margin-bottom:10px;align-items:flex-start"><div class="npcbox" style="width:72px;flex:none">' + npcSlot(st.npc, 72) + '</div><div>' + (P().dev ? '<div class="muted" style="font-size:11px;letter-spacing:.14em">' + (st.status === 'live' ? '<span class="tag on">built</span>' : '<span class="tag">intro only</span>') + '</div>' : '') + '<div style="font-size:15px;font-weight:700;margin-top:4px">' + esc(NPCS[st.npc].name) + ' <span class="muted">· ' + esc(NPCS[st.npc].sys) + '</span></div><div class="dim">' + esc(NPCS[st.npc].role) + '</div></div></div>' +
      '<div class="levels">' + st.levels.map(l => '<div class="level ' + (s.read[l.id] ? 'done' : '') + '" data-level="' + l.id + '">' + (s.read[l.id] ? '<span class="chk">✓</span>' : '') + '<div class="who">' + esc(NPCS[l.npc].name) + '</div><div class="t">' + esc(l.title) + '</div><div class="s">' + esc(noDay(l.sub)) + '</div></div>').join('') + '</div></div></div></div>'; }

  function bdCard(b){ return '<div class="bd" style="position:relative"><span class="rec">REC</span><div class="card"><div class="k">BRAINDANCE · A RECORDING FROM THE OLD NET</div><div class="y">' + esc(b.year || '') + '</div><div class="t">' + esc(b.title || '') + '</div>' + (b.vibe ? '<div class="v">' + esc(b.vibe) + '</div>' : '') + '</div><div class="body">' + rich(b.text) + '</div></div>'; }
  function level(){ const l = Game.levelById(cur.level); const n = NPCS[l.npc]; const b = l.beats[cur.beat]; const last = cur.beat === l.beats.length - 1; let body = '';
    if (b.k === 'TALK') body = '<div class="speech"><div class="k">' + esc(n.name.toUpperCase()) + '</div>' + rich(b.text) + '</div>';
    if (b.k === 'LORE') body = (b.title && b.year) ? bdCard(b) : '<div class="speech lore"><div class="k">BRAINDANCE</div>' + rich(b.text) + '</div>';
    if (b.k === 'KIT') body = '<div class="speech kit"><div class="k">SLOTTED TO YOUR DECK</div>' + rich(b.text) + '<ul class="kitlist">' + b.kit.map(k => '<li><code>' + esc(k.cmd) + '</code> <span class="dim">' + rich(k.what) + '</span></li>').join('') + '</ul></div>';
    if (b.k === 'SCENE') body = '<div class="scene">' + (b.where ? '<div class="where">' + rich(b.where) + '</div>' : '') + (b.lines || []).map(ln => ln.who === 'you' ? '<div class="ln you"><span class="who">' + esc(Game.state.handle) + '</span>' + rich(ln.text) + '</div>' : ln.who === 'narr' ? '<div class="ln narr">' + rich(ln.text) + '</div>' : '<div class="ln"><span class="who">' + esc((NPCS[ln.who] || { name: ln.who }).name) + '</span>' + rich(ln.text) + '</div>').join('') +
      (b.choice ? '<div class="opts">' + b.choice.opts.map((o, i) => '<button data-opt="' + i + '" class="' + (cur.synced === i ? 'right' : '') + '">' + esc(o.say) + '</button>').join('') + '</div>' + (cur.synced != null ? '<div class="ln reply"><span class="who">' + esc((NPCS[b.choice.opts[cur.synced].who || l.npc] || {}).name || '') + '</span>' + rich(b.choice.opts[cur.synced].reply) + '</div>' : '') : '') + '</div>';
    if (b.k === 'SYNC') { const q = b.q; body = '<div class="speech sync"><div class="k">SOMEONE ASKS · the Board would too · no rep on the line</div>' + rich(q.prompt) + '<div class="opts">' + q.opts.map((o, i) => '<button data-opt="' + i + '" class="' + (cur.synced == null ? '' : i === q.a ? 'right' : i === cur.synced ? 'wrong' : '') + '">' + A(i) + '. ' + esc(o) + '</button>').join('') + '</div>' + (cur.synced == null ? '' : '<div style="margin-top:8px" class="' + (cur.synced === q.a ? 'good' : 'warn') + '">' + rich(cur.synced === q.a ? q.yes : q.no) + '</div>' + (q.why ? '<div class="why"><b>The answer is ' + A(q.a) + '. ' + esc(q.opts[q.a]) + '</b><br>' + rich(q.why) + '</div>' : '')) + '</div>'; }
    return '<div class="panel"><div class="row" style="justify-content:space-between"><h2>' + esc(l.title) + '</h2><button class="btn ghost" data-v="grid">← GRID</button></div><div class="muted" style="font-size:11px">' + esc(noDay(l.sub)) + '</div>' +
      '<div class="dlg" style="margin-top:14px"><div class="npcbox" id="npcbox">' + npcSlot(l.npc, 192) + '<div class="name">' + esc(n.name) + '</div><div class="sys">' + esc(n.sys) + '</div><div class="role">' + esc(n.role) + '</div></div>' +
      '<div>' + body + '<div class="dots">' + l.beats.map((x, i) => '<i class="' + (i <= cur.beat ? 'on' : '') + '"></i>').join('') + '</div><div class="row">' + (!last ? '<button class="btn" id="next"' + (b.k === 'SCENE' && b.choice && cur.synced == null ? ' disabled' : '') + '>NEXT ▸</button>' : '<button class="btn grn" id="finish">DONE HERE ✓</button>') + (cur.beat > 0 ? '<button class="btn ghost" id="prev">◂ BACK</button>' : '') +
      '<span class="muted" style="font-size:11px">' + (b.k === 'SYNC' && cur.synced == null ? 'answer or walk on. talking never sharpens a quickhack. using it on a dive does.' : b.k === 'SCENE' && b.choice && cur.synced == null ? 'say something to continue' : '') + '</span></div></div></div></div>'; }

  function jobs(){ const list = JOBS.map(j => ({ j, st: Game.jobStatus(j) })); const sel = cur.job ? list.find(x => x.j.id === cur.job) : null;
    return '<div class="panel"><h2>THE BOARD · DISPATCH</h2><div class="inbox"><div>' + list.map(({ j, st }) => '<div class="msg ' + (st.locked.length ? 'lock' : '') + (cur.job === j.id ? ' on' : '') + '" data-job="' + j.id + '"><span class="cls ' + j.cls + '">' + j.cls + '</span><div class="from">FROM ' + esc(NPCS[j.from].name.toUpperCase()) + ' · +' + j.rep + ' REP · ' + (j.creds || j.rep * 3) + ' CREDS' + (j.rite ? ' · <span class="mag">RITE OF PASSAGE</span>' : '') + '</div><div class="t">' + esc(j.title) + '</div><div class="meta">' + (!st.locked.length && Game.body.lethal(j) ? '<span class="red">☠ not as you are</span> · ' : '') + (st.done ? '✓ done ×' + st.done.times + (st.done.bestMs ? ' · best ' + Math.round(st.done.bestMs / 1000) + 's' : '') + ' · again for 40%' : st.locked.length ? '🔒 ' + st.locked.length + ' thing' + (st.locked.length > 1 ? 's' : '') + ' first' : '● open') + '</div></div>').join('') + '</div>' +
      '<div>' + (sel ? jobDetail(sel.j, sel.st) : '<div class="muted">pick a message. locked gigs tell you who to talk to first.</div>') + '</div></div></div>'; }
  function jobDetail(j, st){ return '<div class="row"><span class="cls ' + j.cls + '">CLASS ' + j.cls + '</span><b>' + esc(j.title) + '</b><span class="muted">from ' + esc(NPCS[j.from].name) + ' · +' + j.rep + ' rep · ' + (j.creds || j.rep * 3) + ' creds' + (st.done ? ' (again: 40%)' : '') + (j.team && j.team.min ? ' · crew of ' + j.team.min : '') + '</span></div>' + (j.rite ? '<div class="mag" style="font-family:var(--disp);font-size:11px;letter-spacing:.2em;margin-top:6px">RITE OF PASSAGE · big payday · the district will remember</div>' : '') + '<div class="brief">' + rich(j.brief) + '</div>' +
      '<div class="muted" style="font-size:11px">quickhacks used: ' + [...new Set(j.steps.map(s => s.skill))].map(k => '<span class="tag">' + esc(SKILLS[k] || k) + '</span>').join('') + '</div>' + (st.locked.length ? '<h3>LOCKED</h3><ul class="reqs">' + st.locked.map(r => '<li class="warn">' + (r.kind === 'read' ? '<a data-level="' + r.id + '">' + esc(r.text) + '</a>' : esc(r.text)) + '</li>').join('') + '</ul>' : (Game.body.lethal(j) ? '<div class="lethal">☠ you go in on ' + Game.state.body.food + ' food and ' + Game.state.body.chrome + ' chrome. this dive costs ' + Game.body.cost(j).food + ' and ' + Game.body.cost(j).chrome + '. you will not come back. eat first, or get the chrome seen to.</div><p><button class="btn ghost" data-start="' + j.id + '" style="border-color:var(--red);color:var(--red)">JACK IN ANYWAY</button> <button class="btn mag" data-v="shop">MARROW\'S STALL</button></p>' : '<div class="muted" style="font-size:11px;margin-top:8px">this dive costs ' + Game.body.cost(j).food + ' food and ' + Game.body.cost(j).chrome + ' chrome. you have ' + Game.state.body.food + ' and ' + Game.state.body.chrome + '. a bad call costs a point of chrome.</div><p><button class="btn mag" data-start="' + j.id + '">JACK IN ▸</button></p>')); }

  // ---- the dive -------------------------------------------------------------------------
  function dive(job, cb){ const d = document.createElement('div'); d.className = 'dive'; const lines = ['DECK ONLINE', 'target · ' + job.title.toUpperCase(), 'mounting legacy shell … the old tongue', 'translating intent → IOS', 'ICE reading · ' + (job.cls === 'A' ? 'HEAVY' : job.cls === 'B' ? 'REAL' : 'LOW'), 'floors · ' + job.steps.length, 'DIVING'];
    d.innerHTML = '<div class="grid"></div><div class="core">' + lines.map((l, i) => '<div class="ln' + (i === lines.length - 1 ? ' big' : i === 1 ? ' mag' : i === 2 || i === 3 ? ' dim' : '') + '" style="animation-delay:' + (i * 0.22) + 's">' + esc(l) + '</div>').join('') + '</div><div class="skip">click to skip</div>'; document.body.appendChild(d);
    let done = false; const fin = () => { if (done) return; done = true; d.classList.add('out'); setTimeout(() => d.remove(), 450); cb(); }; d.onclick = fin; setTimeout(fin, 2100); }

  // ---- run ----------------------------------------------------------------------------
  function runView(){ const r = Game.run; if (!r) { view = 'jobs'; return jobs(); } if (r.result) return resultView(r); const st = Game.currentStep(); const n = NPCS[r.job.from];
    return '<div class="panel"><div class="row" style="justify-content:space-between"><h2>DIVE · ' + esc(r.job.title) + ' <span class="cls ' + r.job.cls + '" style="font-size:11px">CLASS ' + r.job.cls + '</span></h2><span class="muted" style="font-size:11px" id="runclock">00:00</span><button class="btn ghost" id="abort">JACK OUT</button></div>' +
      '<div class="run"><div><div class="netmap" id="netmap"></div><ol class="steps" style="margin-top:10px">' + r.job.steps.map((s, i) => '<li class="' + (i < r.step ? 'done' : i === r.step ? 'cur' : '') + (r.hinted[i] ? ' hinted' : '') + '">floor ' + (i + 1) + ' · ' + esc(SKILLS[s.skill] || s.skill) + (i === r.step ? ' ◂' : '') + (r.fails[i] ? ' <span class="muted">(' + r.fails[i] + ' miss' + (r.fails[i] > 1 ? 'es' : '') + ')</span>' : '') + '</li>').join('') + '</ol></div>' +
      '<div><div class="task"><div class="npcline">' + npcSlot(r.job.from, 48) + '<div><div class="who">' + esc(n.name.toUpperCase()) + ' · floor ' + (r.step + 1) + ' of ' + r.job.steps.length + '</div><div>' + rich(st.text) + '</div></div></div>' + stepInput(st, r) +
      (r.feedback ? '<div style="margin-top:8px" class="' + (r.feedback.ok ? 'good' : 'bad') + '">' + rich(r.feedback.text) + (r.feedback.leveled ? ' <span class="mag">▲ ' + esc(SKILLS[r.feedback.leveled.skill]) + ' → ' + Game.LEVEL_NAMES[r.feedback.leveled.level] + '</span>' : '') + '</div>' : '') +
      (r.lastWhy ? '<details class="why"><summary>why that held</summary>' + rich(r.lastWhy) + '</details>' : '') + (r.hintShown ? '<div class="hintbox">DISPATCH: ' + esc(r.hintShown) + '</div>' : '') + (r.walk ? '<div class="why"><b>' + esc(n.name.toUpperCase()) + ' TAKES YOUR HANDS</b><br><span class="ans">' + esc(r.walk.answer).replace(/\n/g, '<br>') + '</span><br><br>' + rich(r.walk.why || 'Nothing written for this floor yet.') + '</div>' : '') +
      '<div class="row" style="margin-top:10px"><button class="btn grn" id="commit">EXECUTE ▸</button>' + (st.hint ? '<button class="btn ghost" id="hint">' + (r.hinted[r.step] ? 'DISPATCH PINGED' : 'PING DISPATCH') + '</button>' : '') + '<button class="btn ghost" id="walk" title="they show you. it counts as help: this quickhack does not sharpen on this floor">' + (r.walk ? 'SHOWN' : 'SHOW ME') + '</button><span class="muted" style="font-size:10px">help costs the sharpening on this floor, nothing else</span></div></div>' + (r.job.devices.length ? consoleView(r) : '') + '</div></div></div>'; }
  function stepInput(st, r){
    if (st.type === 'choice') return '<div class="opts" style="margin-top:8px">' + st.opts.map((o, i) => '<button data-choice="' + i + '" class="' + (r.choice === i ? 'sel' : '') + '">' + A(i) + '. ' + esc(o) + '</button>').join('') + '</div>';
    if (st.type === 'multi') return '<div class="muted" style="margin-top:8px;font-size:12px">pick everything that applies</div><div class="opts">' + st.opts.map((o, i) => '<button data-multi="' + i + '" class="' + (r.multi.has(i) ? 'sel' : '') + '">' + (r.multi.has(i) ? '☑ ' : '☐ ') + A(i) + '. ' + esc(o) + '</button>').join('') + '</div>';
    if (st.type === 'calc') return '<div class="calc" style="margin-top:8px">' + st.fields.map(f => '<label>' + esc(f.label) + '<input data-calc="' + f.key + '" value="' + esc(r.calc[f.key] || '') + '" class="' + (r.feedback && r.feedback.bad ? (r.feedback.bad.includes(f.key) ? 'no' : 'ok') : '') + '" autocomplete="off"></label>').join('') + '</div>';
    if (st.type === 'order') { if (!r.order) { r.order = st.items.map((_, i) => i); for (let i = r.order.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1)); [r.order[i], r.order[j]] = [r.order[j], r.order[i]]; } if (r.order.every((v, i) => v === i)) r.order.reverse(); } return '<div class="muted" style="margin-top:8px;font-size:12px">put these in order, top to bottom</div><ol class="orderlist">' + r.order.map((idx, pos) => '<li><span class="n">' + (pos + 1) + '</span><span class="t">' + esc(st.items[idx]) + '</span><button data-up="' + pos + '"' + (pos === 0 ? ' disabled' : '') + '>▲</button><button data-down="' + pos + '"' + (pos === r.order.length - 1 ? ' disabled' : '') + '>▼</button></li>').join('') + '</ol>'; }
    if (st.type === 'form') return '<div class="formgrid" style="margin-top:8px">' + st.fields.map(f => '<label>' + esc(f.label) + '<select data-form="' + f.key + '" class="' + (r.feedback && r.feedback.bad ? (r.feedback.bad.includes(f.key) ? 'no' : 'ok') : '') + '"><option value="">— choose —</option>' + f.options.map(o => '<option' + (String(r.form[f.key]) === String(o) ? ' selected' : '') + '>' + esc(o) + '</option>').join('') + '</select></label>').join('') + '</div>';
    if (st.type === 'text') return '<div style="margin-top:8px"><textarea class="txt" data-text="1" placeholder="' + esc(st.placeholder || 'say it') + '">' + esc(r.text || '') + '</textarea></div>';
    if (st.type === 'find') return '<div class="muted" style="margin-top:8px;font-size:12px">marked: <b class="warn">' + esc(r.selected || 'nothing yet') + '</b> — click a node on the map, then EXECUTE.</div>';
    return '<div class="muted" style="margin-top:8px;font-size:12px">speak to the box in the shell below, then EXECUTE. the old tongue takes short forms: conf t, int g0/1, sh span, do sh run.</div>'; }
  function consoleView(r){ const d = r.devices[r.active]; return '<div class="console"><div class="devs">' + r.job.devices.map(n => '<button data-dev="' + n + '" class="' + (n === r.active ? 'on' : '') + '">' + n + '</button>').join('') + '<span class="muted" style="padding:5px 10px;font-size:10px">SHELL · ' + esc(d.prompt()) + '</span></div><div class="out" id="conout">' + d.out.map(o => '<div class="' + o.t + '">' + esc(o.s) + '</div>').join('') + '</div><div class="in-row"><span id="prompt">' + esc(d.prompt()) + '</span><input id="conin" autocomplete="off" spellcheck="false" placeholder="' + (d.kind === 'host' ? 'ping / ipconfig / arp -a / tracert · Enter' : 'speak to the box · ↑ history · Enter') + '"></div></div>'; }
  function autoMap(job){ const D = job.net.devices; const rows = { router: [], switch: [], l3switch: [], host: [], server: [], cloud: [], rogue: [], ap: [], wlc: [] }; Object.keys(D).forEach(n => (rows[D[n].kind] || rows.host).push(n)); const nodes = []; const place = (list, y, type) => list.forEach((n, i) => nodes.push({ id: n, label: n, type: type || D[n].kind, x: Math.round(520 * (i + 1) / (list.length + 1)), y }));
    place(rows.cloud, 30, 'cloud'); place(rows.router.concat(rows.l3switch), 100, 'router'); place(rows.switch, 190, 'switch'); place(rows.host.concat(rows.server, rows.ap, rows.wlc), 280, 'pc'); place(rows.rogue, 330, 'rogue'); return { w: 520, h: 360, nodes, links: job.net.links.map(l => ({ a: l.a, b: l.b, ap: l.ap, bp: l.bp })), alert: job.net.alert || [] }; }
  function drawMap(){ const r = Game.run; const box = $('#netmap'); if (!r || !box) return; const m = r.job.map || (r.job.net ? autoMap(r.job) : { w: 520, h: 200, nodes: [], links: [] }); const W = m.w || 520, H = m.h || 300;
    let comp = null; try { comp = r.ctx.compute(r.vlanView || 1); } catch (e) { console.error(e); } let S = null; try { S = r.ctx.state && r.ctx.state(); } catch (e) { console.error(e); }
    const nodeCls = {}; const portRole = {}; const removed = n => (r.topo && r.topo.switches[n] && r.topo.switches[n].removed) || (r.netDef && r.netDef.devices[n] && r.netDef.devices[n].removed);
    if (comp) { for (const n in comp.switches) { const s = comp.switches[n]; if (s.isRoot && !removed(n)) nodeCls[n] = (nodeCls[n] || '') + ' root'; for (const pn in s.ports) portRole[n + '|' + pn] = s.ports[pn]; } }
    if (S) { for (const n in S.hosts) { const h = S.hosts[n]; if (!h.up || (!h.ip && h.dhcp)) nodeCls[n] = (nodeCls[n] || '') + ' alert'; if (h.rogue) nodeCls[n] = (nodeCls[n] || '') + ' alert'; } for (const n in S.ifaces) for (const p in S.ifaces[n]) if (S.ifaces[n][p].errdisabled) portRole[n + '|' + p] = Object.assign(portRole[n + '|' + p] || {}, { errdisabled: true }); }
    (m.alert || []).forEach(a => { if (!removed(a)) nodeCls[a] = (nodeCls[a] || '') + ' alert'; });
    const pos = {}; m.nodes.forEach(n => pos[n.id] = n); let svg = '<svg viewBox="0 0 ' + W + ' ' + H + '" xmlns="http://www.w3.org/2000/svg">';
    m.links.forEach(l => { const a = pos[l.a], b = pos[l.b]; if (!a || !b) return; if (removed(l.a) || removed(l.b)) return; let cls = 'link'; const pa = l.ap ? portRole[l.a + '|' + l.ap] : null, pb = l.bp ? portRole[l.b + '|' + l.bp] : null;
      const down = S && ((S.ifaces[l.a] && S.ifaces[l.a][l.ap] && !S.ifaces[l.a][l.ap].up) || (S.ifaces[l.b] && S.ifaces[l.b][l.bp] && !S.ifaces[l.b][l.bp].up));
      if (pa && pa.errdisabled || pb && pb.errdisabled) cls += ' err'; else if (down) cls += ' blocked'; else if (pa && pa.state === 'BLK' || pb && pb.state === 'BLK') cls += ' blocked'; else if ((m.alert || []).includes(l.b) || (m.alert || []).includes(l.a)) cls += ' hot';
      svg += '<line class="' + cls + '" x1="' + a.x + '" y1="' + a.y + '" x2="' + b.x + '" y2="' + b.y + '"/>';
      const tagAt = (from, to, txt, cls2) => { const dx = to.x - from.x, dy = to.y - from.y, L = Math.hypot(dx, dy) || 1; const nx = -dy / L, ny = dx / L; const x = from.x + dx / L * 46 + nx * 9, y = from.y + dy / L * 46 + ny * 9; svg += '<text class="ptag ' + cls2 + '" x="' + x + '" y="' + (y + 3) + '" text-anchor="middle">' + esc(txt) + '</text>'; };
      const lab = (p, name) => Stp.shortName(name) + ' ' + (p.errdisabled ? 'ERR' : p.role === 'Root' ? 'R' : p.role === 'Altn' ? 'A' : p.role === 'Desg' ? 'D' : ''); if (pa && (pa.role || pa.errdisabled)) tagAt(a, b, lab(pa, l.ap), pa.state === 'BLK' ? 'blk' : pa.role === 'Root' ? 'root' : ''); else if (l.ap) tagAt(a, b, Stp.shortName(l.ap), ''); if (pb && (pb.role || pb.errdisabled)) tagAt(b, a, lab(pb, l.bp), pb.state === 'BLK' ? 'blk' : pb.role === 'Root' ? 'root' : ''); else if (l.bp) tagAt(b, a, Stp.shortName(l.bp), '');
      if (l.tag) svg += '<text class="ptag" x="' + ((a.x + b.x) / 2) + '" y="' + ((a.y + b.y) / 2 - 6) + '" text-anchor="middle">' + esc(l.tag) + '</text>'; });
    m.nodes.forEach(n => { if (removed(n.id)) return; const c = 'node ' + (n.type === 'rogue' ? 'rogue ' : '') + (nodeCls[n.id] || '') + (r.selected === n.id ? ' sel' : ''); const s = n.small ? 14 : 22; svg += '<g class="' + c + '" data-node="' + n.id + '" transform="translate(' + n.x + ',' + n.y + ')">';
      if (n.type === 'switch' || n.type === 'rogue') svg += '<rect class="body" x="-' + (s + 6) + '" y="-' + (s / 2) + '" width="' + (2 * s + 12) + '" height="' + s + '" rx="3"/><path d="M-12 -3 h8 M-8 -6 l4 3 -4 3 M4 3 h8 M8 0 l-4 3 4 3" stroke="currentColor" fill="none" stroke-width="1.2" style="color:var(--cyan2)"/>';
      else if (n.type === 'router') svg += '<circle class="body" r="' + s + '"/><path d="M-10 0 h20 M4 -6 l6 6 -6 6 M-4 -6 l-6 6 6 6" stroke="var(--cyan2)" fill="none" stroke-width="1.5"/>';
      else if (n.type === 'pc' || n.type === 'host') svg += '<rect class="body" x="-' + s + '" y="-' + (s * .7) + '" width="' + (2 * s) + '" height="' + (s * 1.2) + '" rx="2"/><rect x="-' + (s * .4) + '" y="' + (s * .5) + '" width="' + (s * .8) + '" height="3" fill="var(--line)"/>';
      else if (n.type === 'server') svg += '<rect class="body" x="-' + s + '" y="-' + (s * 1.1) + '" width="' + (2 * s) + '" height="' + (s * 2) + '" rx="2"/>'; else svg += '<ellipse class="body" rx="' + (s + 8) + '" ry="' + (s * .7) + '"/>';
      const sub = S && S.hosts[n.id] && S.hosts[n.id].ip ? S.hosts[n.id].ip : ''; svg += '<text y="' + (n.type === 'pc' || n.type === 'host' ? s + 12 : s + 14) + '" text-anchor="middle">' + esc(n.label) + '</text>' + (sub ? '<text class="ptag" y="' + (s + 24) + '" text-anchor="middle">' + esc(sub) + '</text>' : '') + '</g>'; });
    svg += '</svg>'; box.innerHTML = svg + '<div class="legend">THE BUILDING\'S NET · click a node to mark it' + (comp ? ' · <b>R</b> root port · <b>D</b> designated · <b>A</b> alternate (asleep) · <b>ERR</b> err-disabled · gold = root bridge' : '') + (S ? ' · dashed = down or asleep · red = ICE / needs you' : '') + '</div>'; }
  function resultView(r){ const res = r.result; const c = Game.classFor(Game.state.rep); return '<div class="panel result"><h2>' + (r.job.rite ? 'RITE OF PASSAGE · COMPLETE' : 'DIVE COMPLETE') + '</h2><div class="big">+' + res.rep + ' REP</div><div class="creds" style="font-size:18px">+' + res.creds + ' <small>creds</small></div><div class="dim">' + (res.repeat ? 'again · the street pays 40% for a re-run, your hands learn the whole thing' : 'first clear') + ' · ' + Math.round(res.ms / 1000) + 's' + (res.fails ? ' · ' + res.fails + ' miss' + (res.fails > 1 ? 'es' : '') : ' · no misses') + (res.hintedCount ? ' · help on ' + res.hintedCount + ' floor' + (res.hintedCount > 1 ? 's' : '') : ' · no help. clean.') + '</div>' +
      (res.promoted ? '<div class="mag" style="font-family:var(--disp);font-size:20px;margin-top:10px">▲ THE BOARD CALLS YOU CLASS ' + res.promoted + '</div>' : '') + (res.recruit ? '<div class="good" style="margin-top:8px">' + esc(res.recruit.name) + ' (' + esc(res.recruit.handle) + ') watched you work and asked Dispatch for your handle. They are your crew now.<br><span class="dim">' + esc(Protege.fill(((PROTEGE_LINES.dispatch || {}).send || [])[0] || 'Dispatch: "The street has no junior tier."', res.recruit)) + '</span></div>' : '') +
      (res.leveled.length ? '<div class="lvls">' + res.leveled.map(l => '<div><span class="tag new">SHARPER</span> ' + esc(SKILLS[l.skill]) + ' → <b>' + Game.LEVEL_NAMES[l.level] + '</b></div>').join('') + '</div>' : '<div class="muted" style="margin-top:8px">nothing sharpened this dive. clean uses add up: 1 → SYNCED, 3 → WIRED, 6 → BURNED-IN</div>') +
      '<div class="brief" style="text-align:left;margin-top:16px">' + rich(r.job.outro) + '</div><div class="row" style="justify-content:center"><button class="btn mag" data-v="jobs">BACK TO THE BOARD</button><button class="btn" data-v="stats">YOUR RECORD</button></div><div class="muted" style="margin-top:8px">now Class ' + c.id + ' · ' + Game.state.rep + ' rep · ' + Game.state.creds + ' creds</div></div>'; }

  // ---- flatline: game over, choom ------------------------------------------------------------
  function deadView(){ const s = Game.state, d = s.dead || {}, cp = s.checkpoint; const ago = cp ? Math.max(1, Math.round((Date.now() - cp.at) / 60000)) : 0;
    return '<div class="flatline"><div class="grid"></div><div class="core"><div class="big">FLATLINED.</div><div class="sub">GAME OVER, CHOOM.</div><div class="why">' + esc(d.why || '') + '</div><div class="meters">food ' + (d.food == null ? '—' : d.food) + ' · chrome ' + (d.chrome == null ? '—' : d.chrome) + '</div>' +
      '<div class="last">' + (cp ? 'last sync · ' + esc(cp.label) + ' · ' + ago + ' min ago' : 'no sync on record. the street starts you over under this handle.') + '</div>' +
      '<div class="row" style="justify-content:center;margin-top:18px"><button class="btn mag" id="reload">' + (cp ? 'BACK TO THE LAST SYNC' : 'START OVER') + '</button><button class="btn ghost" id="exitdoor">OUT TO THE DOOR</button></div>' +
      '<div class="muted" style="margin-top:14px">flatlines on this handle: ' + (s.meta.deaths || 0) + '. the street keeps count.</div></div></div>'; }

  // ---- deck, stall, codex, record, crew, journal --------------------------------------------
  function deck(){ const s = Game.state; return '<div class="panel"><h2>DECK · quickhacks you run without thinking</h2><div class="muted">a quickhack slots when someone teaches it · it sharpens only when you use it on a dive with no help · 1 clean use → SYNCED · 3 → WIRED · 6 → BURNED-IN</div><div class="deck" style="margin-top:12px">' +
      Object.keys(SKILLS).map(k => { const sk = s.skills[k]; const lv = sk ? sk.level : 0; const next = Game.LEVEL_AT[lv + 1]; const pct = sk ? (next ? Math.round(((sk.clean - Game.LEVEL_AT[lv]) / (next - Game.LEVEL_AT[lv])) * 100) : 100) : 0; return '<div class="skill l' + lv + '"><div class="n">' + esc(SKILLS[k]) + '</div><div class="lv">' + (sk && sk.slotted ? Game.LEVEL_NAMES[lv] : 'NOT SLOTTED') + (sk ? ' · ' + sk.clean + ' clean / ' + sk.uses + ' uses' : '') + '</div><div class="bar"><i style="width:' + pct + '%"></i></div></div>'; }).join('') + '</div>' +
      (s.perks.skins.length ? '<h3>DECK SKIN</h3><div class="row">' + ['', ...s.perks.skins.map(id => SHOP.find(x => x.id === id).effect.theme)].map(t => '<button class="btn ghost" data-theme="' + t + '"' + ((s.perks.theme || '') === t ? ' style="border-color:var(--cyan);color:var(--cyan)"' : '') + '>' + (t || 'default') + '</button>').join('') + '</div>' : '') +
      '<h3>YOUR RECORD</h3><div class="muted">the deck syncs your record on its own after every talk and every gig. there is no chip and no manual save. if you flatline, you go back to the last sync.' + (s.meta.lastSync ? ' last sync · ' + Math.max(1, Math.round((Date.now() - s.meta.lastSync) / 60000)) + ' min ago.' : '') + '</div><div class="row" style="margin-top:8px"><button class="btn ghost" id="wipe" style="border-color:var(--red);color:var(--red)">WIPE THIS HANDLE</button></div></div>'; }
  function shopView(){ const s = Game.state; const items = Game.shop.items(); return '<div class="panel"><div class="row" style="align-items:flex-start"><div class="npcbox" style="width:72px;flex:none">' + npcSlot('marrow', 72) + '</div><div><h2>MARROW\'S STALL · under the overpass</h2><div class="dim">' + esc(NPCS.marrow.role) + '</div><div class="creds" style="margin-top:6px">' + s.creds + ' <small>creds on you</small></div></div></div>' + (cur.shopMsg ? '<div class="letter" style="margin-top:10px"><span class="k">MARROW</span><br>' + esc(cur.shopMsg) + '</div>' : '') +
      [['food', 'FOOD', 'a dive costs food. eat here, or carry it in. you are at ' + s.body.food + '/100.'], ['service', 'MAINTENANCE', 'two doors down. one price, full service on the chrome. yours reads ' + s.body.chrome + '/100.'], ['gift', 'FOR THE CREW', 'given from the CREW screen. they feel it.'], ['favor', 'FROM DISPATCH', 'one on the books at a time. spend it on someone in real trouble.'], ['bd', 'BRAINDANCES', 'recordings from the old net. they play in the CODEX, and your crew will ask about them.'], ['skin', 'DECK SKINS', 'how your deck looks. pure vanity. switch skins from the DECK screen.']].map(([kind, title, sub]) => { const list = items.filter(it => it.kind === kind); if (!list.length) return '';
        return '<div class="stallsec ' + kind + '"><h3>' + title + ' <span class="muted">· ' + esc(sub) + '</span></h3><div class="stall">' + list.map(it => { const price = Game.shop.price(it); const owned = Game.shop.owned(it.id); const cant = s.creds < price; const maxed = (it.kind === 'bd' || it.kind === 'skin') && owned || (it.max && owned >= it.max);
          return '<div class="item ' + kind + (owned ? ' owned' : '') + (cant && !maxed ? ' cant' : '') + '"><div class="k"><span class="kb">' + esc(kind === 'food' ? 'FOOD' : kind === 'service' ? 'SERVICE' : kind === 'gift' ? 'GIFT' : kind === 'favor' ? 'FAVOR' : kind === 'bd' ? 'BD' : 'SKIN') + '</span> ' + esc(kind === 'food' ? '+' + it.effect.food + ' food' + (it.effect.danger ? ' · or give to a runner' : '') : kind === 'service' ? 'chrome back to 100' : kind === 'gift' ? 'give to a runner' : kind === 'favor' ? 'pull a runner out' : kind === 'bd' ? (it.year || '') + ' · plays in the codex' : 'changes the HUD') + (owned ? ' · you have ' + owned : '') + '</div><div class="n">' + esc(it.name) + '</div><div class="b">' + esc(it.blurb) + '</div><div class="row" style="justify-content:space-between"><span class="p">' + price + ' ¢</span>' + (maxed ? '<span class="tag on">yours</span>' : kind === 'service' && s.body.chrome >= 100 ? '<span class="tag on">nothing to fix</span>' : (kind === 'food' && owned ? '<button class="btn" data-eat="' + it.id + '">EAT</button> ' : '') + '<button class="btn ' + (cant ? 'ghost' : 'mag') + '" data-buy="' + it.id + '"' + (cant && kind !== 'food' ? ' disabled' : '') + '>BUY</button>') + '</div></div>'; }).join('') + '</div></div>'; }).join('') + '<div class="muted" style="margin-top:12px">prices climb with your class. Marrow says it is respect.</div></div>'; }
  function keyView(){ const s = Game.state; const jobsHtml = JOBS.map(j => '<div class="keyjob"><h3><span class="cls ' + j.cls + '" style="font-size:10px">' + j.cls + '</span> ' + esc(j.title) + ' <span class="muted">· ' + esc(NPCS[j.from].name) + '</span></h3>' + j.steps.map((st, i) => '<div class="keystep"><div class="q"><span class="muted">floor ' + (i + 1) + ' · ' + esc(SKILLS[st.skill] || st.skill) + '</span><br>' + rich(st.text) + '</div><div class="a"><b>The move:</b> ' + esc(Game.answerOf(st)).replace(/\n/g, '<br>') + '</div>' + (st.why ? '<div class="w">' + rich(st.why) + '</div>' : '') + '</div>').join('') + '</div>').join('');
    const lvlHtml = STAGES.map(stg => stg.levels.map(l => { const q = (l.beats.find(b => b.k === 'SYNC') || {}).q; if (!q) return ''; return '<div class="keystep"><div class="q"><span class="muted">' + esc(stg.title) + ' · ' + esc(l.title) + ' · ' + esc(NPCS[l.npc].name) + '</span><br>' + rich(q.prompt) + '</div><div class="a"><b>The answer:</b> ' + A(q.a) + '. ' + esc(q.opts[q.a]) + '</div>' + (q.why ? '<div class="w">' + rich(q.why) + '</div>' : '') + '</div>'; }).join('')).join('');
    const bds = []; STAGES.forEach(stg => stg.levels.forEach(l => l.beats.forEach(b => { if (b.k === 'LORE' && b.title) bds.push({ b, l, owned: !!s.read[l.id] }); }))); SHOP.filter(it => it.kind === 'bd').forEach(it => bds.push({ b: { title: it.title, year: it.year, text: it.text, vibe: it.blurb }, l: null, owned: s.bd.includes(it.id), bought: true }));
    return '<div class="panel key"><h2>CODEX · your own notes, kept in the deck</h2><div class="muted">Read it whenever. It changes nothing in your deck. On a dive, SHOW ME opens the same page for the floor you are on, and that counts as help.</div>' +
      '<h3 style="margin-top:16px;color:var(--yel)">BRAINDANCES</h3><div class="muted">the year is what sticks. your crew will ask.</div>' + bds.map(x => x.owned ? '<div style="margin-top:10px">' + bdCard(x.b) + '</div>' : '<div class="keystep muted">' + (x.bought ? 'BD · ' + esc(x.b.title) + ' · at Marrow\'s stall' : 'a recording you have not been handed yet') + '</div>').join('') +
      '<h3 style="margin-top:16px;color:var(--cyan)">DIVES</h3>' + jobsHtml + '<h3 style="margin-top:16px;color:var(--cyan)">WHAT PEOPLE ASK YOU</h3>' + lvlHtml + '</div>'; }
  function statsView(){ const S = Game.stats(); const x = S.extra; const tile = (k, v, cls) => '<div class="tile ' + (cls || '') + '"><div class="v">' + (v == null ? '—' : v) + '</div><div class="k">' + k + '</div></div>'; const acc = a => a == null ? '' : a >= 80 ? 'good' : a >= 60 ? 'warn' : 'bad';
    const spark = (() => { const h = S.repHistory; if (h.length < 2) return '<div class="muted">rep over time shows after a few dives</div>'; const max = Math.max(...h.map(p => p.rep), 1); const pts = h.map((p, i) => (i / (h.length - 1) * 100).toFixed(1) + ',' + (60 - p.rep / max * 56).toFixed(1)).join(' '); return '<svg class="spark" viewBox="0 0 100 60" preserveAspectRatio="none"><polyline points="' + pts + '" fill="none" stroke="var(--cyan)" stroke-width="1.5"/></svg>'; })();
    const done = x.done === x.jobs && x.jobs > 0;
    return '<div class="panel stats"><h2>RECORD · ' + (done ? 'the district is yours · final tally' : 'how the street sees you') + '</h2><div class="muted">every move is timed. misses, pings and show-mes are counted. the crew\'s calls count on their own.</div>' +
      '<h3>THE STREET</h3><div class="tiles">' + tile('rep', Game.state.rep) + tile('class', Game.classFor(Game.state.rep).id) + tile('creds', Game.state.creds) + tile('people met', x.read + '/' + x.levels) + tile('dives cleared', x.done + '/' + x.jobs) + tile('time on the net', S.playTime) + tile('nights', S.sessions) + tile('flatlines', Game.state.meta.deaths || 0, Game.state.meta.deaths ? 'bad' : '') + tile('syncs', Game.state.meta.syncs || 0) + '</div>' +
      '<h3>THE DIVES</h3><div class="tiles">' + tile('moves made', S.steps.attempts) + tile('landed', S.steps.accuracy == null ? null : S.steps.accuracy + '%', acc(S.steps.accuracy)) + tile('first try', S.steps.firstTry == null ? null : S.steps.firstTry + '%', acc(S.steps.firstTry)) + tile('per floor', S.steps.avg) + tile('help taken', S.steps.hints + S.steps.walks, S.steps.hintRate > 30 ? 'warn' : '') + tile('best streak', S.streak.best, 'good') + '</div>' +
      '<h3>THE CREW</h3><div class="tiles">' + tile('calls taken', S.dms.asked) + tile('calls landed', S.dms.accuracy == null ? null : S.dms.accuracy + '%', acc(S.dms.accuracy)) + tile('too late', S.dms.timeouts, S.dms.timeouts ? 'bad' : '') + tile('pickup time', S.dms.avg) + tile('running', Protege.active(x.roster).length, 'good') + tile('lost', Protege.lost(x.roster).length, Protege.lost(x.roster).length ? 'bad' : '') + tile('things they might ask', x.unlocked) + tile('reflexes locked in', x.retention ? x.retention.strong : 0) + '</div>' +
      '<h3>REP OVER TIME</h3>' + spark + '<h3>QUICKHACKS · weakest first</h3><div class="bars">' + (S.skills.length ? S.skills.map(s => '<div class="b ' + (s.accuracy != null && s.accuracy < 60 ? 'low' : s.accuracy != null && s.accuracy < 80 ? 'mid' : '') + '"><span>' + esc(s.name) + '</span><div class="bar"><i style="width:' + (s.accuracy || 0) + '%"></i></div><span class="muted">' + (s.accuracy == null ? '—' : s.accuracy + '%') + ' · ' + s.attempts + ' tries' + (s.hints ? ' · ' + s.hints + ' help' : '') + '</span></div>').join('') : '<div class="muted">no moves yet</div>') + '</div>' +
      (S.weak.length ? '<h3>SHAKY</h3><div class="dim">' + S.weak.map(s => esc(s.name) + ' (' + s.accuracy + '%)').join(' · ') + '</div>' : '') +
      '<h3>BY KIND OF MOVE</h3><table><tr><th>kind</th><th>moves</th><th>landed</th><th>time</th></tr>' + S.types.map(t => '<tr><td>' + t.type + '</td><td>' + t.attempts + '</td><td>' + (t.accuracy == null ? '—' : t.accuracy + '%') + '</td><td>' + S.fmt(t.avgMs) + '</td></tr>').join('') + '</table>' +
      '<h3>DIVES</h3><table><tr><th>dive</th><th>runs</th><th>best time</th><th>misses</th><th>help</th></tr>' + JOBS.map(j => { const b = S.jobs.byJob[j.id]; return b ? '<tr><td>' + esc(j.title) + '</td><td>' + b.finished + '/' + b.runs + '</td><td>' + S.fmt(b.bestMs) + '</td><td>' + b.fails + '</td><td>' + b.hints + '</td></tr>' : ''; }).join('') + '</table></div>'; }
  function crewView(){ const s = Game.state; const dm = Game.dm.pending(); const R = s.roster; const inv = s.inventory || {}; const gifts = SHOP.filter(it => (it.kind === 'gift' || (it.kind === 'food' && it.effect && it.effect.danger)) && inv[it.id] > 0);
    return '<div class="panel"><h2>CREW · the kids who look up to you</h2><div class="muted">The street has no junior tier. You send them on the risky gigs because that is how anyone learns here, and they call you when it gets loud. Answer right and in time and they get through, and they open up. Wrong or late and it goes badly for them, and for your rep. Three strikes and the client does not let them leave. Then their orphan comes to find you.</div>' +
      (dm ? '<div class="panel" style="border-color:var(--mag);margin-top:12px"><b class="mag">A call is waiting</b> from ' + esc((R.list.find(p => p.id === dm.protege) || {}).name) + '. <button class="btn mag" id="opendm">PICK UP</button> <span class="muted">' + dm.seconds + ' seconds once you read it</span></div>' : (Protege.active(R).length ? '<div class="muted" style="margin-top:10px">quiet right now. ' + (Game.allCards().filter(Game.cardUnlocked).length ? 'someone will call when a gig gets loud.' : 'calls start once you have met people in the Grid.') + (P().dev ? ' <button class="btn ghost" id="forcedm">force a call (dev)</button>' : '') + '</div>' : '<div class="muted" style="margin-top:10px">nobody yet. finish your first dive and someone will ask Dispatch for your handle.</div>')) +
      (inv.favor ? '<div class="letter" style="margin-top:10px"><span class="k">DISPATCH</span><br>One favor on the books. Use it on someone in real trouble, from their card below.</div>' : '') +
      '<h3>ROSTER</h3>' + (R.list.length ? '<div class="crewgrid">' + R.list.map(p => { const b = Protege.bond(p); const arch = Protege.archOf(p); return '<div class="pcard ' + (p.status === 'flatlined' ? 'flat' : '') + '">' + pSlot(p, 56) + '<div style="flex:1"><div class="n">' + esc(p.name) + ' <span class="muted">' + esc(p.handle) + '</span></div><div class="h">' + esc(arch.name) + ' · ' + esc(arch.tagline) + '</div><div class="h">' + (p.lineage ? 'orphan of ' + esc((R.list.find(x => x.id === p.lineage) || {}).name || '?') + (p.keepsake ? ' · carries ' + esc(p.keepsake) : '') + ' · ' : '') + esc(p.recruitReason || '') + '</div><div class="d">' + (p.status === 'flatlined' ? '<span class="bad">flatlined</span>' : '<span class="dots">' + [0, 1, 2].map(i => '<i class="' + (i < p.danger ? 'on' : '') + '"></i>').join('') + '</span> ' + (p.danger === 0 ? 'fine' : p.danger === 1 ? 'under pressure' : 'in real trouble') + ' · bond: <b>' + esc(b.name) + '</b>' + (b.next ? ' (' + (b.next - p.saved) + ' more)' : '')) + ' · saved ' + p.saved + ' · failed ' + p.failed + (p.insurance ? ' · burner ×' + p.insurance : '') + (p.timerBonus ? ' · +' + p.timerBonus + 's' : '') + '</div>' + (p.status === 'active' && (gifts.length || (inv.favor && p.danger > 0)) ? '<div class="gift">' + gifts.map(g => '<button data-give="' + g.id + '" data-to="' + p.id + '">give ' + esc(g.name.toLowerCase()) + ' (' + inv[g.id] + ')</button>').join('') + (inv.favor && p.danger > 0 ? '<button data-favor="' + p.id + '" style="border-color:var(--mag);color:var(--mag)">CALL IN THE FAVOR</button>' : '') + '</div>' : '') + '</div></div>'; }).join('') + '</div>' : '') +
      '<h3>MESSAGES</h3><div class="dmlog">' + (s.dmLog.length ? s.dmLog.map(m => m.letter ? '<div class="letter"><span class="k">' + esc(m.name) + (m.trust ? ' · opening up' : '') + '</span><br>' + esc(m.text) + '</div>' : '<div class="item"><div class="row1"><span>' + esc(m.name) + ' · ' + new Date(m.t).toLocaleString() + '</span><span class="' + (m.ok || m.forgiven ? 'good' : 'bad') + '">' + (m.forgiven ? 'burner took it' : m.ok ? 'got through' : m.timedOut ? 'too late' : 'wrong') + (m.repDelta ? ' · ' + (m.repDelta >= 0 ? '+' : '') + m.repDelta + ' rep' : '') + (m.flatlined ? ' · FLATLINED' : '') + '</span></div><div><b>' + esc(m.q) + '</b>' + (m.opts ? '<br><span class="muted">it was: ' + esc(m.opts[m.correct]) + (m.chosen != null && m.chosen !== m.correct ? ' · you said: ' + esc(m.opts[m.chosen]) : '') + '</span>' : '') + '</div><div class="t">' + esc(m.text) + '</div>' + (m.why && !m.ok ? '<div class="why">' + rich(m.why) + '</div>' : '') + '</div>').join('') : '<div class="muted">nothing yet</div>') + '</div></div>'; }
  function logView(){ return '<div class="panel"><h2>JOURNAL</h2><div class="log">' + (Game.state.log.length ? Game.state.log.map(l => '<div><time>' + new Date(l.t).toLocaleString() + '</time>' + esc(l.s) + '</div>').join('') : '<div class="muted">nothing yet.</div>') + '</div></div>'; }

  // ---- the call (DM overlay) ----------------------------------------------------------------
  function dmOverlay(){ const dm = Game.dm.pending(); const res = cur.dmResult; if (!dm && !res) return ''; if (dm && !res && !dm.openedAt && cur.dmSnoozed === dm.id) return '';
    if (res) { const p = res.protege; const arch = Protege.archOf(p); return '<div class="dm-back"><div class="dm"><div class="from">' + pSlot(p, 48) + '<div><div class="n">' + esc(p.name) + '</div><div class="s">' + esc(p.handle) + ' · ' + esc(arch.name) + (res.out.bond ? ' · bond: ' + esc(res.out.bond.name) : '') + '</div></div></div><div class="result ' + (res.out.flatlined ? 'flat' : res.ok || res.out.forgiven ? 'good' : 'bad') + '">' + esc(res.out.text) + (res.out.orphanIntro ? '\n\n' + esc(res.out.orphanIntro) : '') + '</div>' + (res.out.trust ? '<div class="letter"><span class="k">' + esc(p.name) + ' · opening up</span><br>' + esc(res.out.trust) + '</div>' : '') + (res.out.milestone ? '<div class="letter"><span class="k">' + esc(p.name) + ' · a letter</span><br>' + esc(res.out.milestone) + '</div>' : '') + (!res.ok && !res.out.forgiven ? '<div class="why"><b>It was: ' + esc(res.answerText) + '</b>' + (res.why ? '<br>' + rich(res.why) : '') + '</div>' : '') + '<div class="muted" style="margin-top:8px">' + (res.out.repDelta ? (res.out.repDelta >= 0 ? '+' : '') + res.out.repDelta + ' rep' : 'no rep moved') + (res.out.credsDelta ? ' · +' + res.out.credsDelta + ' creds' : '') + (res.promoted ? ' · the Board calls you Class ' + res.promoted : '') + '</div><div class="row" style="margin-top:10px"><button class="btn" id="dmclose">CLOSE</button></div></div></div>'; }
    const p = Game.state.roster.list.find(x => x.id === dm.protege); const arch = Protege.archOf(p); const b = Protege.bond(p); const opened = !!dm.openedAt; const rem = Game.dm.remaining(); const pct = opened ? Math.round(100 * rem / (dm.seconds * 1000)) : 100;
    return '<div class="dm-back"><div class="dm"><div class="from">' + pSlot(p, 48) + '<div><div class="n">' + esc(p.name) + '</div><div class="s">' + esc(p.handle) + ' · ' + esc(arch.name) + ' · bond: ' + esc(b.name) + ' · <span class="danger d' + p.danger + '">' + (p.danger === 0 ? 'fine' : p.danger === 1 ? 'under pressure' : 'in real trouble') + '</span></div></div></div>' +
      '<div class="msg">' + esc(dm.open) + '</div>' + (opened ? '<div class="q">' + esc(dm.q) + '</div><div class="opts">' + (dm.opts || []).map((o, i) => '<button data-dmans="' + i + '">' + A(i) + '. ' + esc(o) + '</button>').join('') + '</div><div class="timer' + (pct < 30 ? ' hot' : '') + '"><i id="dmbar" style="width:' + pct + '%"></i></div><div class="secs" id="dmsecs">' + Math.ceil(rem / 1000) + 's</div>' : '<div class="muted">' + dm.seconds + ' seconds once you read it. no pausing. that is the street.</div><div class="row" style="margin-top:10px"><button class="btn mag" id="dmopen">READ IT</button><button class="btn ghost" id="dmlater">LATER</button></div>') + '</div></div>'; }
  function dmTick(){ const dm = Game.dm.pending(); if (!dm || !dm.openedAt) return; const rem = Game.dm.remaining(); const bar = $('#dmbar'), secs = $('#dmsecs'); if (bar) bar.style.width = Math.round(100 * rem / (dm.seconds * 1000)) + '%'; if (secs) secs.textContent = Math.ceil(rem / 1000) + 's'; if (rem <= 0) { cur.dmResult = Game.dm.timeout(); toast('TOO LATE · ' + cur.dmResult.protege.name, 'mag'); render(); } }
  setInterval(dmTick, 250);

  // ---- dev panel -------------------------------------------------------------------------
  function devPanel(){ if (!P().dev || !cur.devOpen) return ''; let body = ''; const tabs = [['lint', 'LINT'], ['step', 'STEP'], ['net', 'NET'], ['golden', 'GOLDEN'], ['cards', 'CALLS']]; const lint = Game.dev.lint();
    if (cur.dev === 'lint') body = (lint.errors.map(e => '<div class="err">ERROR ' + esc(e.where) + ' — ' + esc(e.msg) + '</div>').join('') || '<div class="ok">no errors</div>') + lint.warnings.map(w => '<div class="warn">warn ' + esc(w.where) + ' — ' + esc(w.msg) + '</div>').join('') + '<div style="margin-top:6px">counts: ' + esc(Object.entries(lint.coverage.counts).map(([k, v]) => k + ' ' + v).join(' · ')) + '<br>days without a level: ' + esc(lint.coverage.missingDays.join(',') || 'none') + '</div>';
    if (cur.dev === 'step') { const d = Game.dev.stepDiag(); body = d ? '<div>floor ' + d.step + ' · ' + d.type + ' · ' + d.skill + ' → <b class="' + (d.ok ? 'ok' : 'err') + '">' + (d.ok ? 'WOULD PASS' : 'would fail') + '</b> ' + esc(d.why || '') + '</div>' + (d.err ? '<div class="err">' + esc(d.err) + '</div>' : '') + (d.need ? '<div>need:</div>' + d.need.map(n => '<div class="' + (n.satisfied ? 'ok' : 'err') + '">  ' + (n.satisfied ? '✓' : '✗') + ' ' + esc(n.dev) + ' mode=' + esc(n.mode) + ' ctx=' + esc(n.ctx) + ' line=' + esc(n.line) + '</div>').join('') : '') + (d.check ? '<div>check: <span class="muted">' + esc(d.check) + '</span></div>' : '') + (d.issues && d.issues.length ? '<div class="warn">net issues: ' + esc(d.issues.map(i => i.kind + ' @ ' + i.where).join(' | ')) + '</div>' : '') : '<div class="muted">not in a dive</div>'; }
    if (cur.dev === 'net') { const S = Game.dev.netState(); body = S ? '<div>ping <input id="devfrom" placeholder="from (PC1)" size="8"> → <input id="devto" placeholder="ip" size="14"> <button class="act" id="devping">PING</button> <span id="devpingres"></span></div><div>hosts: ' + esc(JSON.stringify(Object.fromEntries(Object.entries(S.hosts).map(([k, h]) => [k, { ip: h.ip, gw: h.gw, up: h.up, rogue: h.rogue }])))) + '</div>' + Object.keys(S.tables).map(r => '<div><b>' + r + '</b> ' + esc(S.tables[r].map(e => e.proto + ' ' + e.prefix + '/' + e.len + (e.via ? ' via ' + e.via : ' ' + e.iface)).join(' | ')) + '</div>').join('') + (S.issues.length ? '<div class="warn">issues: ' + esc(S.issues.map(i => i.kind + ' @ ' + i.where).join(' | ')) + '</div>' : '<div class="ok">no issues</div>') + '<div>threats: ' + esc(JSON.stringify(S.threats)) + '</div>' : '<div class="muted">no net in this dive (STP-only topo or no dive)</div>'; }
    if (cur.dev === 'golden') body = '<div>' + JOBS.map(j => '<button class="act" data-golden="' + j.id + '">' + esc(j.id) + '</button>').join(' ') + '</div><div id="goldenres" style="margin-top:6px">' + (cur.goldenRes ? goldenHtml(cur.goldenRes) : 'click a gig to play its golden solution headless') + '</div>';
    if (cur.dev === 'cards') { const all = Game.allCards(); const un = all.filter(Game.cardUnlocked); body = '<div>' + all.length + ' possible calls, ' + un.length + ' unlocked, ' + SRS.due(all, Game.state.cards, Game.cardUnlocked, Date.now()).length + ' due now · <button class="act" id="forcedm">FORCE CALL</button> · roster: ' + Game.state.roster.list.map(p => p.name + '/' + p.arch + '/d' + p.danger).join(', ') + '</div>' + un.slice(0, 40).map(c => '<div>' + esc(c.id) + ' [' + esc(c.skill || c.level) + '] ' + esc(c.q).slice(0, 90) + (Game.state.cards[c.id] ? ' <span class="muted">box ' + Game.state.cards[c.id].box + '</span>' : '') + '</div>').join(''); }
    return '<div class="devbar"><div class="tabs">' + tabs.map(([k, l]) => '<button data-devtab="' + k + '" class="' + (cur.dev === k ? 'on' : '') + '">' + l + '</button>').join('') + '<span class="sp"></span>' + (lint.errors.length ? '<span class="cnt">' + lint.errors.length + ' lint errors</span>' : '') + (lint.warnings.some(w => /out-of-world/.test(w.msg)) ? '<span class="cnt" style="color:var(--yel)">' + lint.warnings.filter(w => /out-of-world/.test(w.msg)).length + ' out-of-world words</span>' : '') + '<button data-devtab="close">✕</button></div><div class="body">' + body + '</div></div>'; }
  function goldenHtml(r){ return '<div class="' + (r.ok ? 'ok' : 'err') + '">' + esc(r.job) + ': ' + (r.ok ? 'PASS' : 'FAIL — ' + esc(r.error)) + '</div>' + r.steps.map(s => '<div class="' + (s.ok ? 'ok' : 'err') + '">  floor ' + (s.i + 1) + ' ' + s.type + ' ' + s.skill + ' ' + (s.ok ? '✓' : '✗ ' + esc(s.why || '')) + '</div>').join('') + r.warnings.map(w => '<div class="warn">  ⚠ ' + esc(w) + '</div>').join('') + (r.console ? Object.entries(r.console).map(([d, t]) => '<div class="muted">[' + d + '] ' + esc(t) + '</div>').join('') : ''); }
  window.addEventListener('error', e => { const b = document.createElement('div'); b.className = 'errbanner'; b.textContent = 'JS error: ' + e.message + ' (' + (e.filename || '').split('/').pop() + ':' + e.lineno + ')'; document.body.appendChild(b); setTimeout(() => b.remove(), 12000); });

  // ---- render ---------------------------------------------------------------------------------
  function render(){ const s = Game.state; const a = app(); document.body.classList.toggle('devon', !!(P().dev && cur.devOpen)); document.body.className = document.body.className.replace(/\btheme-\w+/g, '').trim() + (s.perks && s.perks.theme ? ' theme-' + s.perks.theme : '');
    if (s.handle && s.dead) { a.innerHTML = deadView(); return; }
    if (!s.handle) { a.innerHTML = intro(); $('#go').onclick = () => { const r = Game.setHandle($('#handle').value, $('#pass').value); if (r.ok) { view = 'home'; render(); } else { toast(r.why, 'mag'); (r.field === 'pass' ? $('#pass') : $('#handle')).focus(); } }; $('#handle').onkeydown = e => { if (e.key === 'Enter') $('#pass').focus(); }; $('#pass').onkeydown = e => { if (e.key === 'Enter') $('#go').click(); }; a.querySelectorAll('[data-resume]').forEach(b => b.onclick = () => { $('#handle').value = b.dataset.resume; $('#pass').focus(); }); const si = $('#signin'); if (si) si.onclick = () => Auth.signIn().catch(err => toast('sign-in failed: ' + err.message, 'mag')); $('#handle').focus(); return; }
    if (view !== 'run') Game.dm.maybeCreate();
    let body = ''; if (view === 'home') body = home(); else if (view === 'grid') body = grid(); else if (view === 'level') body = level(); else if (view === 'jobs') body = jobs(); else if (view === 'run') body = runView(); else if (view === 'deck') body = deck(); else if (view === 'shop') body = shopView(); else if (view === 'key') body = keyView(); else if (view === 'stats') body = statsView(); else if (view === 'crew') body = crewView(); else body = logView();
    a.innerHTML = hud() + body + dmOverlay() + devPanel();
    a.querySelectorAll('.npcslot').forEach(sl => { if (sl.dataset.protege) { const p = Game.state.roster.list.find(x => x.id === sl.dataset.protege) || (cur.dmResult && cur.dmResult.protege); sl.replaceWith(npcEl(null, +sl.dataset.size, p ? p.look : { seed: 'p' })); } else sl.replaceWith(npcEl(sl.dataset.npc, +sl.dataset.size)); });
    if (view === 'run' && Game.run && !Game.run.result) { drawMap(); const o = $('#conout'); if (o) o.scrollTop = o.scrollHeight; const inp = $('#conin'); if (inp && !Game.dm.pending()) inp.focus(); }
    window.scrollTo({ top: (view === 'run' && lastView === 'run') ? window.scrollY : 0 }); lastView = view; }
  setInterval(() => { const r = Game.run; const el = $('#runclock'); if (r && el && !r.result) { const s = Math.floor((Date.now() - r.startedAt) / 1000); el.textContent = String(Math.floor(s / 60)).padStart(2, '0') + ':' + String(s % 60).padStart(2, '0'); } }, 1000);

  document.addEventListener('click', e => {
    const t = e.target.closest('[data-v],[data-stage],[data-level],[data-job],[data-start],[data-opt],[data-choice],[data-multi],[data-up],[data-down],[data-dev],[data-node],[data-dmans],[data-devtab],[data-golden],[data-buy],[data-eat],[data-give],[data-favor],[data-theme],#next,#prev,#finish,#commit,#hint,#walk,#abort,#wipe,#logout,#signin,#signout,#reconnect,#reload,#exitdoor,#devtoggle,#opendm,#dmopen,#dmlater,#dmclose,#forcedm,#devping'); if (!t) return;
    if (t.id === 'logout') { if (view === 'run' && Game.run && !Game.run.result && !confirm('Jack out? This dive is lost.')) return; Game.logout(); view = 'home'; cur = Object.assign(cur, { stage: null, level: null, beat: 0, job: null, synced: null }); return render(); }
    if (t.id === 'signin') { Auth.signIn().then(tok => { if (!tok) toast('sign-in did not go through', 'mag'); }).catch(err => toast('sign-in failed: ' + err.message, 'mag')); return; } if (t.id === 'signout') { Auth.signOut().then(render); return; }
    if (t.id === 'reconnect') { Auth.ensureToken().then(tok => { toast(tok ? 'your Drive is listening again' : 'Google did not answer. try again', tok ? 'grn' : 'mag'); render(); }); return; }
    if (t.id === 'devtoggle') { cur.devOpen = !cur.devOpen; return render(); } if (t.dataset.devtab) { if (t.dataset.devtab === 'close') cur.devOpen = false; else cur.dev = t.dataset.devtab; return render(); }
    if (t.dataset.golden) { cur.goldenRes = Game.runSolution(t.dataset.golden); return render(); } if (t.id === 'devping') { const r = Game.dev.ping($('#devfrom').value.trim(), $('#devto').value.trim()); $('#devpingres').textContent = r ? (r.ok ? 'OK ' : 'FAIL ') + r.reason + ' · ' + r.path.map(p => p.dev + ':' + p.act).join(' → ') : 'no net'; return; }
    if (t.dataset.buy) { const r = Game.shop.buy(t.dataset.buy); cur.shopMsg = r.ok ? (r.onTheHouse ? 'On the house. Once. Do not make it a habit.' : r.item.line ? r.item.line.replace(/^Marrow: /, '').replace(/^"|"$/g, '') : 'Yours.') : r.why; toast(r.ok ? (r.onTheHouse ? 'ON THE HOUSE · ' : r.item.kind === 'service' ? 'CHROME · FULL' : 'BOUGHT · ' + r.item.name) : r.why, r.ok ? 'grn' : 'mag'); return render(); }
    if (t.dataset.eat) { const r = Game.body.eat(t.dataset.eat); cur.shopMsg = r.ok ? 'Eat slower. Nobody is taking it.' : r.why; toast(r.ok ? 'FOOD · ' + r.food : r.why, r.ok ? 'grn' : 'mag'); return render(); }
    if (t.id === 'reload') { Game.reload(); view = 'home'; cur = Object.assign(cur, { stage: null, level: null, beat: 0, job: null, synced: null, dmSnoozed: null }); toast('back on your feet', 'grn'); return render(); } if (t.id === 'exitdoor') { Game.logout(); view = 'home'; return render(); }
    if (t.dataset.give) { const r = Game.shop.give(t.dataset.give, t.dataset.to); if (r.ok) toast(r.line, 'grn'); return render(); } if (t.dataset.favor) { const r = Game.shop.favor(t.dataset.favor); toast(r.ok ? 'DISPATCH PULLED THEM OUT' : r.why, r.ok ? 'yel' : 'mag'); return render(); }
    if (t.dataset.theme !== undefined) { Game.shop.setTheme(t.dataset.theme || null); return render(); }
    if (t.id === 'opendm' || t.id === 'dmopen') { cur.dmSnoozed = null; Game.dm.open(); return render(); } if (t.id === 'dmlater') { const d = Game.dm.pending(); if (d) cur.dmSnoozed = d.id; return render(); } if (t.id === 'forcedm') { Game.dm.maybeCreate(true); return render(); }
    if (t.dataset.dmans) { cur.dmResult = Game.dm.answer(+t.dataset.dmans); if (cur.dmResult) { const o = cur.dmResult.out; toast(o.forgiven ? 'THE BURNER TOOK IT · ' + cur.dmResult.protege.name : cur.dmResult.ok ? 'GOT THROUGH · ' + cur.dmResult.protege.name : o.flatlined ? 'FLATLINED · ' + cur.dmResult.protege.name : 'WRONG · ' + cur.dmResult.protege.name, cur.dmResult.ok || o.forgiven ? 'grn' : 'mag'); } return render(); }
    if (t.id === 'dmclose') { cur.dmResult = null; return render(); }
    if (t.dataset.v) { if (view === 'run' && Game.run && !Game.run.result && t.dataset.v !== 'run') { if (!confirm('Jack out? This dive is lost.')) return; Game.abort(); } view = t.dataset.v; if (view === 'crew') cur.dmSnoozed = null; if (view === 'jobs' && Game.run && Game.run.result) Game.abort(); cur.shopMsg = null; return render(); }
    if (t.dataset.stage) { cur.stage = t.dataset.stage; return render(); } if (t.dataset.level) { cur.level = t.dataset.level; cur.beat = 0; cur.synced = null; cur.stage = Game.stageOf(cur.level).id; view = 'level'; return render(); }
    if (t.dataset.job) { cur.job = t.dataset.job; return render(); } if (t.dataset.start) { const job = JOBS.find(j => j.id === t.dataset.start); dive(job, () => { Game.startJob(job.id); view = 'run'; render(); }); return; } if (t.dataset.opt) { cur.synced = +t.dataset.opt; return render(); }
    if (t.id === 'next') { cur.beat++; cur.synced = null; return render(); } if (t.id === 'prev') { cur.beat--; cur.synced = null; return render(); } if (t.id === 'finish') { const first = Game.readLevel(cur.level); if (first) toast('MET · ' + Game.levelById(cur.level).title + ' · quickhacks slotted'); view = 'grid'; return render(); }
    if (t.dataset.choice) { Game.run.choice = +t.dataset.choice; return render(); } if (t.dataset.multi) { const i = +t.dataset.multi; if (Game.run.multi.has(i)) Game.run.multi.delete(i); else Game.run.multi.add(i); return render(); }
    if (t.dataset.up) { const i = +t.dataset.up; const o = Game.run.order; [o[i - 1], o[i]] = [o[i], o[i - 1]]; return render(); } if (t.dataset.down) { const i = +t.dataset.down; const o = Game.run.order; [o[i + 1], o[i]] = [o[i], o[i + 1]]; return render(); }
    if (t.dataset.dev) { Game.run.active = t.dataset.dev; return render(); } if (t.dataset.node) { Game.run.selected = t.dataset.node; Game.run.feedback = null; return render(); }
    if (t.id === 'commit') { const r = Game.run; const stBefore = Game.currentStep(); if (stBefore.type === 'calc') document.querySelectorAll('[data-calc]').forEach(i => r.calc[i.dataset.calc] = i.value); if (stBefore.type === 'form') document.querySelectorAll('[data-form]').forEach(i => r.form[i.dataset.form] = i.value); if (stBefore.type === 'text') { const ta = document.querySelector('[data-text]'); if (ta) r.text = ta.value; }
      const res = Game.commit(); if (res.ok) { toast(res.finished ? (r.job.rite ? 'RITE COMPLETE' : 'DIVE COMPLETE') : 'FLOOR CLEARED', 'grn'); if (r.feedback && r.feedback.leveled) toast('SHARPER · ' + SKILLS[r.feedback.leveled.skill] + ' → ' + Game.LEVEL_NAMES[r.feedback.leveled.level], 'mag'); if (res.result && res.result.promoted) toast('THE BOARD CALLS YOU CLASS ' + res.result.promoted, 'yel'); } return render(); }
    if (t.id === 'hint') { Game.run.hintShown = Game.useHint(); return render(); } if (t.id === 'walk') { Game.run.walk = Game.reveal(); return render(); }
    if (t.id === 'abort') { if (confirm('Jack out? This dive is lost.')) { Game.abort(); view = 'jobs'; render(); } return; }
    if (t.id === 'wipe') { if (confirm('Wipe this handle\'s record? Everything.')) { Game.reset(); render(); } return; }
  });
  document.addEventListener('keydown', e => { const inp = e.target; if (!inp || inp.id !== 'conin') return; const r = Game.run; if (!r) return; const d = r.devices[r.active];
    if (e.key === 'Enter') { const raw = inp.value; r.history.push(raw); r.hIdx = r.history.length; d.exec(raw, r.devices); inp.value = ''; const o = $('#conout'); o.innerHTML = d.out.map(x => '<div class="' + x.t + '">' + esc(x.s) + '</div>').join(''); o.scrollTop = o.scrollHeight; $('#prompt').textContent = d.prompt(); document.querySelector('.console .devs .muted').textContent = 'SHELL · ' + d.prompt(); drawMap(); if (cur.devOpen) { const dp = document.querySelector('.devbar'); if (dp) dp.outerHTML = devPanel(); } }
    if (e.key === 'ArrowUp') { r.hIdx = Math.max(0, (r.hIdx == null ? r.history.length : r.hIdx) - 1); inp.value = r.history[r.hIdx] || ''; e.preventDefault(); } if (e.key === 'ArrowDown') { r.hIdx = Math.min(r.history.length, (r.hIdx == null ? r.history.length : r.hIdx) + 1); inp.value = r.history[r.hIdx] || ''; e.preventDefault(); } if (e.key === 'Tab') e.preventDefault(); });
  document.addEventListener('input', e => { const r = Game.run; if (!r || !e.target.dataset) return; if (e.target.dataset.calc) r.calc[e.target.dataset.calc] = e.target.value; if (e.target.dataset.form) r.form[e.target.dataset.form] = e.target.value; if (e.target.dataset.text) r.text = e.target.value; });

  window.UI = { render, toast, go: v => { view = v; render(); } };
  document.addEventListener('DOMContentLoaded', () => { preloadPortraits(); if (window.Auth) Auth.init(window.PLATFORM); render(); });
})();
