/* ui.js — rendering. Vanilla DOM, no build.
   Views: intro, home, grid, level, jobs, run, deck, key, stats, crew, log. Plus the protégé DM overlay and the dev panel (?dev=1). */
(function(){
  const $ = s => document.querySelector(s); const app = () => $('#app');
  const esc = s => String(s == null ? '' : s).replace(/[&<>"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));
  let view = 'home', lastView = null, cur = { stage: null, level: null, beat: 0, job: null, synced: null, dev: 'lint', dmResult: null, devOpen: false, goldenRes: null };
  const P = () => window.PLATFORM || {};

  function rich(text){ return esc(text).replace(/\[\[([^\]]+)\]\]/g, (m, t) => { const def = GLOSSARY[t.toLowerCase()] || 'See the codex.'; return '<span class="term" data-def="' + esc(def) + '">' + esc(t) + '</span>'; })
      .replace(/"([^"]{2,80}?)"/g, (m, q) => /^[a-z0-9 \-\/\.\,]+$/i.test(q) && /^(show|spanning-tree|configure|interface|enable|write|copy|ip |vlan|hostname|switchport|do |no |root|end$|ping|access-list|router)/i.test(q) ? '<code>' + q + '</code>' : m); }
  function toast(msg, cls){ let t = $('.toast'); if (!t) { t = document.createElement('div'); t.className = 'toast'; document.body.appendChild(t); } const d = document.createElement('div'); d.className = cls || ''; d.textContent = msg; t.appendChild(d); setTimeout(() => d.remove(), 4200); }
  function npcEl(id, size, look){ const n = NPCS[id] || { name: id, look: look || { seed: String(id) } }; const wrap = document.createElement('span'); wrap.style.display = 'inline-block'; wrap.style.lineHeight = '0';
    const apply = el => { if (size) { el.style.width = size + 'px'; el.style.height = size + 'px'; } return el; }; const cv = document.createElement('canvas'); Sprite.animate(cv, look || n.look); wrap.appendChild(apply(cv));
    if (NPCS[id]) { const img = new Image(); img.alt = n.name; img.src = 'assets/npc/' + id + '.png'; img.onload = () => { wrap.innerHTML = ''; wrap.appendChild(apply(img)); }; } return wrap; }
  const npcSlot = (id, size) => '<span class="npcslot" data-npc="' + esc(id) + '" data-size="' + size + '"></span>';
  const pSlot = (p, size) => '<span class="npcslot" data-protege="' + esc(p.id) + '" data-size="' + size + '"></span>';

  // ---- HUD --------------------------------------------------------------------------
  function hud(){ const s = Game.state, c = Game.classFor(s.rep), nx = Game.nextClass(s.rep); const pct = nx ? Math.round(((s.rep - c.min) / (nx.min - c.min)) * 100) : 100;
    const openJobs = JOBS.filter(j => Game.jobStatus(j).locked.length === 0 && !s.jobsDone[j.id]).length; const alive = Protege.active(s.roster).length, lost = Protege.lost(s.roster).length; const dm = Game.dm.pending(); const u = window.Auth && Auth.user();
    return '<div class="hud"><div class="logo">NETRUN<small>://</small>CCNA</div><div class="handle">handle <b>' + esc(s.handle || '—') + '</b>' + (u ? ' <span class="signin">' + (u.avatar ? '<img src="' + esc(u.avatar) + '">' : '') + esc(u.name) + '</span>' : '') + '</div><span class="cls ' + c.id + '">CLASS ' + c.id + '</span>' +
      '<div class="rep"><span>REP ' + s.rep + (nx ? ' / ' + nx.min + ' → Class ' + nx.id : ' · MAX for this arc') + '</span><div class="bar"><i style="width:' + pct + '%"></i></div></div>' +
      (s.roster.list.length ? '<div class="crew">crew <b>' + alive + '</b>' + (lost ? ' <span class="lost">†' + lost + '</span>' : '') + '</div>' : '') +
      '<div class="nav">' + [['home', 'MAP'], ['grid', 'GRID'], ['jobs', 'JOBS'], ['crew', 'CREW'], ['deck', 'DECK'], ['key', 'KEY'], ['stats', 'STATS'], ['log', 'LOG']].map(([v, l]) => '<button data-v="' + v + '" class="' + (view === v || (v === 'grid' && view === 'level') || (v === 'jobs' && view === 'run') ? 'on' : '') + (v === 'crew' && dm ? ' dmping' : '') + '">' + l + (v === 'jobs' && openJobs ? '<span class="badge">' + openJobs + '</span>' : '') + (v === 'crew' && dm ? '<span class="badge">DM</span>' : '') + '</button>').join('') +
      (window.Auth && Auth.configured && !u ? '<button id="signin" title="sign in to keep your saves across devices">SIGN IN</button>' : '') + (u ? '<button id="signout">SIGN OUT</button>' : '') + (P().dev ? '<button id="devtoggle" class="dev">DEV</button>' : '') + '<button id="logout" title="back to the opening screen. progress stays saved under this handle">LOG OUT</button></div></div>'; }

  // ---- views ------------------------------------------------------------------------
  function intro(){ return '<div class="intro"><h1 class="glitch">NETRUN<span>://</span>CCNA</h1><p>Watson district. Old switches, thin budgets, people who remember every outage by what they lost. You are new, you need work, and somebody vouched for you.<br><b>THE GRID</b> is where you meet the people who keep the district running. Each of them works one part of the network, and they will teach you the way people teach: by showing you the thing that went wrong.<br><b>JOBS</b> is the board. Dispatch sends a gig, you go to the building, you fix it in a real console, and someone gets their day back. Skills only count once you have used them without help.<br><b>CREW</b> are the kids who look up to you. They DM you from their own gigs when they are stuck. Answer fast and right, or it goes badly for them.</p>' +
      '<p class="muted">Alpha framework · Stage 4, Spanning Tree, is the built content (Jeremy\'s IT Lab days 20–21). Exam bar: CCNA 200-301.</p>' +
      '<p><input id="handle" placeholder="your handle" maxlength="18" autocomplete="off"> <button class="btn mag" id="go">JACK IN</button></p>' + (Game.profiles().length ? '<p class="muted" style="font-size:12px">saved on this browser: ' + Game.profiles().map(h => '<button class="btn ghost" data-resume="' + esc(h) + '" style="margin:2px 4px">' + esc(h) + '</button>').join('') + '</p>' : '') +
      (window.Auth && Auth.configured ? '<p><button class="btn ghost" id="signin">SIGN IN TO SYNC SAVES</button></p>' : '') +
      '<div class="footer">Study material follows Jeremy\'s IT Lab. Built on notes by <a href="https://github.com/psaumur/CCNA_Course_Notes" target="_blank">psaumur/CCNA_Course_Notes</a> and <a href="https://github.com/sparrowjumpy/CCNA-Notes" target="_blank">sparrowjumpy/CCNA-Notes</a>. Lore from real network history. MIT.</div></div>'; }

  function home(){ const s = Game.state; const reads = Object.keys(s.read).length; const total = STAGES.reduce((a, st) => a + st.levels.length, 0); const done = Object.keys(s.jobsDone).length; const dm = Game.dm.pending();
    return (dm ? '<div class="panel" style="border-color:var(--mag)"><b class="mag">DM waiting.</b> ' + esc(dm.open.split(':')[0]) + ' needs you. <button class="btn mag" data-v="crew">OPEN</button> <span class="muted">the clock starts when you read it.</span></div>' : '') +
      '<div class="panel"><h2>JOURNEY MAP</h2><div class="muted">one arc per discipline. rep and class carry across. only one is mapped so far.</div><div class="arcs" style="margin-top:12px">' +
      ARCS.map(a => '<div class="arc ' + (a.status === 'play' ? 'play' : 'lock') + '" ' + (a.status === 'play' ? 'data-v="grid"' : '') + '><div class="n">ARC ' + a.n + '</div><div class="t">' + a.title + '</div><div class="st">' + esc(a.sub) + '</div>' + (a.status === 'play' ? '<div style="margin-top:8px"><span class="tag on">playable</span><span class="tag">' + reads + '/' + total + ' synced</span><span class="tag">' + done + '/' + JOBS.length + ' gigs</span></div>' : '<div style="margin-top:8px"><span class="tag lock">signal lost · not yet mapped</span></div>') + '</div>').join('') + '</div></div>' +
      '<div class="grid2"><div class="panel"><h2>THE GRID</h2><p class="dim">The people. Each one works a part of the network, and their name gives it away. Go and talk to them. Glowing <span class="term" data-def="Like this. Hover any glowing word for the exam definition.">words</span> are the ones the exam and the job will both use. Talking to someone puts a skill in your deck at level zero. Using it in a gig is what makes it count.</p><button class="btn" data-v="grid">GO TO THE GRID</button></div>' +
      '<div class="panel"><h2>JOBS</h2><p class="dim">The board. Dispatch sends a message, the client says what is wrong in their own words, and you go and fix it. A live map, a real console, an NPC beside you. Skills level only when you use them without a hint. Repeat a gig for less rep but real practice. Bigger gigs bring back earlier problems in new buildings.</p><button class="btn mag" data-v="jobs">OPEN THE BOARD</button></div></div>'; }

  function grid(){ const s = Game.state; if (!cur.stage) cur.stage = (STAGES.find(st => st.status === 'live') || STAGES[0]).id; const st = STAGES.find(x => x.id === cur.stage);
    return '<div class="panel"><h2>THE GRID · ARC 01</h2><div class="stages"><div class="stagelist">' + STAGES.map(x => { const n = x.levels.filter(l => s.read[l.id]).length; return '<button data-stage="' + x.id + '" class="' + (x.id === cur.stage ? 'on' : '') + '">' + esc(x.title) + '<span class="p">' + n + '/' + x.levels.length + '</span><br><span class="muted">' + esc(x.sub) + '</span></button>'; }).join('') + '</div>' +
      '<div><div class="row" style="margin-bottom:10px;align-items:flex-start"><div class="npcbox" style="width:72px;flex:none">' + npcSlot(st.npc, 72) + '</div><div><div class="muted" style="font-size:11px;letter-spacing:.14em">' + (st.status === 'live' ? '<span class="tag on">built</span>' : '<span class="tag">framework stub · intro only</span>') + '</div><div style="font-size:15px;font-weight:700;margin-top:4px">' + esc(NPCS[st.npc].name) + ' <span class="muted">· ' + esc(NPCS[st.npc].sys) + '</span></div><div class="dim">' + esc(NPCS[st.npc].role) + '</div></div></div>' +
      '<div class="levels">' + st.levels.map(l => '<div class="level ' + (s.read[l.id] ? 'done' : '') + '" data-level="' + l.id + '">' + (s.read[l.id] ? '<span class="chk">✓</span>' : '') + '<div class="who">' + esc(NPCS[l.npc].name) + '</div><div class="t">' + esc(l.title) + '</div><div class="s">' + esc(l.sub) + '</div></div>').join('') + '</div></div></div></div>'; }

  function level(){ const l = Game.levelById(cur.level); const n = NPCS[l.npc]; const b = l.beats[cur.beat]; const last = cur.beat === l.beats.length - 1; let body = '';
    if (b.k === 'TALK') body = '<div class="speech"><div class="k">' + esc(n.name.toUpperCase()) + '</div>' + rich(b.text) + '</div>';
    if (b.k === 'LORE') body = '<div class="speech lore"><div class="k">AS TOLD · real history</div>' + rich(b.text) + '</div>';
    if (b.k === 'KIT') body = '<div class="speech kit"><div class="k">WHAT YOU CARRY OUT</div>' + rich(b.text) + '<ul class="kitlist">' + b.kit.map(k => '<li><code>' + esc(k.cmd) + '</code> <span class="dim">' + rich(k.what) + '</span></li>').join('') + '</ul></div>';
    if (b.k === 'SCENE') body = '<div class="scene">' + (b.where ? '<div class="where">' + rich(b.where) + '</div>' : '') + (b.lines || []).map(ln => ln.who === 'you' ? '<div class="ln you"><span class="who">' + esc(Game.state.handle) + '</span>' + rich(ln.text) + '</div>' : ln.who === 'narr' ? '<div class="ln narr">' + rich(ln.text) + '</div>' : '<div class="ln"><span class="who">' + esc((NPCS[ln.who] || { name: ln.who }).name) + '</span>' + rich(ln.text) + '</div>').join('') +
      (b.choice ? '<div class="opts">' + b.choice.opts.map((o, i) => '<button data-opt="' + i + '" class="' + (cur.synced === i ? 'right' : '') + '">' + esc(o.say) + '</button>').join('') + '</div>' + (cur.synced != null ? '<div class="ln reply"><span class="who">' + esc((NPCS[b.choice.opts[cur.synced].who || l.npc] || {}).name || '') + '</span>' + rich(b.choice.opts[cur.synced].reply) + '</div>' : '') : '') + '</div>';
    if (b.k === 'SYNC') { const q = b.q; body = '<div class="speech sync"><div class="k">SOMEONE ASKS · no rep on the line</div>' + rich(q.prompt) + '<div class="opts">' + q.opts.map((o, i) => '<button data-opt="' + i + '" class="' + (cur.synced == null ? '' : i === q.a ? 'right' : i === cur.synced ? 'wrong' : '') + '">' + String.fromCharCode(65 + i) + '. ' + esc(o) + '</button>').join('') + '</div>' + (cur.synced == null ? '' : '<div style="margin-top:8px" class="' + (cur.synced === q.a ? 'good' : 'warn') + '">' + rich(cur.synced === q.a ? q.yes : q.no) + '</div>' + (q.why ? '<div class="why"><b>The answer is ' + String.fromCharCode(65 + q.a) + '. ' + esc(q.opts[q.a]) + '</b><br>' + rich(q.why) + '</div>' : '')) + '</div>'; }
    return '<div class="panel"><div class="row" style="justify-content:space-between"><h2>' + esc(l.title) + '</h2><button class="btn ghost" data-v="grid">← GRID</button></div><div class="muted" style="font-size:11px">' + esc(l.sub) + '</div>' +
      '<div class="dlg" style="margin-top:14px"><div class="npcbox" id="npcbox">' + npcSlot(l.npc, 192) + '<div class="name">' + esc(n.name) + '</div><div class="sys">' + esc(n.sys) + '</div><div class="role">' + esc(n.role) + '</div></div>' +
      '<div>' + body + '<div class="dots">' + l.beats.map((x, i) => '<i class="' + (i <= cur.beat ? 'on' : '') + '"></i>').join('') + '</div><div class="row">' + (!last ? '<button class="btn" id="next"' + (b.k === 'SCENE' && b.choice && cur.synced == null ? ' disabled' : '') + '>NEXT ▸</button>' : '<button class="btn grn" id="finish">SYNC COMPLETE ✓</button>') + (cur.beat > 0 ? '<button class="btn ghost" id="prev">◂ BACK</button>' : '') +
      '<span class="muted" style="font-size:11px">' + (b.k === 'SYNC' && cur.synced == null ? 'answer or skip. talking never levels a skill. using it on a gig does.' : b.k === 'SCENE' && b.choice && cur.synced == null ? 'say something to continue' : '') + '</span></div></div></div></div>'; }

  function jobs(){ const list = JOBS.map(j => ({ j, st: Game.jobStatus(j) })); const sel = cur.job ? list.find(x => x.j.id === cur.job) : null;
    return '<div class="panel"><h2>INBOX · DISPATCH</h2><div class="inbox"><div>' + list.map(({ j, st }) => '<div class="msg ' + (st.locked.length ? 'lock' : '') + (cur.job === j.id ? ' on' : '') + '" data-job="' + j.id + '"><span class="cls ' + j.cls + '">' + j.cls + '</span><div class="from">FROM ' + esc(NPCS[j.from].name.toUpperCase()) + ' · +' + j.rep + ' REP</div><div class="t">' + esc(j.title) + '</div><div class="meta">' + (st.done ? '✓ done ×' + st.done.times + (st.done.bestMs ? ' · best ' + Math.round(st.done.bestMs / 1000) + 's' : '') + ' · repeat for 40%' : st.locked.length ? '🔒 ' + st.locked.length + ' requirement' + (st.locked.length > 1 ? 's' : '') : '● open') + '</div></div>').join('') + '</div>' +
      '<div>' + (sel ? jobDetail(sel.j, sel.st) : '<div class="muted">select a message. locked gigs tell you who to talk to first.</div>') + '</div></div></div>'; }
  function jobDetail(j, st){ return '<div class="row"><span class="cls ' + j.cls + '">CLASS ' + j.cls + '</span><b>' + esc(j.title) + '</b><span class="muted">from ' + esc(NPCS[j.from].name) + ' · +' + j.rep + ' rep' + (st.done ? ' (repeat: +' + Math.round(j.rep * 0.4) + ')' : '') + (j.team && j.team.min ? ' · crew of ' + j.team.min : '') + '</span></div><div class="brief">' + rich(j.brief) + '</div>' +
      '<div class="muted" style="font-size:11px">skills exercised: ' + [...new Set(j.steps.map(s => s.skill))].map(k => '<span class="tag">' + esc(SKILLS[k] || k) + '</span>').join('') + '</div>' + (st.locked.length ? '<h3>LOCKED</h3><ul class="reqs">' + st.locked.map(r => '<li class="warn">' + (r.kind === 'read' ? '<a data-level="' + r.id + '">' + esc(r.text) + '</a>' : esc(r.text)) + '</li>').join('') + '</ul>' : '<p><button class="btn mag" data-start="' + j.id + '">JACK IN ▸</button></p>'); }

  // ---- run ----------------------------------------------------------------------------
  function runView(){ const r = Game.run; if (!r) { view = 'jobs'; return jobs(); } if (r.result) return resultView(r); const st = Game.currentStep(); const n = NPCS[r.job.from];
    return '<div class="panel"><div class="row" style="justify-content:space-between"><h2>NET RUN · ' + esc(r.job.title) + ' <span class="cls ' + r.job.cls + '" style="font-size:11px">CLASS ' + r.job.cls + '</span></h2><span class="muted" style="font-size:11px" id="runclock">00:00</span><button class="btn ghost" id="abort">JACK OUT</button></div>' +
      '<div class="run"><div><div class="netmap" id="netmap"></div><ol class="steps" style="margin-top:10px">' + r.job.steps.map((s, i) => '<li class="' + (i < r.step ? 'done' : i === r.step ? 'cur' : '') + (r.hinted[i] ? ' hinted' : '') + '">' + (i + 1) + '. ' + esc(SKILLS[s.skill] || s.skill) + (i === r.step ? ' ◂' : '') + (r.fails[i] ? ' <span class="muted">(' + r.fails[i] + ' miss' + (r.fails[i] > 1 ? 'es' : '') + ')</span>' : '') + '</li>').join('') + '</ol></div>' +
      '<div><div class="task"><div class="npcline">' + npcSlot(r.job.from, 48) + '<div><div class="who">' + esc(n.name.toUpperCase()) + ' · step ' + (r.step + 1) + '/' + r.job.steps.length + '</div><div>' + rich(st.text) + '</div></div></div>' + stepInput(st, r) +
      (r.feedback ? '<div style="margin-top:8px" class="' + (r.feedback.ok ? 'good' : 'bad') + '">' + rich(r.feedback.text) + (r.feedback.leveled ? ' <span class="mag">▲ ' + esc(SKILLS[r.feedback.leveled.skill]) + ' → ' + Game.LEVEL_NAMES[r.feedback.leveled.level] + '</span>' : '') + '</div>' : '') +
      (r.lastWhy ? '<details class="why"><summary>why that worked</summary>' + rich(r.lastWhy) + '</details>' : '') + (r.hintShown ? '<div class="hintbox">' + esc(r.hintShown) + '</div>' : '') + (r.walk ? '<div class="why"><b>THE ANSWER</b><br><span class="ans">' + esc(r.walk.answer).replace(/\n/g, '<br>') + '</span><br><br>' + rich(r.walk.why || 'No explanation written for this step yet.') + '</div>' : '') +
      '<div class="row" style="margin-top:10px"><button class="btn grn" id="commit">COMMIT ▸</button>' + (st.hint ? '<button class="btn ghost" id="hint">' + (r.hinted[r.step] ? 'HINTED' : 'HINT') + '</button>' : '') + '<button class="btn ghost" id="walk" title="shows the answer and explains it. counts as a hint: no level-up on this step">' + (r.walk ? 'ANSWER SHOWN' : 'WALK ME THROUGH IT') + '</button><span class="muted" style="font-size:10px">a hint or a walk-through costs the level-up for this step, nothing else</span></div></div>' + (r.job.devices.length ? consoleView(r) : '') + '</div></div></div>'; }
  function stepInput(st, r){
    if (st.type === 'choice') return '<div class="opts" style="margin-top:8px">' + st.opts.map((o, i) => '<button data-choice="' + i + '" class="' + (r.choice === i ? 'sel' : '') + '">' + String.fromCharCode(65 + i) + '. ' + esc(o) + '</button>').join('') + '</div>';
    if (st.type === 'multi') return '<div class="muted" style="margin-top:8px;font-size:12px">select every answer that applies</div><div class="opts">' + st.opts.map((o, i) => '<button data-multi="' + i + '" class="' + (r.multi.has(i) ? 'sel' : '') + '">' + (r.multi.has(i) ? '☑ ' : '☐ ') + String.fromCharCode(65 + i) + '. ' + esc(o) + '</button>').join('') + '</div>';
    if (st.type === 'calc') return '<div class="calc" style="margin-top:8px">' + st.fields.map(f => '<label>' + esc(f.label) + '<input data-calc="' + f.key + '" value="' + esc(r.calc[f.key] || '') + '" class="' + (r.feedback && r.feedback.bad ? (r.feedback.bad.includes(f.key) ? 'no' : 'ok') : '') + '" autocomplete="off"></label>').join('') + '</div>';
    if (st.type === 'order') { if (!r.order) { r.order = st.items.map((_, i) => i); for (let i = r.order.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1)); [r.order[i], r.order[j]] = [r.order[j], r.order[i]]; } if (r.order.every((v, i) => v === i)) r.order.reverse(); } return '<div class="muted" style="margin-top:8px;font-size:12px">put these in the right order, top to bottom</div><ol class="orderlist">' + r.order.map((idx, pos) => '<li><span class="n">' + (pos + 1) + '</span><span class="t">' + esc(st.items[idx]) + '</span><button data-up="' + pos + '"' + (pos === 0 ? ' disabled' : '') + '>▲</button><button data-down="' + pos + '"' + (pos === r.order.length - 1 ? ' disabled' : '') + '>▼</button></li>').join('') + '</ol>'; }
    if (st.type === 'form') return '<div class="formgrid" style="margin-top:8px">' + st.fields.map(f => '<label>' + esc(f.label) + '<select data-form="' + f.key + '" class="' + (r.feedback && r.feedback.bad ? (r.feedback.bad.includes(f.key) ? 'no' : 'ok') : '') + '"><option value="">— choose —</option>' + f.options.map(o => '<option' + (String(r.form[f.key]) === String(o) ? ' selected' : '') + '>' + esc(o) + '</option>').join('') + '</select></label>').join('') + '</div>';
    if (st.type === 'text') return '<div style="margin-top:8px"><textarea class="txt" data-text="1" placeholder="' + esc(st.placeholder || 'type your answer') + '">' + esc(r.text || '') + '</textarea></div>';
    if (st.type === 'find') return '<div class="muted" style="margin-top:8px;font-size:12px">selected: <b class="warn">' + esc(r.selected || 'nothing yet') + '</b> — click a node on the map, then COMMIT.</div>';
    return '<div class="muted" style="margin-top:8px;font-size:12px">do it in the console below, then COMMIT. short forms work: conf t, int g0/1, sh span, do sh run.</div>'; }
  function consoleView(r){ const d = r.devices[r.active]; return '<div class="console"><div class="devs">' + r.job.devices.map(n => '<button data-dev="' + n + '" class="' + (n === r.active ? 'on' : '') + '">' + n + '</button>').join('') + '<span class="muted" style="padding:5px 10px;font-size:10px">' + esc(d.prompt()) + '</span></div><div class="out" id="conout">' + d.out.map(o => '<div class="' + o.t + '">' + esc(o.s) + '</div>').join('') + '</div><div class="in-row"><span id="prompt">' + esc(d.prompt()) + '</span><input id="conin" autocomplete="off" spellcheck="false" placeholder="' + (d.kind === 'host' ? 'ping / ipconfig / arp -a / tracert · Enter' : 'type IOS here · ↑ history · Enter') + '"></div></div>'; }
  function autoMap(job){ const D = job.net.devices; const rows = { router: [], switch: [], l3switch: [], host: [], server: [], cloud: [], rogue: [], ap: [], wlc: [] }; Object.keys(D).forEach(n => (rows[D[n].kind] || rows.host).push(n)); const nodes = []; const place = (list, y, type) => list.forEach((n, i) => nodes.push({ id: n, label: n, type: type || D[n].kind, x: Math.round(520 * (i + 1) / (list.length + 1)), y }));
    place(rows.cloud, 30, 'cloud'); place(rows.router.concat(rows.l3switch), 100, 'router'); place(rows.switch, 190, 'switch'); place(rows.host.concat(rows.server, rows.ap, rows.wlc), 280, 'pc'); place(rows.rogue, 330, 'rogue');
    return { w: 520, h: 360, nodes, links: job.net.links.map(l => ({ a: l.a, b: l.b, ap: l.ap, bp: l.bp })), alert: job.net.alert || [] }; }
  function drawMap(){ const r = Game.run; const box = $('#netmap'); if (!r || !box) return; const m = r.job.map || (r.job.net ? autoMap(r.job) : { w: 520, h: 200, nodes: [], links: [] }); const W = m.w || 520, H = m.h || 300;
    let comp = null; try { comp = r.ctx.compute(r.vlanView || 1); } catch (e) { console.error(e); } let S = null; try { S = r.ctx.state && r.ctx.state(); } catch (e) { console.error(e); }
    const nodeCls = {}; const portRole = {}; const removed = n => (r.topo && r.topo.switches[n] && r.topo.switches[n].removed) || (r.netDef && r.netDef.devices[n] && r.netDef.devices[n].removed);
    if (comp) { for (const n in comp.switches) { const s = comp.switches[n]; if (s.isRoot && !removed(n)) nodeCls[n] = (nodeCls[n] || '') + ' root'; for (const pn in s.ports) portRole[n + '|' + pn] = s.ports[pn]; } }
    if (S) { for (const n in S.hosts) { const h = S.hosts[n]; if (!h.up || (!h.ip && h.dhcp)) nodeCls[n] = (nodeCls[n] || '') + ' alert'; if (h.rogue) nodeCls[n] = (nodeCls[n] || '') + ' alert'; } for (const n in S.ifaces) for (const p in S.ifaces[n]) if (S.ifaces[n][p].errdisabled) portRole[n + '|' + p] = Object.assign(portRole[n + '|' + p] || {}, { errdisabled: true }); }
    (m.alert || []).forEach(a => { if (!removed(a)) nodeCls[a] = (nodeCls[a] || '') + ' alert'; });
    const pos = {}; m.nodes.forEach(n => pos[n.id] = n); let svg = '<svg viewBox="0 0 ' + W + ' ' + H + '" xmlns="http://www.w3.org/2000/svg">';
    m.links.forEach(l => { const a = pos[l.a], b = pos[l.b]; if (!a || !b) return; if (removed(l.a) || removed(l.b)) return; let cls = 'link'; const pa = l.ap ? portRole[l.a + '|' + l.ap] : null, pb = l.bp ? portRole[l.b + '|' + l.bp] : null;
      const down = S && ((S.ifaces[l.a] && S.ifaces[l.a][l.ap] && !S.ifaces[l.a][l.ap].up) || (S.ifaces[l.b] && S.ifaces[l.b][l.bp] && !S.ifaces[l.b][l.bp].up));
      if (pa && pa.errdisabled || pb && pb.errdisabled) cls += ' err'; else if (down) cls += ' blocked'; else if (pa && pa.state === 'BLK' || pb && pb.state === 'BLK') cls += ' blocked'; else if ((m.alert || []).includes(l.b) || (m.alert || []).includes(l.a)) cls += ' hot';
      svg += '<line class="' + cls + '" x1="' + a.x + '" y1="' + a.y + '" x2="' + b.x + '" y2="' + b.y + '"/>';
      const tagAt = (from, to, txt, cls2) => { const dx = to.x - from.x, dy = to.y - from.y, L = Math.hypot(dx, dy) || 1; const nx = -dy / L, ny = dx / L; const x = from.x + dx / L * 46 + nx * 9, y = from.y + dy / L * 46 + ny * 9; svg += '<text class="ptag ' + cls2 + '" x="' + x + '" y="' + (y + 3) + '" text-anchor="middle">' + esc(txt) + '</text>'; };
      const lab = (p, name) => Stp.shortName(name) + ' ' + (p.errdisabled ? 'ERR' : p.role === 'Root' ? 'R' : p.role === 'Altn' ? 'A' : p.role === 'Desg' ? 'D' : ''); if (pa && (pa.role || pa.errdisabled)) tagAt(a, b, lab(pa, l.ap), pa.state === 'BLK' ? 'blk' : pa.role === 'Root' ? 'root' : ''); else if (l.ap) tagAt(a, b, Stp.shortName(l.ap), ''); if (pb && (pb.role || pb.errdisabled)) tagAt(b, a, lab(pb, l.bp), pb.state === 'BLK' ? 'blk' : pb.role === 'Root' ? 'root' : ''); else if (l.bp) tagAt(b, a, Stp.shortName(l.bp), '');
      if (l.tag) svg += '<text class="ptag" x="' + ((a.x + b.x) / 2) + '" y="' + ((a.y + b.y) / 2 - 6) + '" text-anchor="middle">' + esc(l.tag) + '</text>'; });
    m.nodes.forEach(n => { if (removed(n.id)) return; const c = 'node ' + (n.type === 'rogue' ? 'rogue ' : '') + (nodeCls[n.id] || '') + (r.selected === n.id ? ' sel' : ''); const s = n.small ? 14 : 22; svg += '<g class="' + c + '" data-node="' + n.id + '" transform="translate(' + n.x + ',' + n.y + ')">';
      if (n.type === 'switch' || n.type === 'rogue') svg += '<rect class="body" x="-' + (s + 6) + '" y="-' + (s / 2) + '" width="' + (2 * s + 12) + '" height="' + s + '" rx="3"/><path d="M-12 -3 h8 M-8 -6 l4 3 -4 3 M4 3 h8 M8 0 l-4 3 4 3" stroke="currentColor" fill="none" stroke-width="1.2" style="color:var(--cyan2)"/>';
      else if (n.type === 'router') svg += '<circle class="body" r="' + s + '"/><path d="M-10 0 h20 M4 -6 l6 6 -6 6 M-4 -6 l-6 6 6 6" stroke="var(--cyan2)" fill="none" stroke-width="1.5"/>';
      else if (n.type === 'pc' || n.type === 'host') svg += '<rect class="body" x="-' + s + '" y="-' + (s * .7) + '" width="' + (2 * s) + '" height="' + (s * 1.2) + '" rx="2"/><rect x="-' + (s * .4) + '" y="' + (s * .5) + '" width="' + (s * .8) + '" height="3" fill="var(--line)"/>';
      else if (n.type === 'server') svg += '<rect class="body" x="-' + s + '" y="-' + (s * 1.1) + '" width="' + (2 * s) + '" height="' + (s * 2) + '" rx="2"/>'; else svg += '<ellipse class="body" rx="' + (s + 8) + '" ry="' + (s * .7) + '"/>';
      const sub = S && S.hosts[n.id] && S.hosts[n.id].ip ? S.hosts[n.id].ip : ''; svg += '<text y="' + (n.type === 'pc' || n.type === 'host' ? s + 12 : s + 14) + '" text-anchor="middle">' + esc(n.label) + '</text>' + (sub ? '<text class="ptag" y="' + (s + 24) + '" text-anchor="middle">' + esc(sub) + '</text>' : '') + '</g>'; });
    svg += '</svg>'; box.innerHTML = svg + '<div class="legend">LIVE MAP · click a node to select' + (comp ? ' · <b>R</b> root port · <b>D</b> designated · <b>A</b> alternate (blocking) · <b>ERR</b> err-disabled · gold = root bridge' : '') + (S ? ' · dashed = down or blocked · red = needs attention' : '') + '</div>'; }
  function resultView(r){ const res = r.result; const c = Game.classFor(Game.state.rep); return '<div class="panel result"><h2>RUN COMPLETE</h2><div class="big">+' + res.rep + ' REP</div><div class="dim">' + (res.repeat ? 'repeat run · consolidation pays 40%' : 'first clear') + ' · ' + Math.round(res.ms / 1000) + 's' + (res.fails ? ' · ' + res.fails + ' missed attempt' + (res.fails > 1 ? 's' : '') : ' · no misses') + (res.hintedCount ? ' · ' + res.hintedCount + ' hinted step' + (res.hintedCount > 1 ? 's' : '') + ' (no level-up on those)' : ' · no hints. clean.') + '</div>' +
      (res.promoted ? '<div class="mag" style="font-family:var(--disp);font-size:20px;margin-top:10px">▲ PROMOTED · CLASS ' + res.promoted + '</div>' : '') + (res.recruit ? '<div class="good" style="margin-top:8px">' + esc(res.recruit.name) + ' (' + esc(res.recruit.handle) + ') watched you work and asked Dispatch for your handle. They are your crew now. Check CREW.</div>' : '') +
      (res.leveled.length ? '<div class="lvls">' + res.leveled.map(l => '<div><span class="tag new">LEVEL UP</span> ' + esc(SKILLS[l.skill]) + ' → <b>' + Game.LEVEL_NAMES[l.level] + '</b></div>').join('') + '</div>' : '<div class="muted" style="margin-top:8px">no skill levelled this run. clean uses add up across runs: 1 → SYNCED, 3 → WIRED, 6 → BURNED-IN</div>') +
      '<div class="brief" style="text-align:left;margin-top:16px">' + rich(r.job.outro) + '</div><div class="row" style="justify-content:center"><button class="btn mag" data-v="jobs">BACK TO INBOX</button><button class="btn" data-v="stats">SEE STATS</button></div><div class="muted" style="margin-top:8px">now Class ' + c.id + ' · ' + Game.state.rep + ' rep</div></div>'; }

  // ---- deck, key, stats, crew, log --------------------------------------------------------
  function deck(){ const s = Game.state; return '<div class="panel"><h2>DECK · what you can do without help</h2><div class="muted">a skill appears when someone teaches it · it levels only when you use it on a gig with no hint · 1 clean use → SYNCED · 3 → WIRED · 6 → BURNED-IN</div><div class="deck" style="margin-top:12px">' +
      Object.keys(SKILLS).map(k => { const sk = s.skills[k]; const lv = sk ? sk.level : 0; const next = Game.LEVEL_AT[lv + 1]; const pct = sk ? (next ? Math.round(((sk.clean - Game.LEVEL_AT[lv]) / (next - Game.LEVEL_AT[lv])) * 100) : 100) : 0; return '<div class="skill l' + lv + '"><div class="n">' + esc(SKILLS[k]) + '</div><div class="lv">' + (sk && sk.slotted ? Game.LEVEL_NAMES[lv] : 'NOT SLOTTED') + (sk ? ' · ' + sk.clean + ' clean / ' + sk.uses + ' uses' : '') + '</div><div class="bar"><i style="width:' + pct + '%"></i></div></div>'; }).join('') + '</div>' +
      '<h3>SAVE</h3><div class="row"><button class="btn ghost" id="export">EXPORT SAVE</button><button class="btn ghost" id="import">IMPORT SAVE</button><button class="btn ghost" id="wipe" style="border-color:var(--red);color:var(--red)">WIPE</button></div><textarea id="savebox" style="width:100%;height:60px;margin-top:8px;background:#050710;color:var(--ink2);border:1px solid var(--line);font:11px var(--mono)" placeholder="export writes JSON here; paste JSON here then IMPORT"></textarea></div>'; }
  function keyView(){ const jobsHtml = JOBS.map(j => '<div class="keyjob"><h3><span class="cls ' + j.cls + '" style="font-size:10px">' + j.cls + '</span> ' + esc(j.title) + ' <span class="muted">· from ' + esc(NPCS[j.from].name) + '</span></h3>' + j.steps.map((st, i) => '<div class="keystep"><div class="q"><span class="muted">step ' + (i + 1) + ' · ' + esc(SKILLS[st.skill] || st.skill) + '</span><br>' + rich(st.text) + '</div><div class="a"><b>Answer:</b> ' + esc(Game.answerOf(st)).replace(/\n/g, '<br>') + '</div>' + (st.why ? '<div class="w">' + rich(st.why) + '</div>' : '') + '</div>').join('') + '</div>').join('');
    const lvlHtml = STAGES.map(stg => stg.levels.map(l => { const q = (l.beats.find(b => b.k === 'SYNC') || {}).q; if (!q) return ''; return '<div class="keystep"><div class="q"><span class="muted">' + esc(stg.title) + ' · ' + esc(l.title) + ' · ' + esc(NPCS[l.npc].name) + '</span><br>' + rich(q.prompt) + '</div><div class="a"><b>Answer:</b> ' + String.fromCharCode(65 + q.a) + '. ' + esc(q.opts[q.a]) + '</div>' + (q.why ? '<div class="w">' + rich(q.why) + '</div>' : '') + '</div>'; }).join('')).join('');
    return '<div class="panel key"><h2>KEY · every answer, explained slowly</h2><div class="muted">Read this any time. It is a study sheet, not a cheat. It changes nothing in your deck. Inside a gig, the WALK ME THROUGH IT button shows the same text for the step you are on, and that one counts as a hint.</div><h3 style="margin-top:16px;color:var(--cyan)">GIGS</h3>' + jobsHtml + '<h3 style="margin-top:16px;color:var(--cyan)">QUESTIONS PEOPLE ASK YOU IN THE GRID</h3>' + lvlHtml + '</div>'; }
  function statsView(){ const S = Game.stats(); const x = S.extra; const tile = (k, v, cls) => '<div class="tile ' + (cls || '') + '"><div class="v">' + (v == null ? '—' : v) + '</div><div class="k">' + k + '</div></div>'; const acc = a => a == null ? '' : a >= 80 ? 'good' : a >= 60 ? 'warn' : 'bad';
    const spark = (() => { const h = S.repHistory; if (h.length < 2) return '<div class="muted">rep over time appears after a few gigs</div>'; const max = Math.max(...h.map(p => p.rep), 1); const pts = h.map((p, i) => (i / (h.length - 1) * 100).toFixed(1) + ',' + (60 - p.rep / max * 56).toFixed(1)).join(' '); return '<svg class="spark" viewBox="0 0 100 60" preserveAspectRatio="none"><polyline points="' + pts + '" fill="none" stroke="var(--cyan)" stroke-width="1.5"/></svg>'; })();
    const done = x.done === x.jobs && x.jobs > 0;
    return '<div class="panel stats"><h2>STATS · ' + (done ? 'CAMPAIGN COMPLETE · final report' : 'how you are doing') + '</h2><div class="muted">every attempt is timed. misses, hints and walk-throughs are counted. protégé DMs count separately.</div>' +
      '<h3>CAMPAIGN</h3><div class="tiles">' + tile('rep', Game.state.rep) + tile('class', Game.classFor(Game.state.rep).id) + tile('levels synced', x.read + '/' + x.levels) + tile('gigs cleared', x.done + '/' + x.jobs) + tile('play time', S.playTime) + tile('sessions', S.sessions) + '</div>' +
      '<h3>PRACTICUM</h3><div class="tiles">' + tile('step attempts', S.steps.attempts) + tile('accuracy', S.steps.accuracy == null ? null : S.steps.accuracy + '%', acc(S.steps.accuracy)) + tile('first-try rate', S.steps.firstTry == null ? null : S.steps.firstTry + '%', acc(S.steps.firstTry)) + tile('avg time / step', S.steps.avg) + tile('hints + walks', S.steps.hints + S.steps.walks, S.steps.hintRate > 30 ? 'warn' : '') + tile('best streak', S.streak.best, 'good') + '</div>' +
      '<h3>CREW · flash cards</h3><div class="tiles">' + tile('DMs answered', S.dms.asked) + tile('DM accuracy', S.dms.accuracy == null ? null : S.dms.accuracy + '%', acc(S.dms.accuracy)) + tile('timed out', S.dms.timeouts, S.dms.timeouts ? 'bad' : '') + tile('avg response', S.dms.avg) + tile('crew alive', Protege.active(x.roster).length, 'good') + tile('crew lost', Protege.lost(x.roster).length, Protege.lost(x.roster).length ? 'bad' : '') + tile('cards unlocked', x.unlocked + '/' + x.cards) + tile('cards strong', x.retention ? x.retention.strong : 0) + '</div>' +
      '<h3>REP OVER TIME</h3>' + spark + '<h3>SKILLS · weakest first</h3><div class="bars">' + (S.skills.length ? S.skills.map(s => '<div class="b ' + (s.accuracy != null && s.accuracy < 60 ? 'low' : s.accuracy != null && s.accuracy < 80 ? 'mid' : '') + '"><span>' + esc(s.name) + '</span><div class="bar"><i style="width:' + (s.accuracy || 0) + '%"></i></div><span class="muted">' + (s.accuracy == null ? '—' : s.accuracy + '%') + ' · ' + s.attempts + ' tries' + (s.hints ? ' · ' + s.hints + ' hints' : '') + '</span></div>').join('') : '<div class="muted">no attempts yet</div>') + '</div>' +
      (S.weak.length ? '<h3>WORK ON</h3><div class="dim">' + S.weak.map(s => esc(s.name) + ' (' + s.accuracy + '%)').join(' · ') + '</div>' : '') +
      '<h3>BY STEP TYPE</h3><table><tr><th>type</th><th>attempts</th><th>accuracy</th><th>avg time</th></tr>' + S.types.map(t => '<tr><td>' + t.type + '</td><td>' + t.attempts + '</td><td>' + (t.accuracy == null ? '—' : t.accuracy + '%') + '</td><td>' + S.fmt(t.avgMs) + '</td></tr>').join('') + '</table>' +
      '<h3>GIGS</h3><table><tr><th>gig</th><th>runs</th><th>best time</th><th>misses</th><th>hints</th></tr>' + JOBS.map(j => { const b = S.jobs.byJob[j.id]; return b ? '<tr><td>' + esc(j.title) + '</td><td>' + b.finished + '/' + b.runs + '</td><td>' + S.fmt(b.bestMs) + '</td><td>' + b.fails + '</td><td>' + b.hints + '</td></tr>' : ''; }).join('') + '</table></div>'; }
  function crewView(){ const s = Game.state; const dm = Game.dm.pending(); const R = s.roster;
    return '<div class="panel"><h2>CREW · the kids who look up to you</h2><div class="muted">They get sent on their own gigs. When they get stuck they DM you. Every DM is a flash card. Answer right, in time, and they get through. Answer wrong or late and it goes badly for them, and for your rep. Three strikes and the client does not let them leave.</div>' +
      (dm ? '<div class="panel" style="border-color:var(--mag);margin-top:12px"><b class="mag">DM waiting</b> from ' + esc((R.list.find(p => p.id === dm.protege) || {}).name) + '. <button class="btn mag" id="opendm">OPEN IT</button> <span class="muted">' + dm.seconds + ' seconds on the clock once it is open</span></div>' : (Protege.active(R).length ? '<div class="muted" style="margin-top:10px">no DM right now. ' + (Game.allCards().filter(Game.cardUnlocked).length ? 'one arrives when a card is due.' : 'cards unlock as you talk to people in the Grid.') + (P().dev ? ' <button class="btn ghost" id="forcedm">force a DM (dev)</button>' : '') + '</div>' : '<div class="muted" style="margin-top:10px">nobody yet. finish your first gig and someone will ask Dispatch for your handle.</div>')) +
      '<h3>ROSTER</h3>' + (R.list.length ? '<div class="crewgrid">' + R.list.map(p => '<div class="pcard ' + (p.status === 'flatlined' ? 'flat' : '') + '">' + pSlot(p, 56) + '<div><div class="n">' + esc(p.name) + ' <span class="muted">' + esc(p.handle) + '</span></div><div class="h">' + (p.lineage ? 'orphan of ' + esc((R.list.find(x => x.id === p.lineage) || {}).name || '?') + ' · ' : '') + esc(p.recruitReason || '') + '</div><div class="d">' + (p.status === 'flatlined' ? '<span class="bad">flatlined</span>' : '<span class="dots">' + [0, 1, 2].map(i => '<i class="' + (i < p.danger ? 'on' : '') + '"></i>').join('') + '</span> ' + (p.danger === 0 ? 'fine' : p.danger === 1 ? 'under pressure' : 'in real trouble')) + ' · saved ' + p.saved + ' · failed ' + p.failed + '</div></div></div>').join('') + '</div>' : '') +
      '<h3>MESSAGES</h3><div class="dmlog">' + (s.dmLog.length ? s.dmLog.map(m => '<div class="item"><div class="row1"><span>' + esc(m.name) + ' · ' + new Date(m.t).toLocaleString() + '</span><span class="' + (m.ok ? 'good' : 'bad') + '">' + (m.ok ? 'saved' : m.timedOut ? 'too late' : 'wrong') + ' · ' + (m.repDelta >= 0 ? '+' : '') + m.repDelta + ' rep' + (m.flatlined ? ' · FLATLINED' : '') + '</span></div><div><b>' + esc(m.q) + '</b>' + (m.opts ? '<br><span class="muted">answer: ' + esc(m.opts[m.correct]) + (m.chosen != null && m.chosen !== m.correct ? ' · you said: ' + esc(m.opts[m.chosen]) : '') + '</span>' : '') + '</div><div class="t">' + esc(m.text) + '</div>' + (m.why && !m.ok ? '<div class="why">' + rich(m.why) + '</div>' : '') + '</div>').join('') : '<div class="muted">no messages yet</div>') + '</div></div>'; }
  function logView(){ return '<div class="panel"><h2>LOG</h2><div class="log">' + (Game.state.log.length ? Game.state.log.map(l => '<div><time>' + new Date(l.t).toLocaleString() + '</time>' + esc(l.s) + '</div>').join('') : '<div class="muted">nothing yet.</div>') + '</div></div>'; }

  // ---- DM overlay -------------------------------------------------------------------------
  function dmOverlay(){ const dm = Game.dm.pending(); const res = cur.dmResult; if (!dm && !res) return '';
    if (res) return '<div class="dm-back"><div class="dm"><div class="from">' + pSlot(res.protege, 48) + '<div><div class="n">' + esc(res.protege.name) + '</div><div class="s">' + esc(res.protege.handle) + '</div></div></div><div class="result ' + (res.out.flatlined ? 'flat' : res.ok ? 'good' : 'bad') + '">' + esc(res.out.text) + (res.out.orphan ? '\n\n' + esc(Protege.fill((PROTEGE_LINES.orphan || [])[0] || '{name} joined your crew.', res.out.orphan)) : '') + '</div>' + (!res.ok ? '<div class="why"><b>The answer was: ' + esc(res.answerText) + '</b>' + (res.why ? '<br>' + rich(res.why) : '') + '</div>' : '') + '<div class="muted" style="margin-top:8px">' + (res.out.repDelta >= 0 ? '+' : '') + res.out.repDelta + ' rep' + (res.promoted ? ' · promoted to Class ' + res.promoted : '') + '</div><div class="row" style="margin-top:10px"><button class="btn" id="dmclose">CLOSE</button></div></div></div>';
    const p = Game.state.roster.list.find(x => x.id === dm.protege); const opened = !!dm.openedAt; const rem = Game.dm.remaining(); const pct = opened ? Math.round(100 * rem / (dm.seconds * 1000)) : 100;
    return '<div class="dm-back"><div class="dm"><div class="from">' + pSlot(p, 48) + '<div><div class="n">' + esc(p.name) + '</div><div class="s">' + esc(p.handle) + ' · <span class="danger d' + p.danger + '">' + (p.danger === 0 ? 'fine' : p.danger === 1 ? 'under pressure' : 'in real trouble') + '</span></div></div></div>' +
      '<div class="msg">' + esc(dm.open) + '</div>' + (opened ? '<div class="q">' + esc(dm.q) + '</div><div class="opts">' + (dm.opts || []).map((o, i) => '<button data-dmans="' + i + '">' + String.fromCharCode(65 + i) + '. ' + esc(o) + '</button>').join('') + '</div><div class="timer' + (pct < 30 ? ' hot' : '') + '"><i id="dmbar" style="width:' + pct + '%"></i></div><div class="secs" id="dmsecs">' + Math.ceil(rem / 1000) + 's</div>' : '<div class="muted">' + dm.seconds + ' seconds once you open it. no pausing.</div><div class="row" style="margin-top:10px"><button class="btn mag" id="dmopen">READ IT</button><button class="btn ghost" id="dmlater">LATER</button></div>') + '</div></div>'; }
  function dmTick(){ const dm = Game.dm.pending(); if (!dm || !dm.openedAt) return; const rem = Game.dm.remaining(); const bar = $('#dmbar'), secs = $('#dmsecs'); if (bar) bar.style.width = Math.round(100 * rem / (dm.seconds * 1000)) + '%'; if (secs) secs.textContent = Math.ceil(rem / 1000) + 's'; if (rem <= 0) { cur.dmResult = Game.dm.timeout(); toast('TOO LATE · ' + cur.dmResult.protege.name, 'mag'); render(); } }
  setInterval(dmTick, 250);

  // ---- dev panel -------------------------------------------------------------------------
  function devPanel(){ if (!P().dev || !cur.devOpen) return ''; let body = ''; const tabs = [['lint', 'LINT'], ['step', 'STEP'], ['net', 'NET'], ['golden', 'GOLDEN'], ['cards', 'CARDS']]; const lint = Game.dev.lint();
    if (cur.dev === 'lint') body = (lint.errors.map(e => '<div class="err">ERROR ' + esc(e.where) + ' — ' + esc(e.msg) + '</div>').join('') || '<div class="ok">no errors</div>') + lint.warnings.map(w => '<div class="warn">warn ' + esc(w.where) + ' — ' + esc(w.msg) + '</div>').join('') + '<div style="margin-top:6px">counts: ' + esc(Object.entries(lint.coverage.counts).map(([k, v]) => k + ' ' + v).join(' · ')) + '<br>days without a level: ' + esc(lint.coverage.missingDays.join(',') || 'none') + '</div>';
    if (cur.dev === 'step') { const d = Game.dev.stepDiag(); body = d ? '<div>step ' + d.step + ' · ' + d.type + ' · ' + d.skill + ' → <b class="' + (d.ok ? 'ok' : 'err') + '">' + (d.ok ? 'WOULD PASS' : 'would fail') + '</b> ' + esc(d.why || '') + '</div>' + (d.err ? '<div class="err">' + esc(d.err) + '</div>' : '') + (d.need ? '<div>need:</div>' + d.need.map(n => '<div class="' + (n.satisfied ? 'ok' : 'err') + '">  ' + (n.satisfied ? '✓' : '✗') + ' ' + esc(n.dev) + ' mode=' + esc(n.mode) + ' ctx=' + esc(n.ctx) + ' line=' + esc(n.line) + '</div>').join('') : '') + (d.check ? '<div>check: <span class="muted">' + esc(d.check) + '</span></div>' : '') + (d.issues && d.issues.length ? '<div class="warn">net issues: ' + esc(d.issues.map(i => i.kind + ' @ ' + i.where).join(' | ')) + '</div>' : '') : '<div class="muted">not in a run</div>'; }
    if (cur.dev === 'net') { const S = Game.dev.netState(); body = S ? '<div>ping <input id="devfrom" placeholder="from (PC1)" size="8"> → <input id="devto" placeholder="ip" size="14"> <button class="act" id="devping">PING</button> <span id="devpingres"></span></div><div>hosts: ' + esc(JSON.stringify(Object.fromEntries(Object.entries(S.hosts).map(([k, h]) => [k, { ip: h.ip, gw: h.gw, up: h.up, rogue: h.rogue }])))) + '</div>' + Object.keys(S.tables).map(r => '<div><b>' + r + '</b> ' + esc(S.tables[r].map(e => e.proto + ' ' + e.prefix + '/' + e.len + (e.via ? ' via ' + e.via : ' ' + e.iface)).join(' | ')) + '</div>').join('') + (S.issues.length ? '<div class="warn">issues: ' + esc(S.issues.map(i => i.kind + ' @ ' + i.where).join(' | ')) + '</div>' : '<div class="ok">no issues</div>') + '<div>threats: ' + esc(JSON.stringify(S.threats)) + '</div>' : '<div class="muted">no net in this run (STP-only topo or no run)</div>'; }
    if (cur.dev === 'golden') { body = '<div>' + JOBS.map(j => '<button class="act" data-golden="' + j.id + '">' + esc(j.id) + '</button>').join(' ') + '</div><div id="goldenres" style="margin-top:6px">' + (cur.goldenRes ? goldenHtml(cur.goldenRes) : 'click a gig to play its golden solution headless') + '</div>'; }
    if (cur.dev === 'cards') { const all = Game.allCards(); const un = all.filter(Game.cardUnlocked); body = '<div>' + all.length + ' cards, ' + un.length + ' unlocked, ' + SRS.due(all, Game.state.cards, Game.cardUnlocked, Date.now()).length + ' due now · <button class="act" id="forcedm">FORCE DM</button></div>' + un.slice(0, 40).map(c => '<div>' + esc(c.id) + ' [' + esc(c.skill || c.level) + '] ' + esc(c.q).slice(0, 90) + (Game.state.cards[c.id] ? ' <span class="muted">box ' + Game.state.cards[c.id].box + '</span>' : '') + '</div>').join(''); }
    return '<div class="devbar"><div class="tabs">' + tabs.map(([k, l]) => '<button data-devtab="' + k + '" class="' + (cur.dev === k ? 'on' : '') + '">' + l + '</button>').join('') + '<span class="sp"></span>' + (lint.errors.length ? '<span class="cnt">' + lint.errors.length + ' lint errors</span>' : '') + '<button data-devtab="close">✕</button></div><div class="body">' + body + '</div></div>'; }
  function goldenHtml(r){ return '<div class="' + (r.ok ? 'ok' : 'err') + '">' + esc(r.job) + ': ' + (r.ok ? 'PASS' : 'FAIL — ' + esc(r.error)) + '</div>' + r.steps.map(s => '<div class="' + (s.ok ? 'ok' : 'err') + '">  step ' + (s.i + 1) + ' ' + s.type + ' ' + s.skill + ' ' + (s.ok ? '✓' : '✗ ' + esc(s.why || '')) + '</div>').join('') + r.warnings.map(w => '<div class="warn">  ⚠ ' + esc(w) + '</div>').join('') + (r.console ? Object.entries(r.console).map(([d, t]) => '<div class="muted">[' + d + '] ' + esc(t) + '</div>').join('') : ''); }
  window.addEventListener('error', e => { const b = document.createElement('div'); b.className = 'errbanner'; b.textContent = 'JS error: ' + e.message + ' (' + (e.filename || '').split('/').pop() + ':' + e.lineno + ')'; document.body.appendChild(b); setTimeout(() => b.remove(), 12000); });

  // ---- render ---------------------------------------------------------------------------------
  function render(){ const s = Game.state; const a = app(); document.body.classList.toggle('devon', !!(P().dev && cur.devOpen));
    if (!s.handle) { a.innerHTML = intro(); $('#go').onclick = () => { if (Game.setHandle($('#handle').value)) { view = 'home'; render(); } }; $('#handle').onkeydown = e => { if (e.key === 'Enter') $('#go').click(); }; a.querySelectorAll('[data-resume]').forEach(b => b.onclick = () => { Game.setHandle(b.dataset.resume); view = 'home'; render(); }); const si = $('#signin'); if (si) si.onclick = () => Auth.signIn(Auth.providers[0]); $('#handle').focus(); return; }
    if (view !== 'run') Game.dm.maybeCreate();
    let body = ''; if (view === 'home') body = home(); else if (view === 'grid') body = grid(); else if (view === 'level') body = level(); else if (view === 'jobs') body = jobs(); else if (view === 'run') body = runView(); else if (view === 'deck') body = deck(); else if (view === 'key') body = keyView(); else if (view === 'stats') body = statsView(); else if (view === 'crew') body = crewView(); else body = logView();
    a.innerHTML = hud() + body + dmOverlay() + devPanel();
    a.querySelectorAll('.npcslot').forEach(sl => { if (sl.dataset.protege) { const p = Game.state.roster.list.find(x => x.id === sl.dataset.protege) || (cur.dmResult && cur.dmResult.protege); sl.replaceWith(npcEl(null, +sl.dataset.size, p ? p.look : { seed: 'p' })); } else sl.replaceWith(npcEl(sl.dataset.npc, +sl.dataset.size)); });
    if (view === 'run' && Game.run && !Game.run.result) { drawMap(); const o = $('#conout'); if (o) o.scrollTop = o.scrollHeight; const inp = $('#conin'); if (inp && !Game.dm.pending()) inp.focus(); }
    window.scrollTo({ top: (view === 'run' && lastView === 'run') ? window.scrollY : 0 }); lastView = view; }
  setInterval(() => { const r = Game.run; const el = $('#runclock'); if (r && el && !r.result) { const s = Math.floor((Date.now() - r.startedAt) / 1000); el.textContent = String(Math.floor(s / 60)).padStart(2, '0') + ':' + String(s % 60).padStart(2, '0'); } }, 1000);

  document.addEventListener('click', e => {
    const t = e.target.closest('[data-v],[data-stage],[data-level],[data-job],[data-start],[data-opt],[data-choice],[data-multi],[data-up],[data-down],[data-dev],[data-node],[data-dmans],[data-devtab],[data-golden],#next,#prev,#finish,#commit,#hint,#walk,#abort,#export,#import,#wipe,#logout,#signin,#signout,#devtoggle,#opendm,#dmopen,#dmlater,#dmclose,#forcedm,#devping'); if (!t) return;
    if (t.id === 'logout') { if (view === 'run' && Game.run && !Game.run.result && !confirm('Jack out? Progress on this gig is lost.')) return; Game.logout(); view = 'home'; cur = Object.assign(cur, { stage: null, level: null, beat: 0, job: null, synced: null }); return render(); }
    if (t.id === 'signin') { Auth.signIn(Auth.providers[0]).catch(err => toast('sign-in failed: ' + err.message, 'mag')); return; } if (t.id === 'signout') { Auth.signOut().then(render); return; }
    if (t.id === 'devtoggle') { cur.devOpen = !cur.devOpen; return render(); } if (t.dataset.devtab) { if (t.dataset.devtab === 'close') cur.devOpen = false; else cur.dev = t.dataset.devtab; return render(); }
    if (t.dataset.golden) { cur.goldenRes = Game.runSolution(t.dataset.golden); return render(); } if (t.id === 'devping') { const r = Game.dev.ping($('#devfrom').value.trim(), $('#devto').value.trim()); $('#devpingres').textContent = r ? (r.ok ? 'OK ' : 'FAIL ') + r.reason + ' · ' + r.path.map(p => p.dev + ':' + p.act).join(' → ') : 'no net'; return; }
    if (t.id === 'opendm' || t.id === 'dmopen') { Game.dm.open(); return render(); } if (t.id === 'dmlater') { view = view === 'crew' ? 'home' : view; return render(); } if (t.id === 'forcedm') { Game.dm.maybeCreate(true); return render(); }
    if (t.dataset.dmans) { cur.dmResult = Game.dm.answer(+t.dataset.dmans); if (cur.dmResult) { toast(cur.dmResult.ok ? 'SAVED · ' + cur.dmResult.protege.name : cur.dmResult.out.flatlined ? 'FLATLINED · ' + cur.dmResult.protege.name : 'WRONG · ' + cur.dmResult.protege.name, cur.dmResult.ok ? 'grn' : 'mag'); } return render(); }
    if (t.id === 'dmclose') { cur.dmResult = null; return render(); }
    if (t.dataset.v) { if (view === 'run' && Game.run && !Game.run.result && t.dataset.v !== 'run') { if (!confirm('Jack out? Progress on this gig is lost.')) return; Game.abort(); } view = t.dataset.v; if (view === 'jobs' && Game.run && Game.run.result) Game.abort(); return render(); }
    if (t.dataset.stage) { cur.stage = t.dataset.stage; return render(); } if (t.dataset.level) { cur.level = t.dataset.level; cur.beat = 0; cur.synced = null; cur.stage = Game.stageOf(cur.level).id; view = 'level'; return render(); }
    if (t.dataset.job) { cur.job = t.dataset.job; return render(); } if (t.dataset.start) { Game.startJob(t.dataset.start); view = 'run'; return render(); } if (t.dataset.opt) { cur.synced = +t.dataset.opt; return render(); }
    if (t.id === 'next') { cur.beat++; cur.synced = null; return render(); } if (t.id === 'prev') { cur.beat--; cur.synced = null; return render(); } if (t.id === 'finish') { const first = Game.readLevel(cur.level); if (first) toast('SYNCED · ' + Game.levelById(cur.level).title + ' · skills slotted'); view = 'grid'; return render(); }
    if (t.dataset.choice) { Game.run.choice = +t.dataset.choice; return render(); } if (t.dataset.multi) { const i = +t.dataset.multi; if (Game.run.multi.has(i)) Game.run.multi.delete(i); else Game.run.multi.add(i); return render(); }
    if (t.dataset.up) { const i = +t.dataset.up; const o = Game.run.order; [o[i - 1], o[i]] = [o[i], o[i - 1]]; return render(); } if (t.dataset.down) { const i = +t.dataset.down; const o = Game.run.order; [o[i + 1], o[i]] = [o[i], o[i + 1]]; return render(); }
    if (t.dataset.dev) { Game.run.active = t.dataset.dev; return render(); } if (t.dataset.node) { Game.run.selected = t.dataset.node; Game.run.feedback = null; return render(); }
    if (t.id === 'commit') { const r = Game.run; const stBefore = Game.currentStep(); if (stBefore.type === 'calc') document.querySelectorAll('[data-calc]').forEach(i => r.calc[i.dataset.calc] = i.value); if (stBefore.type === 'form') document.querySelectorAll('[data-form]').forEach(i => r.form[i.dataset.form] = i.value); if (stBefore.type === 'text') { const ta = document.querySelector('[data-text]'); if (ta) r.text = ta.value; }
      const res = Game.commit(); if (res.ok) { toast(res.finished ? 'GIG COMPLETE' : 'STEP CLEARED', 'grn'); if (r.feedback && r.feedback.leveled) toast('LEVEL UP · ' + SKILLS[r.feedback.leveled.skill] + ' → ' + Game.LEVEL_NAMES[r.feedback.leveled.level], 'mag'); if (res.result && res.result.promoted) toast('PROMOTED · CLASS ' + res.result.promoted, 'yel'); } return render(); }
    if (t.id === 'hint') { Game.run.hintShown = Game.useHint(); return render(); } if (t.id === 'walk') { Game.run.walk = Game.reveal(); return render(); }
    if (t.id === 'abort') { if (confirm('Jack out? Progress on this gig is lost.')) { Game.abort(); view = 'jobs'; render(); } return; }
    if (t.id === 'export') { $('#savebox').value = Game.exportSave(); return; } if (t.id === 'import') { if (Game.importSave($('#savebox').value)) { toast('SAVE IMPORTED'); render(); } else toast('bad save JSON', 'mag'); return; } if (t.id === 'wipe') { if (confirm('Wipe all progress for this handle?')) { Game.reset(); render(); } return; }
  });
  document.addEventListener('keydown', e => { const inp = e.target; if (!inp || inp.id !== 'conin') return; const r = Game.run; if (!r) return; const d = r.devices[r.active];
    if (e.key === 'Enter') { const raw = inp.value; r.history.push(raw); r.hIdx = r.history.length; d.exec(raw, r.devices); inp.value = ''; const o = $('#conout'); o.innerHTML = d.out.map(x => '<div class="' + x.t + '">' + esc(x.s) + '</div>').join(''); o.scrollTop = o.scrollHeight; $('#prompt').textContent = d.prompt(); document.querySelector('.console .devs .muted').textContent = d.prompt(); drawMap(); if (cur.devOpen) { const dp = document.querySelector('.devbar'); if (dp) dp.outerHTML = devPanel(); } }
    if (e.key === 'ArrowUp') { r.hIdx = Math.max(0, (r.hIdx == null ? r.history.length : r.hIdx) - 1); inp.value = r.history[r.hIdx] || ''; e.preventDefault(); } if (e.key === 'ArrowDown') { r.hIdx = Math.min(r.history.length, (r.hIdx == null ? r.history.length : r.hIdx) + 1); inp.value = r.history[r.hIdx] || ''; e.preventDefault(); } if (e.key === 'Tab') e.preventDefault(); });
  document.addEventListener('input', e => { const r = Game.run; if (!r || !e.target.dataset) return; if (e.target.dataset.calc) r.calc[e.target.dataset.calc] = e.target.value; if (e.target.dataset.form) r.form[e.target.dataset.form] = e.target.value; if (e.target.dataset.text) r.text = e.target.value; });

  window.UI = { render, toast, go: v => { view = v; render(); } };
  document.addEventListener('DOMContentLoaded', () => { if (window.Auth) Auth.init(window.PLATFORM); render(); });
})();
