/* engine/show.js — renders IOS-style `show` output from Net state. Sim falls back to this for any show
   command a job did not hard-code. Also the host (PC) console commands. */
(function(){
  const S_ = Net.short; const pad = (s, n) => String(s).padEnd(n); const IP = Sim.ip;
  const R = {};

  R['show ip interface brief'] = (d, S) => { const rows = Object.values(S.ifaces[d.name] || {}).filter(i => !(i.kind === 'vlan' && !i.cfg.ip && i.name !== 'vlan1')).sort((a, b) => a.name.localeCompare(b.name, undefined, { numeric: true }));
    return 'Interface              IP-Address      OK? Method Status                Protocol\n' + rows.map(i => pad(long(i.name), 23) + pad(i.cfg.ip || 'unassigned', 16) + 'YES ' + pad(i.cfg.ip ? 'manual' : 'unset', 7) + pad(i.admin ? (i.up ? 'up' : 'down') : 'administratively down', 22) + (i.up ? 'up' : 'down')).join('\n'); };
  R['show ip route'] = (d, S) => { const t = S.tables[d.name]; if (!t) return '% IP routing is not enabled on ' + d.name;
    const codes = 'Codes: L - local, C - connected, S - static, R - RIP, D - EIGRP, O - OSPF, O IA - OSPF inter area, O*E2 - OSPF external default, * - candidate default\n';
    const gw = t.find(e => e.len === 0); return codes + '\nGateway of last resort is ' + (gw ? (gw.via || 'directly connected') + ' to network 0.0.0.0' : 'not set') + '\n\n' + t.map(e => pad(e.proto, 6) + e.prefix + '/' + e.len + (e.via ? ' [' + e.ad + '/' + e.metric + '] via ' + e.via + ', ' + long(e.iface) : ' is directly connected, ' + long(e.iface))).join('\n'); };
  R['show ip ospf neighbor'] = (d, S) => { const n = S.ospf.neighbors[d.name] || []; if (!S.cfg[d.name].ospf) return '% OSPF: No router process'; return 'Neighbor ID     Pri   State           Dead Time   Address         Interface\n' + n.map(x => pad(x.id, 16) + pad(x.pri != null ? x.pri : 1, 6) + pad(x.state + '/' + (x.role === '-' ? ' -' : x.role || 'DR'), 16) + pad('00:00:35', 12) + pad(x.ip, 16) + long(x.iface)).join('\n') + (n.length ? '' : '(no neighbors)'); };
  R['show ip ospf interface brief'] = (d, S) => { const o = S.ospf.routers[d.name]; if (!o) return '% OSPF: No router process'; return 'Interface    PID   Area            IP Address/Mask    Cost  State Nbrs F/C\n' + o.ifaces.map(i => { const a = S.l3.find(x => x.dev === d.name && x.iface === i.iface); const nb = (S.ospf.neighbors[d.name] || []).filter(n => n.iface === i.iface); const role = S.ospf.roleOf ? S.ospf.roleOf(d.name, i.iface) : 'DR'; return pad(S_(i.iface), 13) + pad(S.cfg[d.name].ospf.pid, 6) + pad(i.area, 16) + pad((a ? a.ip : '') + '/' + i.len, 19) + pad(i.cost, 6) + pad(role === 'DROTHER' ? 'DROTH' : role, 6) + nb.filter(n => n.state === 'FULL').length + '/' + nb.length; }).join('\n'); };
  R['show ip protocols'] = (d, S) => { const c = S.cfg[d.name]; const out = []; if (c.ospf) { const o = S.ospf.routers[d.name]; out.push('Routing Protocol is "ospf ' + c.ospf.pid + '"', '  Router ID ' + (o ? o.id : '0.0.0.0'), '  Routing for Networks:'); c.ospf.networks.forEach(n => out.push('    ' + n.addr + ' ' + n.wild + ' area ' + n.area)); out.push('  Passive Interface(s):'); (o ? o.ifaces : []).filter(i => i.passive).forEach(i => out.push('    ' + long(i.iface))); out.push('  Distance: (default is 110)'); }
    if (c.rip) out.push('Routing Protocol is "rip"', '  Version ' + (c.rip.v2 ? 2 : 1), '  Routing for Networks: ' + c.rip.networks.join(', '), '  Distance: (default is 120)'); if (c.eigrp) out.push('Routing Protocol is "eigrp ' + c.eigrp.as + '"', '  Routing for Networks: ' + c.eigrp.networks.map(n => n.addr + (n.wild ? ' ' + n.wild : '')).join(', '), '  Distance: internal 90 external 170'); return out.length ? out.join('\n') : '% No routing protocols configured'; };
  R['show standby brief'] = (d, S) => { const rows = []; for (const k in S.hsrp) { const g = S.hsrp[k]; g.members.forEach(m => { if (m.dev !== d.name) return; const role = g.active.dev === d.name ? 'Active' : g.standby && g.standby.dev === d.name ? 'Standby' : 'Listen'; rows.push(pad(S_(m.iface), 12) + pad(g.group, 6) + pad(m.priority, 5) + pad(m.preempt ? 'P' : '', 3) + pad(role, 8) + pad(g.active.dev === d.name ? 'local' : g.active.ip, 16) + pad(g.standby ? (g.standby.dev === d.name ? 'local' : g.standby.ip) : 'unknown', 16) + g.vip); }); }
    return '                     P indicates configured to preempt.\nInterface   Grp  Pri P State   Active          Standby         Virtual IP\n' + (rows.join('\n') || '(no HSRP groups)'); };
  R['show access-lists'] = (d, S) => { const a = S.cfg[d.name].acls; const ks = Object.keys(a); if (!ks.length) return '(no access lists)'; return ks.map(k => (a[k].type === 'standard' ? 'Standard' : 'Extended') + ' IP access list ' + k + '\n' + a[k].entries.map(e => '    ' + e.seq + ' ' + e.action + ' ' + (a[k].type === 'standard' ? (e.swild === '0.0.0.0' ? 'host ' + e.src : e.swild === '255.255.255.255' ? 'any' : e.src + ', wildcard bits ' + e.swild) : e.raw)).join('\n')).join('\n'); };
  R['show ip access-lists'] = R['show access-lists'];
  R['show ip nat translations'] = (d, S) => { const t = d._natSeen || []; if (!t.length) return 'Pro  Inside global      Inside local       Outside local      Outside global\n(no translations yet — send traffic first, e.g. ping from an inside host)'; return 'Pro  Inside global      Inside local       Outside local      Outside global\n' + t.map(x => pad(x.proto, 5) + pad(x.global + (x.kind === 'pat' ? ':' + x.port : ''), 19) + pad(x.inside + (x.kind === 'pat' ? ':' + x.port : ''), 19) + pad('---', 19) + '---').join('\n'); };
  R['show ip nat statistics'] = (d, S) => { const c = S.cfg[d.name]; const ins = Object.values(S.ifaces[d.name]).filter(i => i.cfg.natInside).map(i => long(i.name)), outs = Object.values(S.ifaces[d.name]).filter(i => i.cfg.natOutside).map(i => long(i.name)); return 'Total active translations: ' + (d._natSeen || []).length + '\nOutside interfaces:\n  ' + (outs.join(', ') || '(none)') + '\nInside interfaces:\n  ' + (ins.join(', ') || '(none)') + '\nDynamic mappings:\n' + c.natDynamic.map(x => '-- Inside Source\n  access-list ' + x.acl + (x.iface ? ' interface ' + x.iface : ' pool ' + x.pool) + (x.overload ? ' overload' : '')).join('\n'); };
  R['show ip dhcp binding'] = (d, S) => { const rows = Object.values(S.hosts).filter(h => h.lease && h.lease.ok && h.server === d.name); return 'IP address       Client-ID/Hardware address   Lease expiration        Type\n' + (rows.map(h => pad(h.ip, 17) + pad(h.mac, 29) + pad('Sep 28 2026 10:00 AM', 24) + 'Automatic').join('\n') || '(no bindings)'); };
  R['show ip dhcp pool'] = (d, S) => { const p = S.cfg[d.name].dhcp.pools; return Object.values(p).map(x => 'Pool ' + x.name + ' :\n Network: ' + x.network + ' ' + x.mask + '\n Default router: ' + (x.router || '-') + '\n DNS: ' + (x.dns.join(' ') || '-')).join('\n') || '(no pools)'; };
  R['show ip dhcp snooping'] = (d, S) => { const c = S.cfg[d.name].dhcp; const trusted = Object.values(S.ifaces[d.name]).filter(i => i.cfg.snoopTrust); return 'Switch DHCP snooping is ' + (c.snooping ? 'enabled' : 'disabled') + '\nDHCP snooping is configured on following VLANs:\n' + ([...c.snoopVlans].join(',') || 'none') + '\nInterface                  Trusted    Rate limit (pps)\n' + (trusted.map(i => pad(long(i.name), 27) + 'yes        unlimited').join('\n') || '(no trusted interfaces)'); };
  R['show ip dhcp snooping binding'] = (d, S) => { const rows = Object.values(S.hosts).filter(h => h.lease && h.lease.ok && !h.rogue); return 'MacAddress          IpAddress        Lease(sec)  Type           VLAN  Interface\n' + (rows.map(h => pad(h.mac, 20) + pad(h.ip, 17) + pad('86400', 12) + pad('dhcp-snooping', 15) + pad('1', 6)).join('\n') || '(empty)'); };
  R['show ip arp inspection'] = (d, S) => { const c = S.cfg[d.name].dhcp; const t = S.threats.arpspoof; return 'Source Mac Validation      : Disabled\nDestination Mac Validation : Disabled\nIP Address Validation      : Disabled\n Vlan     Configuration    Operation   ACL Match\n ----     -------------    ---------   ---------\n' + ([...c.daiVlans].map(v => pad(' ' + v, 10) + pad('Enabled', 17) + (c.snooping ? 'Active' : 'Inactive (needs DHCP snooping)')).join('\n') || ' (no VLANs)') + (t ? '\n\n Vlan   Forwarded   Dropped\n ----   ---------   -------\n    1   ' + pad(t.blocked ? 14 : 22, 12) + (t.blocked ? 8 : 0) : ''); };
  R['show ip arp inspection statistics'] = R['show ip arp inspection'];
  R['show vlan brief'] = (d, S) => { const c = S.cfg[d.name]; const v = Object.assign({ 1: { id: 1, name: 'default' } }, c.vlans); const ports = {}; Object.values(S.ifaces[d.name] || {}).forEach(i => { if (i.kind !== 'gi' && i.kind !== 'fa') return; if (i.trunk) return; (ports[i.vlan] = ports[i.vlan] || []).push(S_(i.name)); });
    return 'VLAN Name                             Status    Ports\n---- -------------------------------- --------- -------------------------------\n' + Object.values(v).sort((a, b) => a.id - b.id).map(x => pad(x.id, 5) + pad(x.name || ('VLAN' + String(x.id).padStart(4, '0')), 33) + 'active    ' + (ports[x.id] || []).join(', ')).join('\n'); };
  R['show interfaces trunk'] = (d, S) => { const tr = Object.values(S.ifaces[d.name] || {}).filter(i => i.trunk && i.up); if (!tr.length) return '(no trunk ports)'; return 'Port        Mode             Encapsulation  Status        Native vlan\n' + tr.map(i => pad(S_(i.name), 12) + pad(i.mode === 'trunk' ? 'on' : 'auto', 17) + pad('802.1q', 15) + pad('trunking', 14) + i.native).join('\n') + '\n\nPort        Vlans allowed on trunk\n' + tr.map(i => pad(S_(i.name), 12) + (i.allowed ? [...i.allowed].sort((a, b) => a - b).join(',') : '1-4094')).join('\n'); };
  R['show interfaces status'] = (d, S) => { const rows = Object.values(S.ifaces[d.name] || {}).filter(i => i.kind === 'gi' || i.kind === 'fa'); return 'Port      Name               Status       Vlan       Duplex  Speed Type\n' + rows.map(i => pad(S_(i.name), 10) + pad((i.cfg.desc || '').slice(0, 18), 19) + pad(i.errdisabled ? 'err-disabled' : !i.admin ? 'disabled' : i.up ? 'connected' : 'notconnect', 13) + pad(i.trunk ? 'trunk' : i.vlan, 11) + pad(i.cfg.duplex || 'a-full', 8) + pad(i.cfg.speed || (i.kind === 'gi' ? 'a-1000' : 'a-100'), 6) + (i.kind === 'gi' ? '10/100/1000BaseTX' : '10/100BaseTX')).join('\n'); };
  R['show mac address-table'] = (d, S) => { const rows = S.macTable[d.name] || []; return '          Mac Address Table\n-------------------------------------------\nVlan    Mac Address       Type        Ports\n----    -----------       --------    -----\n' + (rows.map(r => pad(' ' + r.vlan, 8) + pad(r.mac, 18) + pad('DYNAMIC', 12) + S_(r.port)).join('\n') || '(empty)'); };
  R['show etherchannel summary'] = (d, S) => { const bs = Object.values(S.bundles).filter(g => g.a === d.name || g.b === d.name); if (!bs.length) return 'Number of channel-groups in use: 0\n(no bundles formed — check both sides have channel-group with compatible modes)'; return 'Flags:  D - down  P - bundled in port-channel  U - in use  S - Layer2  L - Layer3\nNumber of channel-groups in use: ' + bs.length + '\nGroup  Port-channel  Protocol    Ports\n------+-------------+-----------+-----------------------------------------------\n' + bs.map(g => { const me = g.a === d.name; const grp = me ? g.ga : g.gb; const ports = g.links.map(L => S_(me ? (L.a === d.name ? L.ap : L.bp) : (L.b === d.name ? L.bp : L.ap)) + '(P)'); const mode = S.ifaces[d.name][me ? (g.links[0].a === d.name ? g.links[0].ap : g.links[0].bp) : (g.links[0].b === d.name ? g.links[0].bp : g.links[0].ap)].cfg.channel.mode; return pad(grp, 7) + pad('Po' + grp + '(SU)', 14) + pad(mode === 'on' ? '-' : ['active', 'passive'].includes(mode) ? 'LACP' : 'PAgP', 12) + ports.join(' '); }).join('\n'); };
  R['show port-security'] = (d, S) => { const rows = Object.keys(S.portsec).filter(k => k.startsWith(d.name + '|')).map(k => [k.split('|')[1], S.portsec[k]]); return 'Secure Port  MaxSecureAddr  CurrentAddr  SecurityViolation  Security Action\n' + (rows.map(([p, s]) => s.rejected ? pad(S_(p), 13) + '(rejected: port is not in access mode)' : pad(S_(p), 13) + pad(s.max, 15) + pad(s.allowed.length + s.learned.length, 13) + pad(s.violations, 19) + s.violation).join('\n') || '(no secure ports)'); };
  R['show port-security address'] = (d, S) => { const rows = Object.keys(S.portsec).filter(k => k.startsWith(d.name + '|')).flatMap(k => { const s = S.portsec[k]; if (s.rejected) return []; const p = k.split('|')[1]; return [...s.allowed.map(m => [m, 'SecureConfigured', p]), ...s.learned.map(m => [m, s.sticky ? 'SecureSticky' : 'SecureDynamic', p])]; }); return 'Vlan    Mac Address       Type                Ports\n' + (rows.map(([m, t, p]) => pad(' 1', 8) + pad(m, 18) + pad(t, 20) + S_(p)).join('\n') || '(none)'); };
  R['show ipv6 interface brief'] = (d, S) => { const rows = Object.values(S.ifaces[d.name] || {}).filter(i => i.cfg.ipv6.length || i.cfg.ipv6Enable); if (!rows.length) return '(no IPv6 interfaces)'; return rows.map(i => long(i.name) + '       [' + (i.up ? 'up/up' : 'down/down') + ']\n    ' + (i.cfg.ipv6LinkLocal || Net.eui64('FE80::', Net.synthMac(d.name + i.name)).toUpperCase()) + '\n' + i.cfg.ipv6.map(a => '    ' + (a.eui64 ? Net.eui64(a.addr, Net.synthMac(d.name + i.name)) : a.addr).toUpperCase()).join('\n')).join('\n'); };
  R['show ipv6 route'] = (d, S) => { const t = S.tables6[d.name]; if (!t) return '% IPv6 routing not enabled'; if (!S.cfg[d.name].ipv6Routing) return 'IPv6 Routing Table - default\n(ipv6 unicast-routing is not enabled — this box will not forward IPv6)\n' + t.map(e => e.proto + '   ' + e.prefix + '/' + e.len + (e.via ? ' via ' + e.via : ' via ' + long(e.iface) + ', directly connected')).join('\n'); return 'IPv6 Routing Table - default\nCodes: C - Connected, L - Local, S - Static\n' + t.map(e => e.proto + '   ' + e.prefix + '/' + e.len + (e.via ? ' [' + e.ad + '/0]\n     via ' + e.via : '\n     via ' + long(e.iface) + ', directly connected')).join('\n'); };
  R['show ip ssh'] = (d, S) => { const c = S.cfg[d.name]; return c.sshKeyBits ? 'SSH Enabled - version ' + (c.sshVersion || '1.99') + '\nAuthentication timeout: 120 secs; Authentication retries: 3\nMinimum expected Diffie Hellman key size : 1024 bits\nIOS Keys in SECSH format(ssh-rsa, base64 encoded): ' + (c.hostname || d.name) + '.' + (c.domain || '?') : 'SSH Disabled - version 1.99\n%Please create RSA keys to enable SSH (and of atleast 768 bits for SSH v2).\nAuthentication timeout: 120 secs; Authentication retries: 3'; };
  R['show cdp neighbors'] = (d, S) => { if (!S.cfg[d.name].cdp) return '% CDP is not enabled'; const n = (S.neighbors[d.name] || []).filter(x => x.cdp); return 'Capability Codes: R - Router, S - Switch, I - IGMP\n\nDevice ID        Local Intrfce     Holdtme    Capability  Platform  Port ID\n' + (n.map(x => pad(x.dev, 17) + pad(S_(x.local), 18) + pad('150', 11) + pad(x.platform.includes('ISR') ? 'R' : 'S I', 12) + pad(x.platform.replace('cisco ', ''), 10) + S_(x.remote)).join('\n') || '(no neighbors)'); };
  R['show cdp neighbors detail'] = (d, S) => { const n = (S.neighbors[d.name] || []).filter(x => x.cdp); return n.map(x => '-------------------------\nDevice ID: ' + x.dev + '\nEntry address(es):\n  IP address: ' + (x.ip || 'none') + '\nPlatform: ' + x.platform + ',  Capabilities: ' + (x.platform.includes('ISR') ? 'Router' : 'Switch IGMP') + '\nInterface: ' + long(x.local) + ',  Port ID (outgoing port): ' + long(x.remote)).join('\n') || '(no neighbors)'; };
  R['show lldp neighbors'] = (d, S) => { if (!S.cfg[d.name].lldp) return '% LLDP is not enabled'; const n = (S.neighbors[d.name] || []).filter(x => x.lldp); return 'Capability codes: (R) Router, (B) Bridge\nDevice ID           Local Intf     Hold-time  Capability      Port ID\n' + (n.map(x => pad(x.dev, 20) + pad(S_(x.local), 15) + pad('120', 11) + pad(x.platform.includes('ISR') ? 'R' : 'B', 16) + S_(x.remote)).join('\n') || '(no neighbors)'); };
  R['show ntp status'] = (d, S) => { const c = S.cfg[d.name]; return c.ntp.length ? 'Clock is synchronized, stratum 3, reference is ' + c.ntp[0] + '\nnominal freq is 250.0000 Hz, actual freq is 249.9990 Hz, precision is 2**10' : 'Clock is unsynchronized, stratum 16, no reference clock'; };
  R['show ntp associations'] = (d, S) => { const c = S.cfg[d.name]; return '  address         ref clock       st   when   poll reach  delay  offset   disp\n' + (c.ntp.map(x => '*~' + pad(x, 16) + pad('127.127.1.1', 16) + ' 2     12     64   377   1.2    0.5    0.9').join('\n') || '(no associations)'); };
  R['show logging'] = (d, S) => { const c = S.cfg[d.name]; return 'Syslog logging: enabled\n    Console logging: level debugging\n    Trap logging: level informational, ' + (c.logging.length ? 'logging to ' + c.logging.join(', ') : 'no hosts configured'); };
  R['show snmp community'] = (d, S) => { const c = S.cfg[d.name]; return c.snmp.map(x => 'Community name: ' + x.community + '\nCommunity Index: ' + x.community + '\nCommunity SecurityName: ' + x.community + '\nstorage-type: nonvolatile\tactive\taccess: ' + x.mode.toUpperCase()).join('\n') || '(no communities)'; };
  R['show version'] = (d, S) => { const k = (S.net.devices[d.name] || {}).kind; return k === 'router' ? 'Cisco IOS XE Software, Version 16.9.4\n' + d.host + ' uptime is 2 hours, 14 minutes\nSystem image file is "bootflash:isr4300-universalk9.16.09.04.SPA.bin"\nConfiguration register is 0x2102' : 'Cisco IOS Software, C2960X Software (C2960X-UNIVERSALK9-M), Version 15.2(7)E\n' + d.host + ' uptime is 2 hours, 14 minutes\nBase ethernet MAC Address       : ' + ((S.net.devices[d.name] || {}).mac || '0000.0000.0000'); };
  R['show ip dhcp conflict'] = () => '(no conflicts)';
  R['show ip eigrp neighbors'] = (d, S) => { const c = S.cfg[d.name].eigrp; if (!c) return '% EIGRP: no router process'; const n = (S.eigrpNeighbors || {})[d.name] || []; return 'EIGRP-IPv4 Neighbors for AS(' + c.as + ')\nH   Address         Interface       Hold Uptime   SRTT   RTO  Q  Seq\n                                    (sec)         (ms)       Cnt Num\n' + (n.map((x, i) => pad(i, 4) + pad(x.ip, 16) + pad(S_(x.iface), 16) + pad('13', 5) + pad('00:04:12', 9) + pad('1', 7) + pad('100', 5) + pad('0', 3) + '6').join('\n') || '(no neighbors)'); };
  R['show interfaces'] = (d, S) => Object.values(S.ifaces[d.name] || {}).filter(i => i.cabled || i.cfg.ip).map(i => ifaceDetail(d, S, i)).join('\n');
  function ifaceDetail(d, S, i){ return long(i.name) + ' is ' + (i.errdisabled ? 'down (err-disabled)' : i.admin ? (i.up ? 'up' : 'down') : 'administratively down') + ', line protocol is ' + (i.up ? 'up' : 'down') + '\n  Hardware is ' + (i.kind === 'gi' ? 'Gigabit Ethernet' : i.kind === 'fa' ? 'Fast Ethernet' : i.kind === 'se' ? 'Serial' : 'Ethernet') + ', address is ' + Net.synthMac(d.name + i.name) + (i.cfg.ip ? '\n  Internet address is ' + i.cfg.ip + '/' + Net.mlen(i.cfg.mask) : '') + (i.cfg.desc ? '\n  Description: ' + i.cfg.desc : '') + '\n  ' + (i.cfg.duplex || 'Full') + '-duplex, ' + (i.cfg.speed || (i.kind === 'gi' ? '1000' : '100')) + 'Mb/s' + '\n  5 minute input rate 0 bits/sec, 0 packets/sec\n  5 minute output rate 0 bits/sec, 0 packets/sec'; }
  function long(p){ return p.replace('gigabitethernet', 'GigabitEthernet').replace('tengigabitethernet', 'TenGigabitEthernet').replace('fastethernet', 'FastEthernet').replace('serial', 'Serial').replace('loopback', 'Loopback').replace('port-channel', 'Port-channel').replace(/^vlan/, 'Vlan'); }

  function render(dev, cmd, S){
    if (!S) return null; const t = cmd.split(' ');
    if (cmd.startsWith('show spanning-tree') && S.stpTopo) { const m = cmd.match(/vlan (\d+)/); if (cmd.includes('summary')) return null; return Stp.render(S.stpTopo, m ? +m[1] : 1, dev.name, dev._all || {}); }
    let m;
    if ((m = cmd.match(/^show interfaces? (\S+)$/)) && !['trunk', 'status', 'description'].includes(m[1])) { const p = Sim.canonIf(m[1]); const i = S.ifaces[dev.name] && S.ifaces[dev.name][p]; return i ? ifaceDetail(dev, S, i) : '% Invalid interface ' + m[1]; }
    if ((m = cmd.match(/^show ip interface (\S+)$/)) && m[1] !== 'brief') { const p = Sim.canonIf(m[1]); const i = S.ifaces[dev.name] && S.ifaces[dev.name][p]; if (!i) return '% Invalid interface'; return long(p) + ' is ' + (i.up ? 'up' : 'down') + ', line protocol is ' + (i.up ? 'up' : 'down') + '\n  Internet address is ' + (i.cfg.ip ? i.cfg.ip + '/' + Net.mlen(i.cfg.mask) : 'not set') + '\n  Outgoing access list is ' + (i.cfg.aclOut || 'not set') + '\n  Inbound  access list is ' + (i.cfg.aclIn || 'not set') + '\n  NAT ' + (i.cfg.natInside ? 'inside' : i.cfg.natOutside ? 'outside' : 'disabled'); }
    if ((m = cmd.match(/^show port-security interface (\S+)$/))) { const p = Sim.canonIf(m[1]); const s = S.portsec[dev.name + '|' + p]; if (!s) return 'Port Security              : Disabled'; if (s.rejected) return 'Port Security              : Disabled\n(command rejected: port must be in access mode first)'; return 'Port Security              : Enabled\nPort Status                : ' + s.status + '\nViolation Mode             : ' + s.violation + '\nMaximum MAC Addresses      : ' + s.max + '\nTotal MAC Addresses        : ' + (s.allowed.length + s.learned.length) + '\nSticky MAC Addresses       : ' + (s.sticky ? s.learned.length : 0) + '\nSecurity Violation Count   : ' + s.violations; }
    if ((m = cmd.match(/^show (?:ip )?access-lists? (\S+)$/))) { const a = S.cfg[dev.name].acls[m[1]]; if (!a) return '% ACL ' + m[1] + ' not found'; return (a.type === 'standard' ? 'Standard' : 'Extended') + ' IP access list ' + m[1] + '\n' + a.entries.map(e => '    ' + e.seq + ' ' + e.action + ' ' + e.raw).join('\n'); }
    // exact / prefix match against renderer keys
    if (R[cmd]) return R[cmd](dev, S);
    const st = t; for (const k of Object.keys(R)) { const kt = k.split(' '); if (kt.length !== st.length) continue; let ok = true; for (let i = 0; i < kt.length; i++) if (!kt[i].startsWith(st[i])) { ok = false; break; } if (ok) return R[k](dev, S); }
    return null;
  }

  // ---- host console (PC1>)
  function host(dev, raw, S){
    const t = raw.trim().split(/\s+/); const c = (t[0] || '').toLowerCase(); const h = S && S.hosts[dev.name];
    if (!c) return '';
    if (c === 'help' || c === '?') return 'ping <ip>   ipconfig [/all]   arp -a   tracert <ip>';
    if (!h) return 'no network stack';
    if (c === 'ipconfig') { const all = (t[1] || '').toLowerCase() === '/all'; return 'Ethernet adapter Local Area Connection:\n   ' + (h.up ? '' : 'Media State . . . . . . . . . . . : Media disconnected\n   ') + (all ? 'Physical Address. . . . . . . . . : ' + h.mac.toUpperCase() + '\n   DHCP Enabled. . . . . . . . . . . : ' + (h.dhcp ? 'Yes' : 'No') + '\n   ' : '') + 'IPv4 Address. . . . . . . . . . . : ' + (h.ip || '(none)' + (h.lease && h.lease.reason ? '  — ' + h.lease.reason : '')) + '\n   Subnet Mask . . . . . . . . . . . : ' + (h.mask || '') + '\n   Default Gateway . . . . . . . . . : ' + (h.gw || '') + (all ? '\n   DNS Servers . . . . . . . . . . . : ' + ((h.dns && [].concat(h.dns).join(', ')) || '') + (h.server ? '\n   DHCP Server . . . . . . . . . . . : ' + h.server + (h.rogue ? '   (!)' : '') : '') : ''); }
    if (c === 'arp') { const seg = h.seg; const rows = (S.owners[seg] || []).filter(o => o.dev !== dev.name && o.mac); return 'Interface: ' + (h.ip || '0.0.0.0') + '\n  Internet Address      Physical Address      Type\n' + rows.map(o => '  ' + pad(o.ip, 22) + pad(o.mac, 22) + 'dynamic').join('\n'); }
    if (c === 'ping' || c === 'tracert' || c === 'traceroute') { const ip = t[1]; if (!ip) return 'Usage: ' + c + ' <ip>'; const r = Net.ping(S, dev.name, ip); dev._lastPing = r;
      if (c === 'ping') return 'Pinging ' + ip + ' with 32 bytes of data:\n' + (r.ok ? 'Reply from ' + ip + ': bytes=32 time=1ms TTL=' + (128 - (r.hops || 0)) + '\n'.repeat(1).repeat(1) + 'Reply from ' + ip + ': bytes=32 time<1ms\nReply from ' + ip + ': bytes=32 time<1ms\nReply from ' + ip + ': bytes=32 time<1ms\n\nPing statistics: Sent = 4, Received = 4, Lost = 0 (0% loss)' : 'Request timed out.\nRequest timed out.\nRequest timed out.\nRequest timed out.\n\nPing statistics: Sent = 4, Received = 0, Lost = 4 (100% loss)\n  [why: ' + r.reason + ']');
      return 'Tracing route to ' + ip + ' over a maximum of 30 hops:\n\n' + Net.traceLines(r, 'pc').join('\n') + (r.ok ? '\n\nTrace complete.' : '\n  [why: ' + r.reason + ']'); }
    return "'" + t[0] + "' is not recognized. Type help."; }

  window.Show = { render, host, renderers: R, long };
})();
