/* engine/show.js — renders IOS-style `show` output from Net state. Sim falls back to this for any show
   command a job did not hard-code. Also the host (PC) console commands. */
(function(){
  const S_ = Net.short; const pad = (s, n) => String(s).padEnd(n); const IP = Sim.ip;
  const R = {};

  R['show ip interface brief'] = (d, S) => { const rows = Object.values(S.ifaces[d.name] || {}).filter(i => !(i.kind === 'vlan' && !i.cfg.ip && i.name !== 'vlan1')).sort((a, b) => a.name.localeCompare(b.name, undefined, { numeric: true }));
    return 'Interface              IP-Address      OK? Method Status                Protocol\n' + rows.map(i => pad(long(i.name), 23) + pad(i.cfg.ip || 'unassigned', 16) + 'YES ' + pad(i.cfg.ip ? 'manual' : 'unset', 7) + pad(i.admin ? (i.up ? 'up' : 'down') : 'administratively down', 22) + (i.up ? 'up' : 'down')).join('\n'); };
  // the routing table the way IOS prints it: codes, the gateway of last resort, entries grouped under their classful network with local /32 routes
  R['show ip route'] = (d, S) => { const t = S.tables[d.name]; if (!t) return '% IP routing is not enabled on ' + d.name;
    const codes = 'Codes: L - local, C - connected, S - static, R - RIP, M - mobile, B - BGP\n       D - EIGRP, EX - EIGRP external, O - OSPF, IA - OSPF inter area\n       N1 - OSPF NSSA external type 1, N2 - OSPF NSSA external type 2\n       E1 - OSPF external type 1, E2 - OSPF external type 2\n       i - IS-IS, su - IS-IS summary, L1 - IS-IS level-1, L2 - IS-IS level-2\n       * - candidate default, U - per-user static route, o - ODR\n       P - periodic downloaded static route\n';
    const gw = t.find(e => e.len === 0); const n = x => IP.ip2n(x);
    const rows = t.slice(); S.l3.filter(o => o.dev === d.name && o.kind === 'iface' && S.ifaces[d.name][o.iface] && S.ifaces[d.name][o.iface].up).forEach(o => rows.push({ prefix: o.ip, len: 32, proto: 'L', iface: o.iface, via: null }));
    const classful = p => { const f = n(p) >>> 24; return f < 128 ? [IP.n2ip((n(p) & 0xff000000) >>> 0), 8] : f < 192 ? [IP.n2ip((n(p) & 0xffff0000) >>> 0), 16] : [IP.n2ip((n(p) & 0xffffff00) >>> 0), 24]; };
    const line = (e, indent) => pad(e.proto, indent) + e.prefix + '/' + e.len + (e.via ? ' [' + (e.ad != null ? e.ad : 0) + '/' + (e.metric || 0) + '] via ' + e.via + ((e.proto !== 'S' && e.proto !== 'S*') || e.exit ? ', ' + long(e.iface) : '') : ' is directly connected, ' + long(e.iface));
    const out = []; const def = rows.filter(e => e.len === 0); const groups = {};
    rows.filter(e => e.len !== 0).forEach(e => { const [cn, cl] = classful(e.prefix); (groups[cn + '/' + cl] = groups[cn + '/' + cl] || { cn, cl, rows: [] }).rows.push(e); });
    def.forEach(e => out.push(line(e, 6)));
    Object.values(groups).sort((a, b) => n(a.cn) - n(b.cn)).forEach(g => { g.rows.sort((a, b) => n(a.prefix) - n(b.prefix) || a.len - b.len); const masks = new Set(g.rows.map(e => e.len));
      if (g.rows.length === 1 && g.rows[0].len === g.cl) { out.push(line(g.rows[0], 6)); return; }
      out.push('      ' + g.cn + '/' + (masks.size === 1 ? [...masks][0] : g.cl) + ' is ' + (masks.size > 1 ? 'variably subnetted, ' + g.rows.length + ' subnets, ' + masks.size + ' masks' : 'subnetted, ' + g.rows.length + ' subnets'));
      g.rows.forEach(e => out.push(line(e, 9))); });
    return codes + '\nGateway of last resort is ' + (gw ? (gw.via || 'directly connected') + ' to network 0.0.0.0' : 'not set') + '\n\n' + out.join('\n'); };
  R['show ip ospf neighbor'] = (d, S) => { const n = S.ospf.neighbors[d.name] || []; if (!S.cfg[d.name].ospf) return '% OSPF: No router process'; return 'Neighbor ID     Pri   State           Dead Time   Address         Interface\n' + n.map(x => pad(x.id, 16) + pad('1', 6) + pad(x.state + '/DR', 16) + pad('00:00:35', 12) + pad(x.ip, 16) + long(x.iface)).join('\n') + (n.length ? '' : '(no neighbors)'); };
  R['show ip protocols'] = (d, S) => { const c = S.cfg[d.name]; const out = []; if (c.ospf) { const o = S.ospf.routers[d.name]; out.push('Routing Protocol is "ospf ' + c.ospf.pid + '"', '  Router ID ' + (o ? o.id : '0.0.0.0'), '  Routing for Networks:'); c.ospf.networks.forEach(n => out.push('    ' + n.addr + ' ' + n.wild + ' area ' + n.area)); out.push('  Passive Interface(s):'); (o ? o.ifaces : []).filter(i => i.passive).forEach(i => out.push('    ' + long(i.iface))); out.push('  Distance: (default is 110)'); }
    if (c.rip) out.push('Routing Protocol is "rip"', '  Version ' + (c.rip.v2 ? 2 : 1), '  Routing for Networks: ' + c.rip.networks.join(', '), '  Distance: (default is 120)'); if (c.eigrp) out.push('Routing Protocol is "eigrp ' + c.eigrp.as + '"', '  Routing for Networks: ' + c.eigrp.networks.map(n => n.addr + (n.wild ? ' ' + n.wild : '')).join(', '), '  Distance: internal 90 external 170'); return out.length ? out.join('\n') : '% No routing protocols configured'; };
  R['show standby brief'] = (d, S) => { const rows = []; for (const k in S.hsrp) { const g = S.hsrp[k]; g.members.forEach(m => { if (m.dev !== d.name) return; const role = g.active.dev === d.name ? 'Active' : g.standby && g.standby.dev === d.name ? 'Standby' : 'Listen'; rows.push(pad(S_(m.iface), 12) + pad(g.group, 6) + pad(m.priority, 5) + pad(m.preempt ? 'P' : '', 3) + pad(role, 8) + pad(g.active.dev === d.name ? 'local' : g.active.ip, 16) + pad(g.standby ? (g.standby.dev === d.name ? 'local' : g.standby.ip) : 'unknown', 16) + g.vip); }); }
    return '                     P indicates configured to preempt.\nInterface   Grp  Pri P State   Active          Standby         Virtual IP\n' + (rows.join('\n') || '(no HSRP groups)'); };
  R['show access-lists'] = (d, S) => { const a = S.cfg[d.name].acls; const ks = Object.keys(a); if (!ks.length) return '(no access lists)'; return ks.map(k => (a[k].type === 'standard' ? 'Standard' : 'Extended') + ' IP access list ' + k + '\n' + a[k].entries.map(e => '    ' + e.seq + ' ' + e.action + ' ' + (a[k].type === 'standard' ? (e.swild === '0.0.0.0' ? 'host ' + e.src : e.swild === '255.255.255.255' ? 'any' : e.src + ', wildcard bits ' + e.swild) : e.raw)).join('\n')).join('\n'); };
  R['show ip access-lists'] = R['show access-lists'];
  // static mappings from the config, then every translation the pings made, with the outside address (the same local and global: source NAT only)
  R['show ip nat translations'] = (d, S) => { const c = S.cfg[d.name]; const t = d._natSeen || []; const hp = (ip, p, on) => on ? ip + ':' + p : ip;
    if (!t.length && !c.natStatic.length) return 'Pro  Inside global      Inside local       Outside local      Outside global\n(no translations yet: send traffic from an inside host first)';
    return 'Pro  Inside global      Inside local       Outside local      Outside global\n' + c.natStatic.map(x => pad('---', 5) + pad(x.outside, 19) + pad(x.inside, 19) + pad('---', 19) + '---').concat(t.map(x => { const on = x.proto !== 'ip'; const pr = x.proto === 'icmp' ? 1 : x.port;
      return pad(x.proto, 5) + pad(hp(x.global, x.kind === 'pat' ? (x.proto === 'icmp' ? (x.gport || x.port) - x.port + 1 : (x.gport || x.port)) : pr, on), 19) + pad(hp(x.inside, pr, on), 19) + pad(hp(x.outside || '---', pr, on && x.outside), 19) + hp(x.outside || '---', pr, on && x.outside); })).join('\n'); };
  R['show ip nat statistics'] = (d, S) => { const c = S.cfg[d.name]; const ins = Object.values(S.ifaces[d.name]).filter(i => i.cfg.natInside).map(i => long(i.name)), outs = Object.values(S.ifaces[d.name]).filter(i => i.cfg.natOutside).map(i => long(i.name)); return 'Total active translations: ' + (d._natSeen || []).length + '\nOutside interfaces:\n  ' + (outs.join(', ') || '(none)') + '\nInside interfaces:\n  ' + (ins.join(', ') || '(none)') + '\nDynamic mappings:\n' + c.natDynamic.map(x => '-- Inside Source\n  access-list ' + x.acl + (x.iface ? ' interface ' + x.iface : ' pool ' + x.pool) + (x.overload ? ' overload' : '')).join('\n'); };
  R['show ip dhcp binding'] = (d, S) => { const rows = Object.values(S.hosts).filter(h => h.lease && h.lease.ok && h.server === d.name); return 'IP address       Client-ID/Hardware address   Lease expiration        Type\n' + (rows.map(h => pad(h.ip, 17) + pad(h.mac, 29) + pad('Sep 28 2026 10:00 AM', 24) + 'Automatic').join('\n') || '(no bindings)'); };
  R['show ip dhcp pool'] = (d, S) => { const p = S.cfg[d.name].dhcp.pools; return Object.values(p).map(x => 'Pool ' + x.name + ' :\n Network: ' + x.network + ' ' + x.mask + '\n Default router: ' + (x.router || '-') + '\n DNS: ' + (x.dns.join(' ') || '-')).join('\n') || '(no pools)'; };
  R['show ip dhcp snooping'] = (d, S) => { const c = S.cfg[d.name].dhcp; const X = S.cfg[d.name].sec || NetConfig.secBlank(); const rows = Object.values(S.ifaces[d.name]).filter(i => i.cfg.snoopTrust || i.cfg.snoopRate); return 'Switch DHCP snooping is ' + (c.snooping ? 'enabled' : 'disabled') + '\nDHCP snooping is configured on following VLANs:\n' + ([...c.snoopVlans].join(',') || 'none') + '\nInsertion of option 82 is ' + (X.option82 ? 'enabled' : 'disabled') + '\nInterface                  Trusted    Rate limit (pps)\n' + (rows.map(i => pad(long(i.name), 27) + pad(i.cfg.snoopTrust ? 'yes' : 'no', 11) + (i.cfg.snoopRate || 'unlimited')).join('\n') || '(no trusted interfaces)'); };
  R['show ip dhcp snooping binding'] = (d, S) => { const c = S.cfg[d.name].dhcp; const port = h => { for (const p in S.ifaces[d.name]) { const i = S.ifaces[d.name][p]; if (i.peer === h.name) return i; } return null; };
    const rows = c.snooping ? Object.values(S.hosts).filter(h => h.lease && h.lease.ok && !h.rogue).map(h => [h, port(h)]).filter(([h, i]) => i && c.snoopVlans.has(i.vlan)) : [];
    return 'MacAddress          IpAddress        Lease(sec)  Type           VLAN  Interface\n' + (rows.map(([h, i]) => pad(h.mac.toUpperCase().replace(/\./g, '').replace(/(..)(?!$)/g, '$1:'), 20) + pad(h.ip, 17) + pad('86400', 12) + pad('dhcp-snooping', 15) + pad(i.vlan, 6) + long(i.name)).join('\n') || '(empty)') + '\nTotal number of bindings: ' + rows.length; };
  R['show ip arp inspection'] = (d, S) => { const c = S.cfg[d.name].dhcp; const X = S.cfg[d.name].sec || NetConfig.secBlank(); const t = S.threats.arpspoof; const on = k => X.daiValidate.includes(k) ? 'Enabled' : 'Disabled'; const drops = (S.daiDrops || []).filter(x => x.sw === d.name);
    return 'Source Mac Validation      : ' + on('src-mac') + '\nDestination Mac Validation : ' + on('dst-mac') + '\nIP Address Validation      : ' + on('ip') + '\n\n Vlan     Configuration    Operation   ACL Match          Static ACL\n ----     -------------    ---------   ---------          ----------\n' + ([...c.daiVlans].map(v => pad(' ' + v, 10) + pad('Enabled', 17) + pad(c.snooping ? 'Active' : 'Inactive (needs DHCP snooping)', 12) + pad(X.daiFilters[v] || '', 19) + 'No').join('\n') || ' (no VLANs)') + (t || drops.length ? '\n\n Vlan   Forwarded   Dropped\n ----   ---------   -------\n    ' + pad([...c.daiVlans][0] || 1, 4) + pad(t && t.blocked ? 14 : 22, 12) + ((t && t.blocked ? 8 : 0) + drops.length * 4) : '') + (t && t.blocked && t.sw === d.name ? '\n\n%SW_DAI-4-DHCP_SNOOPING_DENY: 8 Invalid ARPs (Res) on ' + S_(t.port) + ', vlan ' + t.vlan + '.([' + t.mac + '/' + (t.claims || '0.0.0.0') + '/ffff.ffff.ffff/' + (t.claims || '0.0.0.0') + '])' : '') + (drops.length ? '\n\n' + drops.map(x => '%SW_DAI-4-DHCP_SNOOPING_DENY: 1 Invalid ARPs (Res) on ' + S_(x.port) + ', vlan ' + x.vlan + '.([' + x.ip + '])').join('\n') : ''); };
  R['show ip arp inspection interfaces'] = (d, S) => 'Interface        Trust State     Rate (pps)    Burst Interval\n ---------------  -----------     ----------    --------------\n' + Object.values(S.ifaces[d.name] || {}).filter(i => i.kind === 'gi' || i.kind === 'fa').sort((a, b) => a.name.localeCompare(b.name, undefined, { numeric: true })).map(i => ' ' + pad(S_(i.name), 17) + pad(i.cfg.daiTrust ? 'Trusted' : 'Untrusted', 16) + pad(i.cfg.daiRate != null ? i.cfg.daiRate : i.cfg.daiTrust ? 'None' : 15, 14) + (i.cfg.daiBurst || 1)).join('\n');
  R['show errdisable recovery'] = (d, S) => { const X = S.cfg[d.name].sec || NetConfig.secBlank(); const causes = ['arp-inspection', 'bpduguard', 'dhcp-rate-limit', 'link-flap', 'psecure-violation', 'security-violation']; const down = Object.values(S.ifaces[d.name] || {}).filter(i => i.errdisabled);
    return 'ErrDisable Reason            Timer Status\n-----------------            --------------\n' + causes.map(c => pad(c, 29) + (X.recoveryCauses.has(c) ? 'Enabled' : 'Disabled')).join('\n') + '\n\nTimer interval: ' + X.recoveryInterval + ' seconds\n\nInterfaces that will be enabled at the next timeout:\n' + (down.length && X.recoveryCauses.has('psecure-violation') ? 'Interface       Errdisable reason       Time left(sec)\n' + down.map(i => pad(S_(i.name), 16) + pad('psecure-violation', 24) + X.recoveryInterval).join('\n') : ''); };
  R['show mac address-table secure'] = (d, S) => { const rows = Object.keys(S.portsec).filter(k => k.startsWith(d.name + '|')).flatMap(k => { const s = S.portsec[k]; if (s.rejected) return []; const p = k.split('|')[1]; const v = (S.ifaces[d.name][p] || {}).vlan || 1; return s.allowed.concat(s.learned).map(m => [v, m, p]); });
    return '          Mac Address Table\n-------------------------------------------\n\nVlan    Mac Address       Type        Ports\n----    -----------       --------    -----\n' + rows.map(([v, m, p]) => pad('  ' + v, 8) + pad(m, 18) + pad('STATIC', 12) + S_(p)).join('\n') + (rows.length ? '\n' : '') + 'Total Mac Addresses for this criterion: ' + rows.length; };
  R['show ip arp inspection statistics'] = R['show ip arp inspection'];
  R['show vlan brief'] = (d, S) => { const c = S.cfg[d.name]; const v = Object.assign({ 1: { id: 1, name: 'default' } }, c.vlans); const ports = {}; Object.values(S.ifaces[d.name] || {}).forEach(i => { if (i.kind !== 'gi' && i.kind !== 'fa') return; if (i.trunk) return; (ports[i.vlan] = ports[i.vlan] || []).push(S_(i.name)); });
    return 'VLAN Name                             Status    Ports\n---- -------------------------------- --------- -------------------------------\n' + Object.values(v).sort((a, b) => a.id - b.id).map(x => pad(x.id, 5) + pad(x.name || ('VLAN' + String(x.id).padStart(4, '0')), 33) + 'active    ' + (ports[x.id] || []).join(', ')).join('\n'); };
  R['show interfaces trunk'] = (d, S) => { const tr = Object.values(S.ifaces[d.name] || {}).filter(i => i.trunk && i.up); if (!tr.length) return '(no trunk ports)'; return 'Port        Mode             Encapsulation  Status        Native vlan\n' + tr.map(i => pad(S_(i.name), 12) + pad(i.mode === 'trunk' ? 'on' : 'auto', 17) + pad('802.1q', 15) + pad('trunking', 14) + i.native).join('\n') + '\n\nPort        Vlans allowed on trunk\n' + tr.map(i => pad(S_(i.name), 12) + (i.allowed ? [...i.allowed].sort((a, b) => a - b).join(',') : '1-4094')).join('\n'); };
  R['show interfaces status'] = (d, S) => { const rows = Object.values(S.ifaces[d.name] || {}).filter(i => i.kind === 'gi' || i.kind === 'fa'); return 'Port      Name               Status       Vlan       Duplex  Speed Type\n' + rows.map(i => pad(S_(i.name), 10) + pad((i.cfg.desc || '').slice(0, 18), 19) + pad(i.errdisabled ? 'err-disabled' : !i.admin ? 'disabled' : i.up ? 'connected' : 'notconnect', 13) + pad(i.trunk ? 'trunk' : i.vlan, 11) + pad(i.op && i.up ? (i.op.autoDuplex ? 'a-' : '') + i.op.duplex : (i.cfg.duplex && i.cfg.duplex !== 'auto' ? i.cfg.duplex : 'auto'), 8) + pad(i.op && i.up ? (i.op.autoSpeed ? 'a-' : '') + i.op.speed : (i.cfg.speed && i.cfg.speed !== 'auto' ? i.cfg.speed : 'auto'), 6) + (i.kind === 'gi' ? '10/100/1000BaseTX' : '10/100BaseTX')).join('\n'); };
  R['show mac address-table'] = (d, S) => { const rows = Net.api(S).macTable(d.name); return '          Mac Address Table\n-------------------------------------------\n\nVlan    Mac Address       Type        Ports\n----    -----------       --------    -----\n' + rows.map(r => pad('  ' + r.vlan, 8) + pad(r.mac, 18) + pad('DYNAMIC', 12) + S_(r.port)).join('\n') + (rows.length ? '\n' : '') + 'Total Mac Addresses for this criterion: ' + rows.length; };
  R['show mac address-table dynamic'] = R['show mac address-table'];
  R['show arp'] = (d, S) => { const own = S.l3.filter(o => o.dev === d.name && o.kind === 'iface'); const rows = own.map(o => ({ ip: o.ip, mac: o.mac, age: '-', iface: o.iface })).concat(Net.arpRows(S, d.name).map(x => { const o = own.find(i => Net.inSubnet(x.ip, Net.netOf(i.ip, i.mask), i.mask)); return { ip: x.ip, mac: x.mac, age: '0', iface: o ? o.iface : '' }; }));
    return 'Protocol  Address          Age (min)  Hardware Addr   Type   Interface\n' + rows.map(r => pad('Internet', 10) + pad(r.ip, 17) + pad(String(r.age).padStart(5), 11) + pad(r.mac, 16) + pad('ARPA', 7) + S_(r.iface)).join('\n'); };
  R['show ip arp'] = R['show arp'];
  R['show etherchannel summary'] = (d, S) => { const bs = Object.values(S.bundles).filter(g => g.a === d.name || g.b === d.name); if (!bs.length) return 'Number of channel-groups in use: 0\n(no bundles formed — check both sides have channel-group with compatible modes)'; return 'Flags:  D - down  P - bundled in port-channel  U - in use  S - Layer2  L - Layer3\nNumber of channel-groups in use: ' + bs.length + '\nGroup  Port-channel  Protocol    Ports\n------+-------------+-----------+-----------------------------------------------\n' + bs.map(g => { const me = g.a === d.name; const grp = me ? g.ga : g.gb; const ports = g.links.map(L => S_(me ? (L.a === d.name ? L.ap : L.bp) : (L.b === d.name ? L.bp : L.ap)) + '(P)'); const mode = S.ifaces[d.name][me ? (g.links[0].a === d.name ? g.links[0].ap : g.links[0].bp) : (g.links[0].b === d.name ? g.links[0].bp : g.links[0].ap)].cfg.channel.mode; return pad(grp, 7) + pad('Po' + grp + '(SU)', 14) + pad(mode === 'on' ? '-' : ['active', 'passive'].includes(mode) ? 'LACP' : 'PAgP', 12) + ports.join(' '); }).join('\n'); };
  R['show port-security'] = (d, S) => { const rows = Object.keys(S.portsec).filter(k => k.startsWith(d.name + '|')).map(k => [k.split('|')[1], S.portsec[k]]); return 'Secure Port  MaxSecureAddr  CurrentAddr  SecurityViolation  Security Action\n' + (rows.map(([p, s]) => s.rejected ? pad(S_(p), 13) + '(rejected: port is not in access mode)' : pad(S_(p), 13) + pad(s.max, 15) + pad(s.allowed.length + s.learned.length, 13) + pad(s.violations, 19) + s.violation).join('\n') || '(no secure ports)'); };
  R['show port-security address'] = (d, S) => { const rows = Object.keys(S.portsec).filter(k => k.startsWith(d.name + '|')).flatMap(k => { const s = S.portsec[k]; if (s.rejected) return []; const p = k.split('|')[1]; return [...s.allowed.map(m => [m, 'SecureConfigured', p]), ...s.learned.map(m => [m, s.sticky ? 'SecureSticky' : 'SecureDynamic', p])]; }); return 'Vlan    Mac Address       Type                Ports\n' + (rows.map(([m, t, p]) => pad(' 1', 8) + pad(m, 18) + pad(t, 20) + S_(p)).join('\n') || '(none)'); };
  R['show ipv6 interface brief'] = (d, S) => { const rows = Object.values(S.ifaces[d.name] || {}).filter(i => i.cfg.ipv6.length || i.cfg.ipv6Enable); if (!rows.length) return '(no IPv6 interfaces)'; return rows.map(i => long(i.name) + '       [' + (i.up ? 'up/up' : 'down/down') + ']\n    ' + (i.cfg.ipv6LinkLocal || Net.eui64('FE80::', Net.synthMac(d.name + i.name)).toUpperCase()) + '\n' + i.cfg.ipv6.map(a => '    ' + (a.eui64 ? Net.eui64(a.addr, Net.synthMac(d.name + i.name)) : a.addr).toUpperCase()).join('\n')).join('\n'); };
  R['show ipv6 route'] = (d, S) => { const t = S.tables6[d.name]; if (!t) return '% IPv6 routing not enabled'; if (!S.cfg[d.name].ipv6Routing) return 'IPv6 Routing Table - default\n(ipv6 unicast-routing is not enabled — this box will not forward IPv6)\n' + t.map(e => e.proto + '   ' + e.prefix + '/' + e.len + (e.via ? ' via ' + e.via : ' via ' + long(e.iface) + ', directly connected')).join('\n'); return 'IPv6 Routing Table - default\nCodes: C - Connected, L - Local, S - Static\n' + t.map(e => e.proto + '   ' + e.prefix + '/' + e.len + (e.via ? ' [' + e.ad + '/0]\n     via ' + e.via : '\n     via ' + long(e.iface) + ', directly connected')).join('\n'); };
  R['show ip ssh'] = (d, S) => { const c = S.cfg[d.name]; return c.sshKeyBits ? 'SSH Enabled - version ' + (c.sshVersion || '1.99') + '\nAuthentication timeout: 120 secs; Authentication retries: 3\nMinimum expected Diffie Hellman key size : 1024 bits\nIOS Keys in SECSH format(ssh-rsa, base64 encoded): ' + (c.hostname || d.name) + '.' + (c.domain || '?') : 'SSH Disabled - version 1.99\n%Please create RSA keys to enable SSH (and of atleast 768 bits for SSH v2).\nAuthentication timeout: 120 secs; Authentication retries: 3'; };
  R['show cdp neighbors'] = (d, S) => { if (!S.cfg[d.name].cdp) return '% CDP is not enabled'; const n = (S.neighbors[d.name] || []).filter(x => x.cdp); return 'Capability Codes: R - Router, S - Switch, I - IGMP\n\nDevice ID        Local Intrfce     Holdtme    Capability  Platform  Port ID\n' + (n.map(x => pad(x.dev, 17) + pad(S_(x.local), 18) + pad('150', 11) + pad(x.platform.includes('ISR') ? 'R' : 'S I', 12) + pad(x.platform.replace('cisco ', ''), 10) + S_(x.remote)).join('\n') || '(no neighbors)'); };
  R['show cdp neighbors detail'] = (d, S) => { const n = (S.neighbors[d.name] || []).filter(x => x.cdp); return n.map(x => '-------------------------\nDevice ID: ' + x.dev + '\nEntry address(es):\n  IP address: ' + (x.ip || 'none') + '\nPlatform: ' + x.platform + ',  Capabilities: ' + (x.platform.includes('ISR') ? 'Router' : 'Switch IGMP') + '\nInterface: ' + long(x.local) + ',  Port ID (outgoing port): ' + long(x.remote)).join('\n') || '(no neighbors)'; };
  R['show lldp neighbors'] = (d, S) => { if (!S.cfg[d.name].lldp) return '% LLDP is not enabled'; const n = (S.neighbors[d.name] || []).filter(x => x.lldp); return 'Capability codes: (R) Router, (B) Bridge\nDevice ID           Local Intf     Hold-time  Capability      Port ID\n' + (n.map(x => pad(x.dev, 20) + pad(S_(x.local), 15) + pad('120', 11) + pad(x.platform.includes('ISR') ? 'R' : 'B', 16) + S_(x.remote)).join('\n') || '(no neighbors)'); };
  R['show ntp status'] = (d, S) => { const c = S.cfg[d.name]; return c.ntp.length ? 'Clock is synchronized, stratum 3, reference is ' + c.ntp[0] + '\nnominal freq is 250.0000 Hz, actual freq is 249.9990 Hz, precision is 2**10' : 'Clock is unsynchronized, stratum 16, no reference clock'; };
  R['show ntp associations'] = (d, S) => { const c = S.cfg[d.name]; return '  address         ref clock       st   when   poll reach  delay  offset   disp\n' + (c.ntp.map(x => '*~' + pad(x, 16) + pad('127.127.1.1', 16) + ' 2     12     64   377   1.2    0.5    0.9').join('\n') || '(no associations)'); };
  R['show logging'] = (d, S) => { const c = S.cfg[d.name]; return 'Syslog logging: enabled\n    Console logging: level debugging\n    Trap logging: level informational, ' + (c.logging.length ? 'logging to ' + c.logging.join(', ') : 'no hosts configured'); };
  R['show snmp community'] = (d, S) => { const c = S.cfg[d.name]; return c.snmp.map(x => 'Community name: ' + x.community + '\nCommunity Index: ' + x.community + '\nCommunity SecurityName: ' + x.community + '\nstorage-type: nonvolatile\tactive\taccess: ' + x.mode.toUpperCase()).join('\n') || '(no communities)'; };
  R['show version'] = (d, S) => { const k = (S.net.devices[d.name] || {}).kind; return k === 'router' ? 'Cisco IOS XE Software, Version 16.9.4\n' + d.host + ' uptime is 2 hours, 14 minutes\nSystem image file is "bootflash:isr4300-universalk9.16.09.04.SPA.bin"\nConfiguration register is 0x2102' : 'Cisco IOS Software, C2960X Software (C2960X-UNIVERSALK9-M), Version 15.2(7)E\n' + d.host + ' uptime is 2 hours, 14 minutes\nBase ethernet MAC Address       : ' + ((S.net.devices[d.name] || {}).mac || '0000.0000.0000'); };
  R['show ip dhcp conflict'] = () => '(no conflicts)';
  R['show interfaces description'] = (d, S) => { const rows = Object.values(S.ifaces[d.name] || {}).filter(i => !(i.kind === 'vlan' && !i.cfg.ip && !i.cfg.desc)).sort((a, b) => a.name.localeCompare(b.name, undefined, { numeric: true }));
    return 'Interface                      Status         Protocol Description\n' + rows.map(i => pad(S_(i.name), 31) + pad(i.errdisabled ? 'down' : i.admin ? (i.up ? 'up' : 'down') : 'admin down', 15) + pad(i.up ? 'up' : 'down', 9) + (i.cfg.desc || '')).join('\n'); };
  R['show interfaces'] = (d, S) => Object.values(S.ifaces[d.name] || {}).filter(i => i.cabled || i.cfg.ip).map(i => ifaceDetail(d, S, i)).join('\n');
  function ifaceDetail(d, S, i){ return long(i.name) + ' is ' + (i.errdisabled ? 'down (err-disabled)' : i.admin ? (i.up ? 'up' : 'down') : 'administratively down') + ', line protocol is ' + (i.up ? 'up' : 'down') + '\n  Hardware is ' + (i.kind === 'gi' ? 'Gigabit Ethernet' : i.kind === 'fa' ? 'Fast Ethernet' : i.kind === 'se' ? 'Serial' : 'Ethernet') + ', address is ' + Net.synthMac(d.name + i.name) + (i.cfg.ip ? '\n  Internet address is ' + i.cfg.ip + '/' + Net.mlen(i.cfg.mask) : '') + (i.cfg.desc ? '\n  Description: ' + i.cfg.desc : '') + '\n  ' + opLine(i) + '\n  5 minute input rate 0 bits/sec, 0 packets/sec\n  5 minute output rate 0 bits/sec, 0 packets/sec\n' + counters(i); }
  // operating speed and duplex, as negotiated on the link (engine i.op); unconnected ports show what is configured
  function opLine(i){ const o = i.op; if (!o || !i.up) return (i.cfg.duplex && i.cfg.duplex !== 'auto' ? cap(i.cfg.duplex) + '-duplex' : 'Auto-duplex') + ', ' + (i.cfg.speed && i.cfg.speed !== 'auto' ? i.cfg.speed + 'Mb/s' : 'Auto-speed'); return cap(o.duplex) + '-duplex, ' + o.speed + 'Mb/s'; }
  const cap = w => w.charAt(0).toUpperCase() + w.slice(1);
  // error counters: a duplex mismatch shows its classic signature (CRC errors and runts on the full-duplex end, late collisions on the half-duplex end)
  function counters(i){ const m = i.dupMismatch && i.up, full = m && i.op.duplex === 'full', half = m && i.op.duplex === 'half';
    return '     ' + (full ? 213 : 0) + ' runts, 0 giants, 0 throttles\n     ' + (full ? 1377 : 0) + ' input errors, ' + (full ? 1164 : 0) + ' CRC, ' + (full ? 213 : 0) + ' frame, 0 overrun, 0 ignored\n     ' + (half ? 402 : 0) + ' output errors, ' + (half ? 2089 : 0) + ' collisions, 0 interface resets\n     ' + (half ? 402 : 0) + ' late collision, 0 deferred'; }
  // flash: the image the box shipped with (net device `flash: [{ name, size }]`, or a stock one) plus anything copied in
  const flashOf = (d, S) => { const def = (S.net.devices[d.name] || {}); const base = def.flash || [def.kind === 'router' ? { name: 'c2900-universalk9-mz.SPA.151-4.M4.bin', size: 33591768 } : { name: 'c2960-lanbasek9-mz.150-2.SE4.bin', size: 9920768 }];
    const got = d.flash || []; return base.filter(f => !got.some(g => g.name === f.name.toLowerCase())).concat(got); };
  R['show flash'] = (d, S) => { const fs = flashOf(d, S); const used = fs.reduce((a, f) => a + (f.size || 0), 0); const total = 256000000;
    return '-#- --length-- -----date/time------ path\n' + fs.map((f, i) => pad(i + 1, 4) + String(f.size || 0).padStart(10) + ' Sep 28 2026 01:1' + i + ':04 +00:00 ' + f.name).join('\n') + '\n\n' + (total - used) + ' bytes available (' + used + ' bytes used)'; };
  R['show flash:'] = R['show flash'];
  R['show file systems'] = () => 'File Systems:\n\n     Size(b)     Free(b)      Type  Flags  Prefixes\n*  256000000   188816464      disk     rw   flash:\n           -           -    opaque     rw   system:\n           -           -    opaque     rw   tmpsys:\n      262136      257912     nvram     rw   nvram:\n           -           -   network     rw   tftp:\n           -           -   network     rw   ftp:\n           -           -   network     rw   scp:';
  // QoS (MQC): class-maps and policy-maps as configured; per-interface policies with zero counters (no traffic model)
  const DSCP = v => { v = String(v).toLowerCase(); if (v === 'ef') return 46; if (v === 'default') return 0; let m; if ((m = v.match(/^af([1-4])([1-3])$/))) return 8 * +m[1] + 2 * +m[2]; if ((m = v.match(/^cs([0-7])$/))) return 8 * +m[1]; return /^\d+$/.test(v) ? +v : null; };
  const matchText = x => { const m = x.match(/^(ip )?dscp (\S+)$/); return m ? 'dscp ' + m[2] + (DSCP(m[2]) != null && !/^\d+$/.test(m[2]) ? ' (' + DSCP(m[2]) + ')' : '') : x; };
  const classActs = c => [c.setDscp ? 'set dscp ' + c.setDscp + (DSCP(c.setDscp) != null ? ' (' + DSCP(c.setDscp) + ')' : '') : null, c.setCos != null ? 'set cos ' + c.setCos : null, c.priority ? 'Strict Priority, ' + (c.priority.percent ? c.priority.percent + '% of the link' : c.priority.kbps + ' kbps') : null,
    c.bandwidth ? 'bandwidth ' + (c.bandwidth.percent ? c.bandwidth.percent + '%' : c.bandwidth.kbps + ' kbps') + ' (minimum guaranteed)' : null, c.police ? 'police ' + c.police.bps + ' bps: over the rate is dropped' : null, c.shape ? 'shape average ' + c.shape.bps + ' bps: over the rate is queued' : null, c.fairQueue ? 'fair-queue' : null, c.wred ? c.wred : null].filter(Boolean);
  R['show class-map'] = (d, S) => { const q = S.cfg[d.name].qos; const cs = Object.values(q.classMaps); return cs.map((c, i) => ' Class Map ' + c.type + ' ' + c.name + ' (id ' + (i + 1) + ')\n' + (c.matches.map(x => '   Match ' + matchText(x)).join('\n') || '   (no match statements)')).join('\n\n') + (cs.length ? '\n\n' : '') + ' Class Map match-any class-default (id 0)\n   Match any'; };
  R['show policy-map'] = (d, S) => { const q = S.cfg[d.name].qos; const ps = Object.values(q.policyMaps); if (!ps.length) return '(no policy maps)'; return ps.map(p => '  Policy Map ' + p.name + '\n' + p.order.map(n => '    Class ' + n + '\n' + classActs(p.classes[n]).map(a => '      ' + a).join('\n')).join('\n')).join('\n\n'); };
  function policyOn(d, S, i){ const q = S.cfg[d.name].qos; const out = [long(i.name)]; const sp = i.cfg.servicePolicy || {}; if (!sp.input && !sp.output) return long(i.name) + '\n  (no service-policy on this interface)';
    for (const dir of ['input', 'output']) { if (!sp[dir]) continue; const p = q.policyMaps[sp[dir]]; out.push('', '  Service-policy ' + dir + ': ' + sp[dir] + (p ? '' : '  (policy map not defined)'));
      if (p) p.order.concat(p.order.includes('class-default') ? [] : ['class-default']).forEach(n => { const cm = q.classMaps[n]; out.push('', '    Class-map: ' + n + ' (' + (n === 'class-default' ? 'match-any' : cm ? cm.type : 'not defined') + ')', '      0 packets, 0 bytes', '      5 minute offered rate 0000 bps, drop rate 0000 bps', '      Match: ' + (n === 'class-default' ? 'any' : cm ? cm.matches.map(matchText).join(', ') || '(nothing)' : '(class map missing)'));
        if (p.classes[n]) classActs(p.classes[n]).forEach(a => out.push('      ' + a)); }); }
    return out.join('\n'); }
  R['show policy-map interface'] = (d, S) => Object.values(S.ifaces[d.name] || {}).filter(i => i.cfg.servicePolicy).map(i => policyOn(d, S, i)).join('\n\n') || '(no service-policy on any interface)';

  // show interfaces X switchport: the port's mode, its access VLAN and its voice VLAN (the phone's tagged VLAN)
  function switchportDetail(d, S, i){ const c = S.cfg[d.name]; const vname = v => (c.vlans[v] && c.vlans[v].name) || (v === 1 ? 'default' : 'VLAN' + String(v).padStart(4, '0')); const mode = i.cfg.mode || 'dynamic auto';
    const oper = i.trunk ? 'trunk' : mode === 'access' || !i.trunk ? 'static access' : mode;
    return 'Name: ' + S_(i.name) + '\nSwitchport: Enabled\nAdministrative Mode: ' + (mode === 'access' ? 'static access' : mode) + '\nOperational Mode: ' + (i.up ? oper : 'down') + '\nAdministrative Trunking Encapsulation: dot1q\nNegotiation of Trunking: ' + (mode === 'access' || i.cfg.nonegotiate ? 'Off' : 'On') +
      '\nAccess Mode VLAN: ' + (i.vlan || 1) + ' (' + vname(i.vlan || 1) + ')\nTrunking Native Mode VLAN: ' + (i.native || 1) + ' (' + vname(i.native || 1) + ')\nVoice VLAN: ' + (i.cfg.voiceVlan ? i.cfg.voiceVlan + ' (' + vname(i.cfg.voiceVlan) + ')' : 'none') + (i.cfg.powerPolice ? '\nPower inline police: on, action ' + i.cfg.powerPolice : ''); }
  function long(p){ return p.replace('gigabitethernet', 'GigabitEthernet').replace('tengigabitethernet', 'TenGigabitEthernet').replace('fastethernet', 'FastEthernet').replace('serial', 'Serial').replace('loopback', 'Loopback').replace('port-channel', 'Port-channel').replace(/^vlan/, 'Vlan'); }

  function render(dev, cmd, S){
    if (!S) return null; const t = cmd.split(' ');
    if (cmd.startsWith('show spanning-tree') && S.stpTopo) { const m = cmd.match(/vlan (\d+)/); if (cmd.includes('summary')) return null; return Stp.render(S.stpTopo, m ? +m[1] : 1, dev.name, dev._all || {}); }
    let m;
    if ((m = cmd.match(/^show policy-map interfaces? (\S+)$/))) { const p = Sim.canonIf(m[1]); const i = S.ifaces[dev.name] && S.ifaces[dev.name][p]; return i ? policyOn(dev, S, i) : '% Invalid interface ' + m[1]; }
    if ((m = cmd.match(/^show interfaces? (\S+) sw\S*$/))) { const p = Sim.canonIf(m[1]); const i = S.ifaces[dev.name] && S.ifaces[dev.name][p]; if (!i) return '% Invalid interface ' + m[1]; return switchportDetail(dev, S, i); }
    if ((m = cmd.match(/^show interfaces? (\S+)$/)) && !['trunk', 'status', 'description'].includes(m[1])) { const p = Sim.canonIf(m[1]); const i = S.ifaces[dev.name] && S.ifaces[dev.name][p]; return i ? ifaceDetail(dev, S, i) : '% Invalid interface ' + m[1]; }
    if ((m = cmd.match(/^show ip interface (\S+)$/)) && m[1] !== 'brief') { const p = Sim.canonIf(m[1]); const i = S.ifaces[dev.name] && S.ifaces[dev.name][p]; if (!i) return '% Invalid interface'; return long(p) + ' is ' + (i.up ? 'up' : 'down') + ', line protocol is ' + (i.up ? 'up' : 'down') + '\n  Internet address is ' + (i.cfg.ip ? i.cfg.ip + '/' + Net.mlen(i.cfg.mask) : 'not set') + '\n  Outgoing access list is ' + (i.cfg.aclOut || 'not set') + '\n  Inbound  access list is ' + (i.cfg.aclIn || 'not set') + '\n  NAT ' + (i.cfg.natInside ? 'inside' : i.cfg.natOutside ? 'outside' : 'disabled'); }
    if ((m = cmd.match(/^show port-security interface (\S+)$/))) { const p = Sim.canonIf(m[1]); const s = S.portsec[dev.name + '|' + p]; if (!s) return 'Port Security              : Disabled'; if (s.rejected) return 'Port Security              : Disabled\n(command rejected: port must be in access mode first)'; return 'Port Security              : Enabled\nPort Status                : ' + s.status + '\nViolation Mode             : ' + s.violation + '\nMaximum MAC Addresses      : ' + s.max + '\nTotal MAC Addresses        : ' + (s.allowed.length + s.learned.length) + '\nSticky MAC Addresses       : ' + (s.sticky ? s.learned.length : 0) + '\nSecurity Violation Count   : ' + s.violations; }
    if ((m = cmd.match(/^show (?:ip )?access-lists? (\S+)$/))) { const a = S.cfg[dev.name].acls[m[1]]; if (!a) return '% ACL ' + m[1] + ' not found'; return (a.type === 'standard' ? 'Standard' : 'Extended') + ' IP access list ' + m[1] + '\n' + a.entries.map(e => '    ' + e.seq + ' ' + e.action + ' ' + e.raw).join('\n'); }
    // exact / prefix match against renderer keys
    if (R[cmd]) return R[cmd](dev, S);
    const st = t; for (const k of Object.keys(R)) { const kt = k.split(' '); if (kt.length !== st.length) continue; let ok = true; for (let i = 0; i < kt.length; i++) if (!kt[i].startsWith(st[i])) { ok = false; break; } if (ok) return R[k](dev, S); }
    return null;
  }

  // a ping from a PC that was translated on the way: every router it crossed now holds the translation (show ip nat translations)
  function noteNat(dev, r){ if (!r || !r.nat || !r.nat.length || !dev._all) return; Object.values(dev._all).forEach(o => { if (o === dev || !(r.path || []).some(p => p.dev === o.name)) return; o._natSeen = o._natSeen || [];
    r.nat.forEach(t => { if (!o._natSeen.some(x => x.inside === t.inside && x.global === t.global && x.port === t.port && x.outside === t.outside)) o._natSeen.push(t); }); }); }

  // ---- host console (PC1>)
  function host(dev, raw, S){
    const t = raw.trim().split(/\s+/); const c = (t[0] || '').toLowerCase(); const h = S && S.hosts[dev.name];
    if (!c) return '';
    if (c === 'help' || c === '?') return 'ping <ip>   ipconfig [/all]   arp -a   tracert <ip>';
    if (!h) return 'no network stack';
    if (c === 'ipconfig') { const all = (t[1] || '').toLowerCase() === '/all'; return 'Ethernet adapter Local Area Connection:\n   ' + (h.up ? '' : 'Media State . . . . . . . . . . . : Media disconnected\n   ') + (all ? 'Physical Address. . . . . . . . . : ' + h.mac.toUpperCase() + '\n   DHCP Enabled. . . . . . . . . . . : ' + (h.dhcp ? 'Yes' : 'No') + '\n   ' : '') + 'IPv4 Address. . . . . . . . . . . : ' + (h.ip || '(none)' + (h.lease && h.lease.reason ? '  — ' + h.lease.reason : '')) + '\n   Subnet Mask . . . . . . . . . . . : ' + (h.mask || '') + '\n   Default Gateway . . . . . . . . . : ' + (h.gw || '') + (all ? '\n   DNS Servers . . . . . . . . . . . : ' + ((h.dns && [].concat(h.dns).join(', ')) || '') + (h.server ? '\n   DHCP Server . . . . . . . . . . . : ' + h.server + (h.rogue ? '   (!)' : '') : '') : ''); }
    if (c === 'arp' && (t[1] || '').toLowerCase() === '-d') { Net.forget(S, 'arp', dev.name); return ''; }
    if (c === 'arp') { const rows = Net.arpRows(S, dev.name); if (!rows.length) return 'No ARP Entries Found.'; const dash = m => m.replace(/\./g, '').replace(/(..)(?!$)/g, '$1-'); return 'Interface: ' + (h.ip || '0.0.0.0') + ' --- 0x1\n  Internet Address      Physical Address      Type\n' + rows.map(o => '  ' + pad(o.ip, 22) + pad(dash(o.mac), 22) + 'dynamic').join('\n'); }
    if (c === 'ping' || c === 'tracert' || c === 'traceroute') { const ip = t[1]; if (!ip) return 'Usage: ' + c + ' <ip>'; const r = Net.ping(S, dev.name, ip); dev._lastPing = r; noteNat(dev, r); const lost = r.ok && Net.learnFrom(S, r) > 0 ? 1 : 0; if (!r.ok) Net.learnFrom(S, r);
      const reply = 'Reply from ' + ip + ': bytes=32 time<1ms TTL=' + (128 - Math.max(0, (r.hops || 0))) + '\n';
      if (c === 'ping') return 'Pinging ' + ip + ' with 32 bytes of data:\n' + (r.ok ? 'Request timed out.\n'.repeat(lost) + reply.repeat(4 - lost) + '\nPing statistics for ' + ip + ':\n    Packets: Sent = 4, Received = ' + (4 - lost) + ', Lost = ' + lost + ' (' + lost * 25 + '% loss)' : (/^loop at /.test(r.reason || '') && (r.trail || []).length ? ('Reply from ' + r.trail[r.trail.length - 1] + ': TTL expired in transit.\n').repeat(4) + '\nPing statistics for ' + ip + ':\n    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss)\n  [why: ' + r.reason + ', the packet went round until its TTL reached 0]' : 'Request timed out.\nRequest timed out.\nRequest timed out.\nRequest timed out.\n\nPing statistics for ' + ip + ':\n    Packets: Sent = 4, Received = 0, Lost = 4 (100% loss)\n  [why: ' + r.reason + ']'));
      return 'Tracing route to ' + ip + ' over a maximum of 30 hops:\n\n' + Net.traceLines(r, 'pc').join('\n') + (r.ok ? '\n\nTrace complete.' : '\n  [why: ' + r.reason + ']'); }
    return "'" + t[0] + "' is not recognized. Type help."; }

  window.Show = { render, host, renderers: R, long };
})();
