"""extract_card_images.py — pull the pictures out of the Anki decks and link them to the imported cards.

Reads every .apkg in <folder> the same way tools/import_apkg.py does (same order, same card ids), copies each picture a
card uses into assets/cards/dayNN/ as a small webp, and writes js/data/cards/images.js: { cardId: 'assets/cards/...' }.
The card text files are not touched. Run it again whenever decks are re-imported.
    python tools/extract_card_images.py "C:/Users/Seonso/Desktop/CCNA Course Files"
"""
import io, json, os, re, sys, zipfile
sys.path.insert(0, os.path.dirname(__file__))
from import_apkg import read_apkg  # noqa: E402
from PIL import Image  # noqa: E402

def main():
    folder = sys.argv[1]; out_js = 'js/data/cards/images.js'; out_dir = 'assets/cards'
    files = sorted(f for f in os.listdir(folder) if f.lower().endswith('.apkg'))
    by_day = {}
    for f in files:
        m = re.search(r'Day\s*(\d+)', f); by_day.setdefault(int(m.group(1)) if m else 0, []).append(f)
    mapping, count = {}, 0
    for f in files:
        m = re.search(r'Day\s*(\d+)', f); day = int(m.group(1)) if m else 0
        letter = chr(ord('a') + by_day[day].index(f)) if len(by_day[day]) > 1 else ''
        path = os.path.join(folder, f)
        try: cards = read_apkg(path)
        except Exception as e: print('skip', f, e); continue
        with zipfile.ZipFile(path) as z:
            try: media = json.loads(z.read('media').decode('utf-8') or '{}')
            except Exception: media = {}
            by_name = {v: k for k, v in media.items()}
            for i, c in enumerate(cards):
                if not c.get('imgs'): continue
                src = c['imgs'][0]; key = by_name.get(src)
                if key is None or key not in z.namelist(): continue
                cid = 'd%02d%s-%03d' % (day, letter, i + 1)
                try: im = Image.open(io.BytesIO(z.read(key))).convert('RGBA')
                except Exception: continue
                if im.width > 480: im = im.resize((480, round(im.height * 480 / im.width)), Image.LANCZOS)
                d = os.path.join(out_dir, 'day%02d' % day); os.makedirs(d, exist_ok=True)
                rel = '%s/%s.webp' % (d.replace(os.sep, '/'), cid); im.save(rel, quality=82)
                mapping[cid] = rel; count += 1
    lines = ['/* generated by tools/extract_card_images.py — the picture each card shows, by card id. */',
             'window.CARD_IMAGES = ' + json.dumps(mapping, indent=0, sort_keys=True) + ';']
    open(out_js, 'w', encoding='utf-8', newline='\n').write('\n'.join(lines) + '\n')
    print('pictures:', count)

if __name__ == '__main__':
    main()
