"""import_apkg.py — turn Anki decks (.apkg) into game flash cards.

Jeremy's IT Lab publishes one deck per day: "Day 21 Flashcards - Spanning Tree Protocol (Part 2).apkg".
Download the Drive folder to a local directory, then:

  python tools/import_apkg.py "C:/path/to/CCNA course files" --out js/data/cards

One file per day is written: js/data/cards/day21.js, each pushing onto window.CARDS.
Card shape: { id, day, deck, skill, q, a, type:'text'|'choice', opts?, tags, why? }
- q/a are plain text (HTML stripped). Cloze notes become q with ____ and a with the hidden text.
- `skill` comes from DAY_SKILL below (edit it as stages get built); falls back to 'day-NN'.
- The importer never overwrites a file that has been hand-edited (it checks for the marker "hand-edited").

No third-party packages. Uses zipfile + sqlite3 from the standard library.
"""
import argparse, html, json, os, re, sqlite3, sys, tempfile, zipfile

DAY_SKILL = {
    1: 'osi-layers', 2: 'osi-layers', 3: 'osi-layers', 4: 'cli-modes', 5: 'mac-table', 6: 'mac-table', 7: 'subnetting', 8: 'subnetting', 9: 'mac-table', 10: 'subnetting',
    11: 'static-route', 12: 'subnetting', 13: 'subnetting', 14: 'static-route', 15: 'static-route', 16: 'vlan-config', 17: 'vlan-config', 18: 'vlan-config', 19: 'trunk-config',
    20: 'stp-election', 21: 'stp-config', 22: 'stp-states', 23: 'trunk-config', 24: 'static-route', 25: 'static-route', 26: 'static-route', 27: 'static-route', 28: 'static-route', 29: 'static-route',
    30: 'osi-layers', 31: 'subnetting', 32: 'subnetting', 33: 'subnetting', 34: 'acl-standard', 35: 'acl-standard', 36: 'cli-modes', 37: 'dhcp', 38: 'dhcp', 39: 'dhcp', 40: 'cli-modes',
    41: 'cli-modes', 42: 'cli-modes', 43: 'cli-modes', 44: 'static-route', 45: 'static-route', 46: 'osi-layers', 47: 'osi-layers', 48: 'port-security', 49: 'port-security', 50: 'port-security',
    51: 'virtualization', 52: 'virtualization', 53: 'virtualization', 54: 'virtualization', 55: 'virtualization', 56: 'virtualization', 57: 'virtualization', 58: 'virtualization', 59: 'virtualization', 60: 'virtualization',
    61: 'virtualization', 62: 'virtualization', 63: 'virtualization',
}

TAG = re.compile(r'<[^>]+>')
CLOZE = re.compile(r'\{\{c\d+::(.*?)(?:::.*?)?\}\}')


def clean(s):
    s = s.replace('<br>', '\n').replace('<br/>', '\n').replace('<br />', '\n').replace('</div>', '\n')
    s = TAG.sub('', s); s = html.unescape(s)
    s = re.sub(r'\[sound:[^\]]+\]', '', s)
    return re.sub(r'\n{3,}', '\n\n', s).strip()


def read_apkg(path):
    with zipfile.ZipFile(path) as z:
        name = 'collection.anki21' if 'collection.anki21' in z.namelist() else 'collection.anki2'
        tmp = tempfile.NamedTemporaryFile(delete=False, suffix='.anki2'); tmp.write(z.read(name)); tmp.close()
    con = sqlite3.connect(tmp.name); cur = con.cursor()
    models = json.loads(cur.execute('select models from col').fetchone()[0])
    decks = json.loads(cur.execute('select decks from col').fetchone()[0])
    out = []
    for nid, mid, flds, tags in cur.execute('select id, mid, flds, tags from notes'):
        model = models.get(str(mid)) or {}
        fields = flds.split('\x1f'); names = [f['name'] for f in model.get('flds', [])]
        is_cloze = model.get('type') == 1 or 'cloze' in (model.get('name', '').lower())
        if is_cloze:
            text = clean(fields[0]); answers = CLOZE.findall(fields[0])
            q = CLOZE.sub('____', fields[0]); q = clean(q); a = ' / '.join(clean(x) for x in answers)
        else:
            q = clean(fields[0]) if fields else ''; a = clean(fields[1]) if len(fields) > 1 else ''
        if not q or not a: continue
        out.append({'nid': nid, 'q': q, 'a': a, 'tags': [t for t in tags.split() if t]})
    con.close(); os.unlink(tmp.name)
    return out


def main():
    ap = argparse.ArgumentParser(); ap.add_argument('folder'); ap.add_argument('--out', default='js/data/cards'); ap.add_argument('--force', action='store_true')
    a = ap.parse_args(); os.makedirs(a.out, exist_ok=True)
    files = sorted(f for f in os.listdir(a.folder) if f.lower().endswith('.apkg'))
    if not files: sys.exit('no .apkg files in ' + a.folder)
    total = 0
    for f in files:
        m = re.search(r'Day\s*(\d+)', f); day = int(m.group(1)) if m else 0
        deck = re.sub(r'^Day\s*\d+\s*Flashcards\s*-\s*', '', f)[:-5].strip()
        cards = read_apkg(os.path.join(a.folder, f))
        out_path = os.path.join(a.out, 'day%02d.js' % day)
        if os.path.exists(out_path) and not a.force and 'hand-edited' in open(out_path, encoding='utf-8').read():
            print('skip (hand-edited):', out_path); continue
        skill = DAY_SKILL.get(day, 'day-%02d' % day)
        lines = ['/* generated by tools/import_apkg.py from "%s" — %d cards. Add "hand-edited" to this comment to protect edits. */' % (f, len(cards)), '(function(){ window.CARDS = window.CARDS || [];', '  const D = %d, K = %s, DECK = %s;' % (day, json.dumps(skill), json.dumps(deck))]
        for i, c in enumerate(cards):
            lines.append('  CARDS.push({ id: "d%02d-%03d", day: D, deck: DECK, skill: K, type: "text", q: %s, a: %s, tags: %s });' % (day, i + 1, json.dumps(c['q'], ensure_ascii=False), json.dumps(c['a'], ensure_ascii=False), json.dumps(c['tags'])))
        lines.append('})();')
        open(out_path, 'w', encoding='utf-8', newline='\n').write('\n'.join(lines) + '\n')
        print('wrote', out_path, len(cards), 'cards'); total += len(cards)
    print('total cards:', total)
    print('now add <script src="js/data/cards/dayNN.js"></script> lines to index.html (or run tools/check.js --fix-index)')


if __name__ == '__main__':
    main()
