"""import_apkg.py — turn Anki decks (.apkg) into game flash cards.

Jeremy's IT Lab publishes one deck per day: "Day 21 Flashcards - Spanning Tree Protocol (Part 2).apkg".
Download the Drive folder to a local directory, then:

  python tools/import_apkg.py "C:/path/to/CCNA course files" --out js/data/cards

One file per day is written: js/data/cards/day21.js, each pushing onto window.CARDS.
Card shape: { id, day, deck, skill, q, a, type:'text'|'choice', opts?, tags, why? }
- q/a are plain text (HTML stripped). Cloze notes become q with ____ and a with the hidden text.
- `skill` comes from DAY_SKILL below (edit it as stages get built); falls back to 'day-NN'. Cards unlock when a
  level whose `day` list contains the card's day has been read, or when the card's real skill is slotted.
- The importer never overwrites an existing file unless --force; a first line containing HAND-EDITED is never overwritten.

No third-party packages. Uses zipfile + sqlite3 from the standard library.
"""
import argparse, html, io, json, os, re, sqlite3, sys, tempfile, zipfile

DAY_SKILL = {
    # Only days with a built level map to a real skill (feeds STATS "weak skills"). Every other day gets
    # the pseudo-skill 'day-NN'; such cards unlock when any level covering that day has been read.
    1: 'net-devices', 2: 'cabling', 4: 'cli-modes', 20: 'stp-election', 21: 'stp-config',
}

TAG = re.compile(r'<[^>]+>')
CLOZE = re.compile(r'\{\{c\d+::(.*?)(?:::.*?)?\}\}')


def clean(s):
    s = s.replace('<br>', '\n').replace('<br/>', '\n').replace('<br />', '\n').replace('</div>', '\n')
    s = TAG.sub('', s); s = html.unescape(s)
    s = re.sub(r'\[sound:[^\]]+\]', '', s)
    return re.sub(r'\n{3,}', '\n\n', s).strip()


def read_apkg(path):
    with zipfile.ZipFile(path) as z:
        names = z.namelist()
        tmp = tempfile.NamedTemporaryFile(delete=False, suffix='.anki2')
        if 'collection.anki21b' in names:
            # newer Anki: the collection is a zstd-compressed SQLite file (pip install zstandard)
            import zstandard
            tmp.write(zstandard.ZstdDecompressor().stream_reader(io.BytesIO(z.read('collection.anki21b'))).read())
        else:
            name = 'collection.anki21' if 'collection.anki21' in names else 'collection.anki2'
            tmp.write(z.read(name))
        tmp.close()
    con = sqlite3.connect(tmp.name); cur = con.cursor()
    try: models = json.loads(cur.execute('select models from col').fetchone()[0] or '{}')
    except Exception: models = {}
    out = []
    for nid, mid, flds, tags in cur.execute('select id, mid, flds, tags from notes'):
        model = models.get(str(mid)) or {}
        fields = flds.split('\x1f'); names = [f['name'] for f in model.get('flds', [])]
        is_cloze = model.get('type') == 1 or 'cloze' in (model.get('name', '').lower()) or bool(CLOZE.search(fields[0] if fields else ''))
        if is_cloze:
            text = clean(fields[0]); answers = CLOZE.findall(fields[0])
            q = CLOZE.sub('____', fields[0]); q = clean(q); a = ' / '.join(clean(x) for x in answers)
        else:
            q = clean(fields[0]) if fields else ''; a = clean(fields[1]) if len(fields) > 1 else ''
        if not q or not a: continue
        imgs = re.findall(r'<img[^>]+src="([^"]+)"', flds)
        out.append({'nid': nid, 'q': q, 'a': a, 'tags': [t for t in tags.split() if t], 'imgs': imgs})
    con.close(); os.unlink(tmp.name)
    return out


def main():
    ap = argparse.ArgumentParser(); ap.add_argument('folder'); ap.add_argument('--out', default='js/data/cards'); ap.add_argument('--force', action='store_true')
    a = ap.parse_args(); os.makedirs(a.out, exist_ok=True)
    files = sorted(f for f in os.listdir(a.folder) if f.lower().endswith('.apkg'))
    if not files: sys.exit('no .apkg files in ' + a.folder)
    total = 0
    by_day = {}
    for f in files:
        m = re.search(r'Day\s*(\d+)', f); by_day.setdefault(int(m.group(1)) if m else 0, []).append(f)
    for f in files:
        m = re.search(r'Day\s*(\d+)', f); day = int(m.group(1)) if m else 0
        deck = re.sub(r'^Day\s*\d+\s*(\([^)]*\)\s*)?Flashcards\s*(\([^)]*\)\s*)?-\s*', '', f)[:-5].strip()
        letter = chr(ord('a') + by_day[day].index(f)) if len(by_day[day]) > 1 else ''
        cards = read_apkg(os.path.join(a.folder, f))
        if not cards: print('skip (0 cards):', f); continue
        out_path = os.path.join(a.out, 'day%02d%s.js' % (day, letter))
        if os.path.exists(out_path) and not a.force and 'HAND-EDITED' in open(out_path, encoding='utf-8').readline():
            print('skip (hand-edited):', out_path); continue
        if os.path.exists(out_path) and not a.force:
            print('skip (exists, use --force to regenerate):', out_path); continue
        skill = DAY_SKILL.get(day, 'day-%02d' % day)
        lines = ['/* generated by tools/import_apkg.py from "%s" — %d cards. */' % (f, len(cards)), '/* To protect manual edits from --force, put the word HAND-EDITED on the first line above. */', '(function(){ window.CARDS = window.CARDS || [];', '  const D = %d, K = %s, DECK = %s;' % (day, json.dumps(skill), json.dumps(deck))]
        for i, c in enumerate(cards):
            lines.append('  CARDS.push({ id: "d%02d%s-%03d", day: D, deck: DECK, skill: K, type: "text", q: %s, a: %s, tags: %s });' % (day, letter, i + 1, json.dumps(c['q'], ensure_ascii=False), json.dumps(c['a'], ensure_ascii=False), json.dumps(c['tags'])))
        lines.append('})();')
        open(out_path, 'w', encoding='utf-8', newline='\n').write('\n'.join(lines) + '\n')
        print('wrote', out_path, len(cards), 'cards'); total += len(cards)
    print('total cards:', total)
    print('now add <script src="js/data/cards/dayNN.js"></script> lines to index.html (or run tools/check.js --fix-index)')


if __name__ == '__main__':
    main()
